<?php
/**
 * Created by PhpStorm.
 * User: acid
 * Date: 16.09.18
 * Time: 10:33
 */

namespace frontend\modules\mails\models;

use app\helpers\GridHelper;
use Yii;
use yii\helpers\ArrayHelper;

class StartForm extends \yii\base\Model
{
  public $options;

  public $data;

  private $_rules = [];
  private $_attributes = [];
  private $_attributes_labels = [];
  private $_attributes_hints = [];

  /* @var Template */
  private $_template;

  /**
   * Creates a form model for given template.
   *
   */
  public function __construct(TemplateMail $template)
  {
    $this->_template = $template;

    parent::__construct();
  }

  public function init()
  {
    $this->configureOptions($this->getVisitorCheckOptions());

    parent::init(); // TODO: Change the autogenerated stub
  }

  public function rules()
  {
    return array_merge([], $this->_rules);
  }

  public function attributeLabels()
  {
    return array_merge(parent::attributeLabels(), $this->_attributes_labels);
  }

  public function getFieldTemplate($fieldOptions, $name)
  {
    $request = Yii::$app->request;

    if (isset($fieldOptions['checkbox']) && $fieldOptions['checkbox']) {
      $name = $name . '_active';
      $check = isset($request->post($this::formName())[$name]) ? ' checked ' : '';

      $name = $this::formName() . '[' . $name . ']';

      $cb = '<input type="checkbox" class="activator" name="' . $name . '" ' . $check . '><span class="fa fa-check"></span>';
      return [
          'template' => "<div class='checkbox_box' >$cb\n{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}</div>",
      ];
    }

    return [];
  }

  public function attributeHints()
  {
    return array_merge(parent::attributeHints(), $this->_attributes_hints);
  }


  public function configureOptions($options)
  {
    $request = Yii::$app->request;
    $post = $request->post(self::formName());

    $this->options = $options;

    foreach ($options as $fieldName => $fieldOptions) {
      // Attribute
      $this->_attributes[$fieldName] = isset($fieldOptions['value']) ? $fieldOptions['value'] : null;

      // Label
      if (isset($fieldOptions['label'])) {
        $this->_attributes_labels[$fieldName] = $fieldOptions['label'];
      }

      // Hint
      if (isset($fieldOptions['hint'])) {
        $this->_attributes_hints[$fieldName] = $fieldOptions['hint'];
      }

      // Rules
      $rules = $fieldOptions['rules'];
      array_unshift($rules, ['safe']);

      foreach ($rules as $rule) {
        array_unshift($rule, [$fieldName]);
        if (!isset($fieldOptions['checkbox']) ||
            isset($post[$fieldName . '_active'])
        ) {
          $this->_rules[] = $rule;
        }
      }
    }

    //print_r($this->_rules);
  }

  /**
   * @inheritdoc
   */
  public function canGetProperty($name, $checkVars = true, $checkBehaviors = true)
  {
    if (isset($this->_attributes[$name])) {
      return true;
    }

    return parent::canGetProperty($name, $checkVars, $checkBehaviors);
  }

  /**
   * @inheritdoc
   */
  public function canSetProperty($name, $checkVars = true, $checkBehaviors = true)
  {
    if (isset($this->_attributes[$name])) {
      return true;
    }

    return parent::canSetProperty($name, $checkVars, $checkBehaviors);
  }

  /**
   * @inheritdoc
   */
  public function __get($name)
  {
    if (isset($this->_attributes[$name])) {
      return $this->_attributes[$name];
    }

    return parent::__get($name);
  }

  /**
   * @inheritdoc
   */
  public function __set($name, $value)
  {
    if (isset($this->_attributes[$name])) {
      $this->_attributes[$name] = $value;
    } else {
      parent::__set($name, $value);
    }
  }


  public function getVisitorCheckOptions()
  {
    $cafe = Yii::$app->cafe->get();

    $dateFormat = Yii::$app->params['lang']['date'];

    $options = array_merge([
        'visit_type' => [
            'label' => Yii::t('app', 'Visit type'),
            'checkbox' => true,
            'value' => -1,
            'rules' => [
                ['required'],
            ],
            'inputOptions' => [
                'type' => 'dropDown',
                'items' => ArrayHelper::merge(
                    [
                        '-1' => Yii::t('app', "All registered"),
                    ],
                    \frontend\modules\visits\models\VisitorLog::typeList(),
                    [
                        100 => Yii::t('app', "With children"),
                    ]
                ),
            ],
        ],
        'visit_date' => [
            'label' => Yii::t('app', 'Visit date'),
            'checkbox' => true,
            'value' =>
                date($dateFormat, strtotime("-1 month")) .
                ' - ' .
                date($dateFormat),
            'rules' => [
                ['required'],
            ],
            'inputOptions' => [
                'type' => 'dateRange',
            ],
        ],
        'registration_date' => [
            'label' => Yii::t('app', 'Registration date'),
            'checkbox' => true,
            'value' =>
                date($dateFormat, strtotime("-1 month")) .
                ' - ' .
                date($dateFormat),
            'rules' => [
                ['required'],
            ],
            'inputOptions' => [
                'type' => 'dateRange',
            ],
        ],

        'visit_count_min' => [
            'label' => Yii::t('app', 'Min visit count'),
            'checkbox' => true,
            'value' => 0,
            'rules' => [
                ['integer'],
                ['required'],
            ],
        ],
        'visit_count_max' => [
            'label' => Yii::t('app', 'Max visit count'),
            'checkbox' => true,
            'value' => 10,
            'rules' => [
                ['integer'],
                ['required'],
            ],
        ],
    ]);


    return $options;
  }

  public function filterarams()
  {
    $options = $this->getVisitorCheckOptions();
    $params = [];
    $request = Yii::$app->request;
    $post = $request->post(self::formName());
    foreach ($options as $name => $param) {
      if (!isset($param['checkbox']) || ($param['checkbox'] && !empty($post[$name . '_active']))) {
        if (!empty($post[$name])) {
          if (isset($param['inputOptions']) && !empty($param['inputOptions']['type']) && $param['inputOptions']['type'] == 'dateRange') {

            $date_range = explode(' - ', $post[$name]);
            foreach ($date_range as &$d) {
              $d = GridHelper::getDbDateFromDateRangeFormat($d, null, false);
            }
            $params[$name] = $date_range;
          } else {
            $params[$name] = $post[$name];
          }
        }
      }
    }

    return $params;
  }
}