<?php

namespace frontend\modules\mails\models;

use frontend\modules\cafe\models\Cafe;
use frontend\modules\templates\models\Template;
use Yii;
use yii\helpers\Url;

/**
 * This is the model class for table "template_mail".
 *
 * @property int $id
 * @property string $content
 * @property array $user_filter
 * @property int $status
 * @property int $cafe_id
 * @property int $updated_at
 * @property int $created_at
 *
 * @property Cafe $cafe
 */
class TemplateMail extends Template
{

  public $status;


  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return 'template_mails';
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
        [['title'], 'required'],
        [['title'], 'string', 'min' => 6, 'max' => 255],
        [['content', 'background'], 'string'],
        [['user_filter'], 'safe'],
        [['status', 'cafe_id', 'updated_at', 'created_at'], 'integer'],
        [['width'], 'integer'],
        [['cafe_id'], 'exist', 'skipOnError' => true, 'targetClass' => Cafe::className(), 'targetAttribute' => ['cafe_id' => 'id']],
    ];
  }


  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
        'id' => Yii::t('app', 'ID'),
        'content' => Yii::t('app', 'Content'),
        'title' => Yii::t('app', 'Title'),
        'user_filter' => Yii::t('app', 'User Filter'),
        'status' => Yii::t('app', 'Status'),
        'width' => Yii::t('app', 'width'),
        'cafe_id' => Yii::t('app', 'Cafe ID'),
        'updated_at' => Yii::t('app', 'Updated At'),
        'created_at' => Yii::t('app', 'Created At'),
    ];
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getCafe($cafe_id = NULL)
  {
    return $this->hasOne(Cafe::className(), ['id' => 'cafe_id']);
  }

  public function beforeValidate()
  {
    $this->cafe_id = Yii::$app->cafe->id;
    return parent::beforeValidate(); // TODO: Change the autogenerated stub
  }

  public function getParams()
  {
    return [
        'is_print' => false,
        'vars' => [
            [
                'name' => 'Cafe',
                'prefix' => 'cafe.',
                'items' => [
                    'name' => "cafe name",
                    'address' => "address",
                    'currency' => 'currency',
                    'logo' => "logo url",
                    'max_person' => "max person",
                    'vat_code_line' => "Vat codes in line",
                    'vat_code_column' => "Vat codes in column"
                ]
            ],
            [
                'name' => 'Visitor',
                'prefix' => 'visitor.',
                'items' => [
                    'f_name' => "First name",
                    'l_name' => "Last name",
                    'code' => "code",
                    'email' => "email",
                    'phone' => "phone",
                ]
            ]
        ]
    ];
  }

  public static function getButtons($mode)
  {
    $list = self::find()
        ->select(['id', 'title'])
        ->where(['cafe_id' => Yii::$app->cafe->id])
        ->asArray()
        ->orderBy(['id' => SORT_DESC])
        ->all();

    if (count($list) == 0) return '';

    $out = '<div class="btn-group">
  <button type="button" class="btn bg-blue fg-white dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-send-o"></i>
    ' . Yii::t('app', 'Send mails') . ' <span class="caret"></span></button>
  <div class="dropdown-menu"><li class="dropdown-header" >' . Yii::t('main', 'Mails') . '</li>';
    foreach ($list as $li) {
      $url = Url::toRoute(['/mails/admin/start', 'id' => $li['id'], 'type' => $mode]);
      $out .= '<li><a 
          class="dropdown-item testChechedRow" 
          href="' . $url . '"
          role="modal-remote-bulk" 
          data-request-method="post" 
          data-confirm-title="' . Yii::t('app', 'Are you sure?') . '" 
          data-confirm-message="' . Yii::t('app', 'Are you sure want to send mail for this item') . '"
          >' . $li['title'] . ' <span class="label label-info font-weight-400 pull-right">' . Yii::t('app', '#') . '' . $li['id'] . '</span></a></li>';
    }
    $out
        .= '<li class="dropdown-item-text"><a>' . Yii::t('app', 'Choose letter template') . '</a></li></div>
</div>
    ';


    return $out;
  }


}


//<a class="btn btn-danger margin-right-10 testChechedRow" href="/visits/admin/bulk-delete" title="Delete All" role="modal-remote-bulk" data-request-method="post" data-confirm-title="Are you sure?" data-confirm-message="Are you sure want to delete this item"><i class="glyphicon glyphicon-trash"></i> Delete All</a>