<?php
/**
 * Created by PhpStorm.
 * User: acid
 * Date: 16.09.18
 * Time: 10:33
 */

namespace frontend\modules\mails\models;

use common\components\VatHelper;
use frontend\modules\cafe\models\CafeParams;
use Yii;

class TestForm extends \yii\base\Model
{
  public $options;

  public $data;

  private $_rules = [];
  private $_attributes = [];
  private $_attributes_labels = [];
  private $_attributes_hints = [];

  /* @var Template */
  private $_template;

  /**
   * Creates a form model for given template.
   *
   */
  public function __construct(TemplateMail $template)
  {
    $this->_template = $template;

    parent::__construct();
  }

  public function init()
  {
    $this->configureOptions($this->getVisitorCheckOptions());

    parent::init(); // TODO: Change the autogenerated stub
  }

  public function rules()
  {
    return array_merge([], $this->_rules);
  }

  public function attributeLabels()
  {
    return array_merge(parent::attributeLabels(), $this->_attributes_labels);
  }

  public function attributeHints()
  {
    return array_merge(parent::attributeHints(), $this->_attributes_hints);
  }

  public function process()
  {
    if (!$this->validate()) {
      return false;
    }

    foreach ($this->options as $fieldName => $fieldOptions) {
      if (isset($fieldOptions['fetchData'])) {
        $fetchData = $fieldOptions['fetchData'];
        call_user_func($fetchData, $this->{$fieldName});
      }
    }

    return true;
  }

  public function getContent()
  {
    $id = $this->_template->id;

    $content = $this->_template->renderTemplate($this->data);

    try {
      $sended = \Yii::$app->mailer->compose()
          ->setFrom(Yii::$app->params['robotEmail'])
          ->setTo($this->email)
          ->setSubject($this->_template->subject)
          ->setHtmlBody($content);

      if (Yii::$app->cafe->get()->pdf_to_mail) {
        Yii::$app->helper->addPdfToMail($sended, $content);
      }
      $sended->send();
    } catch (\Exception $e) {
      //return ($e->getMessage());
      $sended = false;
    }

    if ($sended) {
      return Yii::t('main', 'Email successfully sended, check your inbox');
    } else {
      return Yii::t('main', 'Email sending error');
    }
  }

  public function getFieldTemplate($fieldOptions)
  {
    return [];
  }

  public function getVisitorCheckOptions()
  {
    $cafe = Yii::$app->cafe->get();
    $params = $cafe->getParam()->asArray()->one();
    $langParams = CafeParams::composeLangParams($params);
    $cafeCurrency = Yii::t('app', $cafe->currency);

    $total_visit = [
        'cost' => 0,
        'sum' => 0,
        'vat' => [],
        'vat_total' => 0,
    ];

    $options = [];
    $summary_vat = [];

    $visit = [
        'id' => 4654,
        'add_time' => date($langParams['datetime'], strtotime('2018-10-17 21:03:57')),
        'finish_time' => date($langParams['datetime'], strtotime('2018-10-17 22:03:57')),
        'duration' => Yii::$app->helper->echo_time(3600),
        'pause' => Yii::$app->helper->echo_time(0),
        'cost' => 5.06,
        'sum' => 4.4,
        'guest_m' => 0,
        'guest_chi' => 0,
    ];

    list($sum, $cost, $vat, $vatTotal) = VatHelper::calculate($visit['sum']);
    $visit['vat'] = $vat;

    $total_visit['cost'] = $visit['cost'];
    $total_visit['sum'] = $visit['sum'];

    // VAT Merging copy-paste from populateUniteData()
    foreach ($visit['vat'] as $vat) {
      $vat_merged = false;

      foreach ($summary_vat as $uniteVatIndex => $uniteVat) {
        // If VAT equals - merge it
        if ($uniteVat['name'] == $vat['name']) {
          $vat_merged = true;
          $summary_vat[$uniteVatIndex]['vat'] = ((float)$summary_vat[$uniteVatIndex]['vat'] + (float)$summary_vat[$uniteVatIndex]['vat']);
        }
      }

      // If VAT is absent - add it
      if (!$vat_merged) {
        $summary_vat[] = $vat;
      }

      $visit['vat'][$vat['name']] = $vat;
      $visit['vat'][$vat['name']]['vat'] .= ' ' . $cafeCurrency;
    }

    foreach ($summary_vat as $sVat) {
      $total_visit['vat'][$sVat['name']] = $sVat;
      $total_visit['vat'][$sVat['name']]['vat'] .= ' ' . $cafeCurrency;
      $total_visit['vat_total'] += $sVat['vat'];
    }

    $total_visit['cost'] .= ' ' . $cafeCurrency;
    $total_visit['sum'] .= ' ' . $cafeCurrency;
    $total_visit['vat_total'] .= ' ' . $cafeCurrency;

    $this->data = [
        'cafe' => $cafe->getAttributes(['id', 'name', 'max_person', 'address', 'currency', 'vat_code']),
        'visitor' => [
            'f_name' => "First name",
            'l_name' => "Last name",
            'code' => "code",
            'email' => "email",
            'phone' => "phone",
        ],
    ];

    $this->data['cafe']['logo'] = $cafe->getLogo();


    $options = array_merge($options, [
        'email' => [
            'label' => Yii::t('app', 'Send test to Email'),
            'value' => Yii::$app->user->identity->email,
            'rules' => [
                ['required'],
            ],
        ],
    ]);


    $options = array_merge($options, [

    ]);

    return $options;
  }

  public function configureOptions($options)
  {
    $this->options = $options;

    foreach ($options as $fieldName => $fieldOptions) {
      // Attribute
      $this->_attributes[$fieldName] = $fieldOptions['value'];

      // Label
      if (isset($fieldOptions['label'])) {
        $this->_attributes_labels[$fieldName] = $fieldOptions['label'];
      }

      // Hint
      if (isset($fieldOptions['hint'])) {
        $this->_attributes_hints[$fieldName] = $fieldOptions['hint'];
      }

      // Rules
      $rules = $fieldOptions['rules'];
      array_unshift($rules, ['safe']);

      foreach ($rules as $rule) {
        array_unshift($rule, [$fieldName]);
        $this->_rules[] = $rule;
      }
    }
  }

  /**
   * @inheritdoc
   */
  public function canGetProperty($name, $checkVars = true, $checkBehaviors = true)
  {
    if (isset($this->_attributes[$name])) {
      return true;
    }

    return parent::canGetProperty($name, $checkVars, $checkBehaviors);
  }

  /**
   * @inheritdoc
   */
  public function canSetProperty($name, $checkVars = true, $checkBehaviors = true)
  {
    if (isset($this->_attributes[$name])) {
      return true;
    }

    return parent::canSetProperty($name, $checkVars, $checkBehaviors);
  }

  /**
   * @inheritdoc
   */
  public function __get($name)
  {
    if (isset($this->_attributes[$name])) {
      return $this->_attributes[$name];
    }

    return parent::__get($name);
  }

  /**
   * @inheritdoc
   */
  public function __set($name, $value)
  {
    if (isset($this->_attributes[$name])) {
      $this->_attributes[$name] = $value;
    } else {
      parent::__set($name, $value);
    }
  }
}