<?php
/**
 * Created by PhpStorm.
 * User: max
 * Date: 18.01.19
 * Time: 10:59
 */

namespace frontend\components;


use Yii;
use yii\web\Request;

class HttpRequest extends Request
{

  public $noCsrfValidationRoutes = array();

  public function validateCsrfToken($clientSuppliedToken = null)
  {
    $route = Yii::$app->request->pathInfo;
    if ($this->enableCsrfValidation && array_search($route, $this->noCsrfValidationRoutes) !== false)
      return true;

    return parent::validateCsrfToken($clientSuppliedToken); // TODO: Change the autogenerated stub
  }

}
