<?php

namespace frontend\components;

use Yii;
use yii\rbac\DbManager;


class RBACmng extends DbManager
{
  public function checkAccess($userId, $permissionName, $params = [])
  {
    if ($permissionName == "ChooseCafe") {
      $cafe_list = Yii::$app->user->identity->cafesList;

      if (empty($cafe_list)) {
        return false;
      }
    }

    if (in_array($permissionName, Yii::$app->params['defaultAccess'])) {
      return true;
    };

    if (
        in_array($permissionName, Yii::$app->params['managerAccess']) &&
        count(Yii::$app->user->identity->getRoleOfUserArray()) == 0
    ) {
      return true;
    };

    return parent::checkAccess($userId, $permissionName, $params); // TODO: Change the autogenerated stub
  }

}