<?php

namespace frontend\components;


use common\components\SdViewBASE;
use kartik\growl\Growl;
use Yii;
use yii\web\View;

class ViewBASE extends View
{

  public $all_params = [];
  public $first_init = true;
  public $description;
  public $h1;
  public $meta_head;

  public $contentBD;

  public $user_id = false;
  public $user = [];

  public $cafe = [];

  public $isAjax = true;

  private function create_flash($type, $flashe)
  {

    if ($type == 'polls') {
      if (Yii::$app->cafe->can('Polls')) {
        $this->registerJs('openPoll(' . (int)$flashe['visitor_id'] . ',' . (int)$flashe['mode'] . ');');
        //return '<script>openPoll('.(int)$flashe['visitor_id'].','.(int)$flashe['mode'].');</script>';
      }
      return;
    }

    $title = false;
    $icon = false;
    if (is_array($flashe)) {
      if (isset($flashe['title'])) $title = trim($flashe['title'], '.');
      if (isset($flashe['icon'])) $no_show_page = $flashe['icon'];
      $txt = $flashe['message'];
    } else {
      $txt = $flashe;
    }
    if (mb_strlen($txt) < 5) {
      return '';
    }

    $type_list = [
        "info" => Growl::TYPE_INFO,
        "success" => Growl::TYPE_SUCCESS,
        "warning" => Growl::TYPE_WARNING,
        "error" => Growl::TYPE_DANGER,
    ];

    $type = isset($type_list[$type]) ? $type_list[$type] : Growl::TYPE_MINIMALIST;

    return Growl::widget([
        'type' => $type,
        'icon' => $icon,
        'title' => $title,
        'showSeparator' => true,
        'body' => $txt
    ]);
  }

  public function getNotification()
  {
    $session = Yii::$app->session;

    $flashes = $session->allFlashes;
    if (count($flashes) == 0) {
      return '';
    }

    $html = '';
    $flashes = array_reverse($flashes);
    foreach ($flashes as $type => $flashe) {
      //Yii::$app->session->removeFlash($type);
      if (is_array($flashe)) {
        if ((isset($flashe['title']) && isset($flashe['message'])) || isset($flashe['visitor_id'])) {
          $html .= $this->create_flash($type, $flashe);
        } else {
          $flashe = array_unique($flashe);
          foreach ($flashe as $txt) {
            $html .= $this->create_flash($type, $txt);
          }
        }
      } elseif (is_string($flashe)) {
        $html .= $this->create_flash($type, $flashe);
      }
    }

    // Remove flashes
    $session->removeAllFlashes();

    //Yii::$app->session->addFlash('error','test');
    return $html;
  }

  public function init_param()
  {
    if (!$this->first_init) return;

    $this->first_init = false;

    if (!Yii::$app->user->isGuest) {
      $this->user_id = Yii::$app->user->id;
      $user = Yii::$app->user->identity;
      $this->user = (array)$user->getIterator();

      $this->all_params['user'] = (array)$user->getIterator();
      $this->all_params['user_id'] = Yii::$app->user->id;

      $this->cafe = Yii::$app->cafe;
    }

    $request = Yii::$app->request;
    if ($request->isAjax) {
      if (strpos($request->pathInfo, 'selfservice')) {
        $this->registerJs('close_modal_timer_cnt=0;$(".modal-footer").removeClass("terminal_status");');
      }
      return;
    }
  }

  public function render($view, $params = [], $context = null)
  {
    $this->isAjax = false;
    //return parent::render($view, $params, $context); // TODO: Change the autogenerated stub
    if ($this->first_init) {
      $this->init_param();
    }

    $this->all_params = array_merge($this->all_params, $params);
    if ($this->all_params && isset($this->all_params['exception'])) {
      Yii::$app->params['exception'] = $this->all_params['exception'];
    };
    Yii::$app->params['all_params'] = $this->all_params;

    $tags = '';
    foreach (Yii::$app->view->metaTags as $meta) {
      $tags .= $meta;
    }
    preg_match_all('/<[\s]*meta[\s]*(name|property)="?' . '([^>"]*)"?[\s]*' . 'content="?([^>"]*)"?[\s]*[\/]?[\s]*>/si', $tags, $match);
    $tags = [];
    foreach ($match[2] as $k => $name) {
      $tags[$name] = $match[3][$k];
    }
    Yii::$app->view->metaTags = [];


    if (isset($this->all_params['title'])) {
      $this->title = $this->all_params['title'];
    }
    if (isset($this->all_params['description'])) {
      $this->description = $this->all_params['description'];
    }

    //d($this->title);
    //ddd($tags);
    $params = array_merge((array)$this, $this->all_params);
    unset($this->all_params['all_params']);
    if (empty($params['afterTable'])) $params['afterTable'] = '';
    if (empty($params['canCreate'])) $params['canCreate'] = false;
    return parent::render($view, $params, $context); // TODO: Change the autogenerated stub
  }

  public function clear()
  {
    $js = $this->js;
    parent::clear();
    $this->js = $js;
  }

  public function afterRender($viewFile, $params, &$output)
  {
    if ($this->first_init) {
      $this->init_param();
    }

    if (substr(Yii::$app->request->pathInfo, 0, 3) == "gii") return;
    $this->all_params = array_merge($this->all_params, $params);
    Yii::$app->params['all_params'] = $this->all_params;
    unset($this->all_params['all_params']);

    parent::afterRender($viewFile, $params, $output); // TODO: Change the autogenerated stub
    //ddd($this->all_params);

    if ($this->isAjax || strpos($output, '</body>') !== false) {
      $notif = $this->getNotification();
      if($this->isAjax)$notif = $this->getJS(); //сделал тольео для ajax тк глючило https://prnt.sc/nnmpx8

      if (strpos($output, '</body>') === false) {
        $output .= $notif;
      } else {
        $output = str_replace('</body>', $notif . '</body>', $output);
      }
    }


    if (Yii::$app->response->getStatusCode() == 200) {
      $output = Yii::$app->TwigString->render(
          $output,
          $this->all_params
      );
    }
  }

  public function openModal($url)
  {
    return $this->renderAjax("@frontend/views/openModal.twig", ['url' => $url]);
  }

  public function closeModal($id = '#ajaxCrudModal')
  {
    if (strlen($id) < 5) {
      $id = '#ajaxCrudModal';
    }

    return $this->renderAjax("@frontend/views/closeModal.twig", [
        'modalId' => $id,
    ]);
  }

  public function blankPage()
  {
    return $this->renderAjax("@frontend/views/blankPage.twig");
  }

  public function reloadPage()
  {
    return $this->renderAjax("@frontend/views/reloadPage.twig");
  }

  public function endPage_($ajaxMode = false)
  {
    parent::endPage($ajaxMode);
    parent::clear();
  }

  public function getJS()
  {
    $js_out = [];
    $js_out_pre = [];
    $output = '';
    if (!empty($this->js)) {
      foreach ($this->js as $js_) {
        foreach ($js_ as $js) {
          if (strpos($js, '<script') != 0) {
            $js_out_pre [] = $js;
          } else {
            $js_out [] = $js . ';';
          }
        }
      }
      $js_out_pre = implode('', array_reverse($js_out_pre));
      $js_out = implode('', array_reverse($js_out));
      $output .= $js_out_pre . '<script>jQuery(function ($) {' . $js_out . '});</script>';
    }
    $this->js = [];
    return $output;
  }

  public function getFlash()
  {
    $output = $this->getNotification();
    $output .= $this->getJS();
    return $output;
  }
}