<?php

namespace frontend\modules\visitor\models;

use frontend\modules\franchisee\models\Franchisee;
use frontend\modules\visits\models\VisitorLog;
use Yii;

/**
 * This is the model class for table "visitor".
 *
 * @property int $id
 * @property int $franchisee_id
 * @property string $f_name
 * @property string $l_name
 * @property string $code
 * @property string $email
 * @property string $phone
 * @property int $create
 * @property string $notice
 * @property int $lg
 *
 * @property PollsAns[] $pollsAns
 */
class Visitor extends \common\components\ActiveRecord
{
  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return 'visitor';
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
        [['f_name', 'code', 'create'], 'required'],
        [['f_name', 'l_name', 'code', 'email', 'phone', 'notice', 'lg'], 'string'],
        [['franchisee_id'], 'integer'],
        [['f_name', 'l_name', 'code', 'email', 'phone', 'lg'], 'trim'],
        ['visit_cnt', 'integer'],
        [['email'], 'email'],
      //[[ 'code','email','phone'], 'unique']
        [['code', 'phone'], 'unique']
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
        'id' => Yii::t('app', 'ID'),
        'franchisee_id' => Yii::t('app', 'Franchisee'),
        'f_name' => Yii::t('app', 'F Name'),
        'l_name' => Yii::t('app', 'L Name'),
        'code' => Yii::t('app', 'Code'),
        'email' => Yii::t('app', 'Email'),
        'phone' => Yii::t('app', 'Phone'),
        'create' => Yii::t('app', 'create'),
        'notice' => Yii::t('app', 'Notice'),
        'lg' => Yii::t('app', 'lg'),
        'visit_cnt' => Yii::t('app', 'visit_cnt'),
    ];
  }

  public function beforeValidate()
  {
    $old_attr = $this->oldAttributes;

    if (empty($this->code)) {
      $this->code = isset($old_attr['code']) && strlen($old_attr) > 3 ? $old_attr['code'] : Visitor::newCode();
    }

    if (empty($this->franchisee_id)) {
      $this->franchisee_id = isset($old_attr['franchisee_id']) ? $old_attr['franchisee_id'] : Yii::$app->cafe->franchiseeId;
    }

    if (($this->email == '' || !$this->email) && isset($old_attr['email'])) {
      $this->email = $old_attr['email'];
    }
    if (($this->phone == '' || !$this->phone) && isset($old_attr['phone'])) {
      $this->phone = $old_attr['phone'];
    }

    return parent::beforeValidate(); // TODO: Change the autogenerated stub
  }

  /**
   * @return string Visitors full name
   */
  public function getFullname()
  {
    $fullNameParts = [];

    if (!empty($this->f_name)) {
      $fullNameParts[] = $this->f_name;
    }

    if (!empty($this->l_name)) {
      $fullNameParts[] = $this->l_name;
    }

    return implode(' ', $fullNameParts);
  }

  /**
   * Gives next Fracnhisee CODE value with prefix
   */
  public static function newCode()
  {

    list($codePrefix, $code) = self::getLastCode();
    $code++;

    return $codePrefix . $code;
  }

  public static function getLastCode($codePrefix = false, $franchiseeId = false)
  {
    if (!$codePrefix) {
      if (!$franchiseeId) {
        $franchiseeId = Yii::$app->cafe->getFranchiseeId();
      }
      $franchisee = Franchisee::find()
          ->andWhere(['id' => $franchiseeId])
          ->asArray()
          ->one();

      if (!$franchisee) {
        return time();
        //throw new InvalidConfigException('Franchisee not found');
      }

      $codePrefix = $franchisee['code'];
    }

    $prefixLength = strlen($codePrefix);

    $code = Visitor::find()
        ->select(['code'])
        ->andWhere('SUBSTRING(`code`, 1, :prefixLength) = :codePrefix', [
            ':prefixLength' => $prefixLength,
            ':codePrefix' => $codePrefix
        ])
        ->orderBy([
            'CONVERT(SUBSTRING(`code`, ' . ($prefixLength + 1) . '), UNSIGNED INTEGER) DESC' => '',
        ])
        ->limit(1)
        ->asArray()
        ->scalar();

    $code = (int)preg_replace("/[^0-9]/", '', $code);

    return [$codePrefix, $code];
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getPollsAns()
  {
    return $this->hasMany(PollsAns::className(), ['visitor_id' => 'id']);
  }

  public static function findByString($term, $model = false, $selfMOde = false)
  {
    $term = str_replace('  ', ' ', trim(strip_tags($term)));
    $q = addslashes($term);

    if (!$model) {
      $model = Visitor::find();
    }

    if (is_numeric($q)) {
      $model = $model->orWhere(['visitor.id' => $q]);
    }

    $q = mb_strtolower($q);
    $q = explode(' ', $q);
    if (count($q) == 1) {
      if (!$selfMOde) {
        $model = $model->orWhere(['like', 'LOWER(email)', $q[0] . '%', false]);
        $model = $model->orWhere(['like', 'LOWER(phone)', $q[0]]);
      }
      $model = $model->orWhere(['like', 'LOWER(f_name)', $q[0] . '%', false]);
      $model = $model->orWhere(['like', 'LOWER(l_name)', $q[0] . '%', false]);
      $model = $model->orWhere(['like', 'LOWER(code)', $q[0]]);
    } else if (count($q) == 2) {
      $model = $model->orWhere([
          'and',
          ['like', 'LOWER(l_name)', $q[0] . '%', false],
          ['like', 'LOWER(f_name)', $q[1] . '%', false],
      ]);

      $model = $model->orWhere([
          'and',
          ['like', 'LOWER(l_name)', $q[1] . '%', false],
          ['like', 'LOWER(f_name)', $q[0] . '%', false],
      ]);
    } else {
      return false;
    }

    $model->andWhere(['franchisee_id' => Yii::$app->cafe->franchiseeId]);

    return $model;
  }

  public function getLang()
  {
    $lg_list = Yii::$app->params['lg_list'];
    return isset($lg_list[$this->lg]) ? $lg_list[$this->lg] : $this->lg;
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getFranchisee()
  {
    return $this->hasOne(Franchisee::className(), ['id' => 'franchisee_id']);
  }

  public function getQty($w = [])
  {
    $w['visitor_id'] = $this->id;
    return VisitorLog::find()->andWhere($w)->count();
  }
}
