<?php

namespace frontend\modules\visitor\models;

use app\helpers\GridHelper;
use kartik\daterange\DateRangeBehavior;
use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;

/**
 * VisitorSearch represents the model behind the search form of `frontend\modules\visitor\models\Visitor`.
 */
class VisitorSearch extends Visitor
{
  public $create_from;
  public $create_to;


  public function behaviors()
  {
    return [
        [
            "class" => DateRangeBehavior::className(),
            "attribute" => "create",
            "dateStartAttribute" => "create_from",
            "dateEndAttribute" => "create_to",
            "dateFormat" => false,
            "dateStartFormat" => false,
            "dateEndFormat" => false,
        ],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
        [['id', 'franchisee_id'], 'integer'],
        [['code', 'f_name', 'l_name', 'email', 'phone', 'create', 'notice', 'lg'], 'safe'],
        [['create'], 'match', 'pattern' => '/^.+\s\-\s.+$/'],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function scenarios()
  {
    // bypass scenarios() implementation in the parent class
    return Model::scenarios();
  }

  public function beforeValidate()
  {
    return true; // TODO: Change the autogenerated stub
  }

  /**
   * Creates data provider instance with search query applied
   *
   * @param array $params
   *
   * @return ActiveDataProvider
   */
  public function search($params)
  {
    $query = Visitor::find();

    // add conditions that should always apply here

    $dataProvider = new ActiveDataProvider([
        'query' => $query,
        'sort' => array(
            'defaultOrder' => [
                'id' => SORT_DESC
            ]
        ),
    ]);

    $this->load($params);

    if (!$this->validate()) {
      // uncomment the following line if you do not want to return any records when validation fails
      // $query->where('0=1');
      return $dataProvider;
    }

    if (!Yii::$app->user->can('AllFranchisee')) {
      $this->franchisee_id = Yii::$app->cafe->franchiseeId;
    }

    // grid filtering conditions
    $query->andFilterWhere([
        'id' => $this->id,
        'franchisee_id' => $this->franchisee_id,
    ]);

    $query->andFilterWhere(['like', '.code', $this->code])
        ->andFilterWhere(['like', 'LOWER(f_name)', $this->f_name === null ? null : strtolower($this->f_name)])
        ->andFilterWhere(['like', 'LOWER(l_name)', $this->l_name === null ? null : strtolower($this->l_name)])
        ->andFilterWhere(['like', 'LOWER(email)', $this->email === null ? null : strtolower($this->email)])
        ->andFilterWhere(['like', 'phone', $this->phone])
        ->andFilterWhere(['like', 'LOWER(notice)', $this->notice === null ? null : strtolower($this->notice)])
        ->andFilterWhere(['like', '.lg', $this->lg]);

    if ($this->create) {
      $query->andFilterWhere(['>=', 'create', GridHelper::getDbDateFromDateRangeFormat($this->create_from)])
          ->andFilterWhere(['<=', 'create', GridHelper::getDbDateFromDateRangeFormat($this->create_to, 'P1D')]);
    };
    return $dataProvider;
  }
}
