<?php

namespace frontend\modules\users\models;

use DateTime;
use frontend\modules\cafe\models\Cafe;
use Yii;

/**
 * This is the model class for table "user_log".
 *
 * @property int $id
 * @property int $user_id
 * @property string $start
 * @property string $finish
 * @property int $cafe_id
 *
 * @property Cafe $cafe
 * @property User $user
 */
class UserLog extends \common\components\ActiveRecord
{
  public $start_date;
  public $start_time;
  public $finish_date;
  public $finish_time;
  public $group_datetime = false;

  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return 'user_log';
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
        [['user_id', 'cafe_id'], 'integer'],
        [['start', 'finish'], 'safe'],
        [['start_time', 'finish_time', 'start_date', 'finish_date'], 'safe'],
        [['cafe_id'], 'exist', 'skipOnError' => true, 'targetClass' => Cafe::className(), 'targetAttribute' => ['cafe_id' => 'id']],
        [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['user_id' => 'id']],
        [['start_time', 'start_date'], 'required', 'when' => function ($model) {
          return $model->group_datetime;
        }],
        [['finish_time', 'finish_date'], 'required', 'when' => function ($model) {
          return $model->group_datetime && $model->finish;
        }],

        ['finish_time', 'validateDates'],
    ];
  }

  public function validateDates($attribute, $params, $validator)
  {
    $add_time = DateTime::createFromFormat(Yii::$app->params['lang']['datetime'], $this->start_date . ' ' . $this->start_time);
    $finish_time = DateTime::createFromFormat(Yii::$app->params['lang']['datetime'], $this->finish_date . ' ' . $this->finish_time);

    if (!$add_time || !$finish_time) {
      return;
    }

    if ($add_time > $finish_time) {
      $this->addError('start_date', Yii::t('app', "Start time must be sooner then End time"));
      $this->addError('start_time', Yii::t('app', "Start time must be sooner then End time"));
      $this->addError('finish_date', Yii::t('app', "Start time must be sooner then End time"));
      $this->addError('finish_time', Yii::t('app', "Start time must be sooner then End time"));
    }
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
        'id' => Yii::t('app', 'ID'),
        'user_id' => Yii::t('app', 'User ID'),
        'start' => Yii::t('app', 'Start'),
        'finish' => Yii::t('app', 'Finish'),
        'cafe_id' => Yii::t('app', 'Cafe ID'),
        'duration' => Yii::t('app', 'Duration'),
        'start_time' => Yii::t('app', 'Start time'),
        'finish_time' => Yii::t('app', 'Finish time'),
        'start_date' => Yii::t('app', 'Start date'),
        'finish_date' => Yii::t('app', 'Finish date'),
    ];
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getCafe()
  {
    return $this->hasOne(Cafe::className(), ['id' => 'cafe_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getUser()
  {
    return $this->hasOne(Users::className(), ['id' => 'user_id']);
  }

  public function afterFind()
  {
    parent::afterFind(); // TODO: Change the autogenerated stub

    if (!empty($this->start)) {
      $start = new DateTime($this->start);
      $this->start_date = $start->format(Yii::$app->params['lang']['date']);
      $this->start_time = $start->format(Yii::$app->params['lang']['time']);
    }

    if (!empty($this->finish)) {
      $finish = new DateTime($this->finish);
      $this->finish_date = $finish->format(Yii::$app->params['lang']['date']);
      $this->finish_time = $finish->format(Yii::$app->params['lang']['time']);
    } else {
      $this->finish_date = null;
      $this->finish_time = null;
    }

  }

  public function beforeSave($insert)
  {
    if ($this->isNewRecord && !$this->start) {
      $this->start = date("Y-m-d H:i:s");
    }

    if ($this->group_datetime) {
      $start_time = DateTime::createFromFormat(Yii::$app->params['lang']['datetime'], $this->start_date . ' ' . $this->start_time);
      $this->start = $start_time->format('Y-m-d H:i:s');

      if ($this->finish) {
        $finish_time = DateTime::createFromFormat(Yii::$app->params['lang']['datetime'], $this->finish_date . ' ' . $this->finish_time);

        $this->finish = $finish_time->format('Y-m-d H:i:s');
      }
    }
    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }

  public function getDuration()
  {
    return (!empty($this->finish) ? strtotime($this->finish) : time()) - strtotime($this->start);
  }

  static function getExportData($where = [])
  {
    $visitors = self::find()
        ->select('user_log.id,user_log.start,user_log.finish,user.name')
        ->leftJoin(Users::tableName(), Users::tableName() . '.id = user_id')
        ->andWhere($where)
        ->asArray()
        ->all();
    $out = [];


    foreach ($visitors as $visit) {

      $finishTime = !empty($visit['finish']) ? strtotime($visit['finish']) : time();
      $visit['duration'] = Yii::$app->helper->echo_time($finishTime - strtotime($visit['start']), true);
      $visit['start_time'] = date(Yii::$app->params['lang']['time'], strtotime($visit['start']));
      $visit['start_date'] = date(Yii::$app->params['lang']['date'], strtotime($visit['start']));
      /*if (!empty($visit['guest_m']) || !empty($visit['guest_chi'])) {
        $visit->type = VisitorLog::TYPE_GROUP;
      }

      $visitor['id'] = $visit['id'];
      $visitor['start_time'] = date(Yii::$app->params['lang']['time'], strtotime($visit['add_time']));
      $visitor['user'] = $visit->user->name;
      $visitor['type'] = $visit->type;
      $visitor['pause_start'] = $visit->pause_start;
      $visitor['visit_cnt'] = $visit->visit_cnt;
      $visitor['type_str'] = VisitorLog::typeList($visit->type);
      $visitor['color'] = VisitorLog::$colors[$visit->type];
      $visitor['icon'] = $icons[$visit->type];
      $visitor['persons_summary'] = 1 + $visit['guest_m'] + $visit['guest_chi']; // People summary in this Visit*/

      $out[] = $visit;
    }
    return $out;
  }

  static function getUserInCafe($cafe_id = false)
  {
    if (!$cafe_id) {
      $cafe_id = Yii::$app->cafe->id;
    };

    return self::getExportData(['cafe_id' => $cafe_id, 'finish' => null]);
  }

  public static function sessionStart($cafe_id = null, $user_id = null)
  {
    if ($user_id === null) {
      $user_id = Yii::$app->user->id;
    }

    if ($cafe_id === null) {
      $cafe_id = Yii::$app->cafe->id;
    }

    $session = self::find()
        ->andWhere([
            'user_id' => $user_id,
            'cafe_id' => $cafe_id,
            'finish' => null,
        ])
        ->one();

    if (!$session) {
      $session = new self();
      $session->user_id = $user_id;
      $session->cafe_id = $cafe_id;

      return $session->save();
    }

    return true;
  }
}
