<?php

namespace frontend\modules\mails\controllers;

use common\components\widget\BulkButtonWidget;
use frontend\components\Controller;
use frontend\modules\mails\models\MailsLog;
use frontend\modules\mails\models\StartForm;
use frontend\modules\mails\models\TemplateMail;
use frontend\modules\mails\models\TemplateMailSearch;
use frontend\modules\mails\models\TestForm;
use Yii;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * AdminController implements the CRUD actions for TemplateMail model.
 */
class AdminController extends Controller
{


  private $def_sel_column = [
      'id',
      'content',
      'title',
      'status',
      'cafe_id',
      'updated_at',
      'created_at',
  ];

  /**
   * @inheritdoc
   */
  public function behaviors()
  {
    return [
        'verbs' => [
            'class' => VerbFilter::className(),
            'actions' => [
                'delete' => ['post'],
                'bulk-delete' => ['post'],
            ],
        ],];
  }

  public function beforeAction($action)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->cafe->can('mails')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    return parent::beforeAction($action); // TODO: Change the autogenerated stub
  }

  /**
   * Lists all TemplateMail models.
   * @return mixed
   */
  public function actionIndex()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateMailView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $searchModel = new TemplateMailSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    $canCreate = Yii::$app->user->can('TemplateMailCreate');
    $actions = "";
    $actions .= Yii::$app->user->can('TemplateMailUpdate') ? "{update}" : "";
    $actions .= Yii::$app->user->can('TemplateMailDelete') ? "{delete}" : "";
    $panelButtons = '';
    if (Yii::$app->user->can('TemplateMailDelete')) {
      $panelButtons = BulkButtonWidget::widget();
    };
    $columns = include(__DIR__ . '/../views/admin/_columns.php');
    if (Yii::$app->user->isGuest) {
      $sel_column = Yii::$app->session->get("columns_TemplateMail", false);
    } else {
      $user = Yii::$app->getUser()->getIdentity();
      $sel_column = $user->getActiveColumn("columns_TemplateMail");
    }
    if (!$sel_column) {
      $sel_column = $this->def_sel_column;
    }
    foreach ($columns as $k => $column) {
      $column_name = !is_array($column) ? $column : (isset($column['attribute']) ? $column['attribute'] : false);
      if ($column_name && !in_array($column_name, $sel_column)) {
        unset($columns[$k]);
      }
    }

    return $this->render('index', [
        'searchModel' => $searchModel,
        'dataProvider' => $dataProvider,
        'columns' => $columns,
        'canCreate' => $canCreate,
        'panelButtons' => $panelButtons,
        'title' => Yii::t('app', 'TemplateMail list'),
    ]);
  }


  /**
   * Config column in TemplateMail model.
   * @param integer $id
   * @return mixed
   * @throws NotFoundHttpException if the model cannot be found
   */
  public function actionColumns()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateMailView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    $model = new TemplateMail();
    $searchModel = new TemplateMailSearch();

    $request = Yii::$app->request;

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    Yii::$app->response->format = Response::FORMAT_JSON;

    if ($request->post('column')) {
      $col = $request->post('column');

      if (Yii::$app->user->isGuest) {
        Yii::$app->session->set("columns_TemplateMail", $col);
      } else {
        $user = Yii::$app->getUser()->getIdentity();
        $user->setActiveColumn("columns_TemplateMail", $col);
      }

      return [
          'forceReload' => '#crud-datatable-pjax',
          'content' => Yii::$app->view->closeModal(),
          'forceClose' => 'true',
      ];
    }
    $actions = "";
    $columns = include(__DIR__ . '/../views/admin/_columns.php');
    if (Yii::$app->user->isGuest) {
      $sel_column = Yii::$app->session->get("columns_TemplateMail", false);
    } else {
      $user = Yii::$app->getUser()->getIdentity();
      $sel_column = $user->getActiveColumn("columns_TemplateMail");
    }
    if (!$sel_column) {
      $sel_column = $this->def_sel_column;
    }
    foreach ($columns as $k => $column) {
      $column_name = !is_array($column) ? $column : (isset($column['attribute']) ? $column['attribute'] : false);
      if (!$column_name) {
        unset($columns[$k]);
      } else {
        $columns[$k] = $column_name;
      }
    }

    return [
        'title' => Yii::t('app', 'Change visible columns in TemplateMail table'),
        'content' => $this->renderAjax('columns', [
            'sel_column' => $sel_column,
            'columns' => $columns,
            'model' => $model,
            'isAjax' => true
        ]),
        'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
            Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"])

    ];
  }

  /**
   * Creates a new TemplateMail model.
   * For ajax request will return json object
   * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
   * @return mixed
   */
  public function actionCreate()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateMailCreate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    $request = Yii::$app->request;
    $model = new TemplateMail();

    if ($request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }


    $model->width = 700;
    if ($model->load($request->post()) && $model->save()) {
      Yii::$app->session->addFlash('success', Yii::t('app', 'Email template is saved'));
      return $this->redirect(['update', 'id' => $model->id]);
    }


    return $this->render('create', [
        'model' => $model,
		'title' => Yii::t('app', "Create new Template"),
		'back_url' => "/mails/admin",
        'used_in_cafe' => $model->getCafe(Yii::$app->cafe->getId())->exists(),
        'isAjax' => true
    ]);
  }

  /**
   * Updates an existing TemplateMail model.
   * For ajax request will return json object
   * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
   * @param integer $id
   * @return mixed
   */
  public function actionUpdate($id)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateMailUpdate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $request = Yii::$app->request;
    $model = $this->findModel($id);

    if (!$model) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    if ($model->load($request->post()) && $model->save()) {
      Yii::$app->session->addFlash('success', Yii::t('app', 'Email template is saved'));
    };

    return $this->render('update', [
	    'title' => Yii::t('app', "Update Template"),
        'model' => $model,
		'back_url' => "/mails/admin",
		'used_in_cafe' => $model->getCafe(Yii::$app->cafe->getId())->exists()
		
    ]);
  }
  /**
   * Delete an existing TemplateMail model.
   * For ajax request will return json object
   * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   */
  public function actionDelete($id)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateMailDelete')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    $request = Yii::$app->request;
    $this->findModel($id)->delete();

    if ($request->isAjax) {
      /*
      *   Process for ajax request
      */
      Yii::$app->response->format = Response::FORMAT_JSON;
      return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
    } else {
      /*
      *   Process for non-ajax request
      */
      return $this->redirect(['index']);
    }
  }

  /**
   * Delete multiple existing TemplateMail model.
   * For ajax request will return json object
   * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   */
  public function actionBulkDelete()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateMailDelete')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    $request = Yii::$app->request;
    $pks = explode(',', $request->post('pks')); // Array or selected records primary keys
    foreach ($pks as $pk) {
      $model = $this->findModel($pk);
      $model->delete();
    }

    if ($request->isAjax) {
      /*
      *   Process for ajax request
      */
      Yii::$app->response->format = Response::FORMAT_JSON;
      return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
    } else {
      /*
      *   Process for non-ajax request
      */
      return $this->redirect(['index']);
    }

  }

  /**
   * Finds the TemplateMail model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return TemplateMail the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id)
  {
    if (($model = TemplateMail::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException(Yii::t('app', 'Page does not exist'));
    }
  }

  public function actionView($id)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateUpdate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    $model = $this->findModel($id);
    return $model->getTemplate();
  }

  public function actionSendOnEmail($id, $db = 0)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateMailView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    $request = Yii::$app->request;

    $template = $this->findModel($id);

    if ($db == 1) {
      if ($request->post() && $request->post('data')) {
        Yii::$app->session->set('tpl_' . $id, $request->post('data'));
        return 'ok';
      }
      $data = Yii::$app->session->get('tpl_' . $id);
      if ($data) {
        $template->content = $data;
      }
    }

    $model = new TestForm($template);

    /*
    *   Process for ajax request
    */
    Yii::$app->response->format = Response::FORMAT_JSON;
    $title = Yii::t('app', "Template test");
    if ($request->isGet) {
      return [
          'title' => $title,
          'content' => $this->renderAjax('@frontend/modules/templates/views/admin/test.php', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Test'), ['class' => 'btn btn-primary', 'type' => "submit"]),
      ];
    } else if ($model->load($request->post()) && $model->process()) {
      return [
          'title' => $title,
          'content' => $model->getContent(),
      ];
    } else {
      return [
          'title' => $title,
          'content' => $this->renderAjax('@frontend/modules/templates/views/admin/test.php', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Test'), ['class' => 'btn btn-primary', 'type' => "submit"]),

      ];
    }
  }

  public function actionStart($id, $type)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateMailView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }
    $request = Yii::$app->request;

    if (!$request->isPost || !$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    Yii::$app->response->format = Response::FORMAT_JSON;

    $template = $this->findModel($id);

    $button = Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]);
    $title = Yii::t('app', 'Sending mails');

    if (!$template) {
      return [
          'title' => $title,
          'content' => Yii::t('app', 'Mail template not found'),
          'footer' => $button
      ];
    }

    $mails = new MailsLog();
    $mails->user_id = Yii::$app->user->id;
    $mails->cafe_id = Yii::$app->cafe->id;
    $mails->cteated_at = date('Y-m-d H:i:s');
    $mails->setTemplate($template);
    $mails->params = json_encode([
        $type => $request->post('pks')
    ]);
    $mails->save();

    return [
        'title' => $title,
        'content' => Yii::t('app', 'Job newsletter created.'),
        'footer' => $button
    ];
  }

  public function actionStartNewsletter($id, $db = 0)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateMailView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    $request = Yii::$app->request;

    $template = $this->findModel($id);

    if ($db == 1) {
      if ($request->post() && $request->post('data')) {
        Yii::$app->session->set('tpl_' . $id, $request->post('data'));
        return 'ok';
      }
      $data = Yii::$app->session->get('tpl_' . $id);
      if ($data) {
        $template->content = $data;
      }
    }

    $model = new StartForm($template);

    /*
    *   Process for ajax request
    */
    Yii::$app->response->format = Response::FORMAT_JSON;
    $title = Yii::t('app', "Start newsletter");
    if ($request->isGet) {
      return [
          'title' => $title,
          'content' => $this->renderAjax('@frontend/modules/templates/views/admin/test.php', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Start newsletter'), ['class' => 'btn btn-primary', 'type' => "submit"]),
      ];
    }

    if ($model->load($request->post()) && $model->validate()) {
      $mails = new MailsLog();
      $mails->user_id = Yii::$app->user->id;
      $mails->cafe_id = Yii::$app->cafe->id;
      $mails->cteated_at = date('Y-m-d H:i:s');
      $mails->setTemplate($template);
      $mails->params = json_encode($model->filterarams());
      $mails->save();

      return [
          'title' => $title,
          'content' => Yii::t('app', 'Newsletter is started'),
      ];
    } else {
      return [
          'title' => $title,
          'content' => $this->renderAjax('@frontend/modules/templates/views/admin/test.php', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Test'), ['class' => 'btn btn-primary', 'type' => "submit"]),

      ];
    }
  }
}
