<?php

namespace frontend\modules\polls\controllers;

use common\components\widget\BulkButtonWidget;
use frontend\components\Controller;
use frontend\modules\franchisee\models\FranchiseeTariffs;
use frontend\modules\polls\models\Polls;
use frontend\modules\polls\models\PollsAns;
use frontend\modules\polls\models\PollsSearch;
use Yii;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\helpers\Json;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * AdminController implements the CRUD actions for Polls model.
 */
class AdminController extends Controller
{

  private $def_sel_column = [
      'id',
      'question',
      'answers',
      'status',
      'user_id',
      'created',
      'other_ans',
      'user_status',
      'event',
      'cafe_id',
      'is_poll',
  ];

  /**
   * @inheritdoc
   */
  public function behaviors()
  {
    return [
        'verbs' => [
            'class' => VerbFilter::className(),
            'actions' => [
                'delete' => ['post'],
                'bulk-delete' => ['post'],
            ],
        ],];
  }

  public function beforeAction($action)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->cafe->can('Polls')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    return parent::beforeAction($action); // TODO: Change the autogenerated stub
  }

  private function getChart($data)
  {
    return [
        'title' => ['text' => '',],
		'colors' => ['#3498DB', '#7bad18', '#ff2e12', '#FBBB0F', '#006ac1', '#87794e', '#647687', '#76608a', '#dc4fad', '#c1004f', '#7200ac'],
		'credits' => ['enabled' => false],
      //'legend' => ['enabled' => false],
      //'credits' => ['enabled' => false],
        'chart' => [
		    'styledMode' => true,
            'type' => 'pie',
            'height' => '500',
			//'width' =>'200',
            'plotBackgroundColor' => null,
            'plotBorderWidth' => null,
            'plotShadow' => false,
            'style' => [
                'fontFamily' => 'Open Sans',
            ],
        ],
        'tooltip' => [
         //'backgroundColor ' => '#FFFFFF',
		 'borderColor' => '#474747',
		 'borderRadius' => 0,
		//'shared' => true,
        //'useHTML' => true,
       // 'headerFormat' =>  '<table style="font-size: 14px">{name}',
        'pointFormat' => '<span style="font-size: 14px">{series.name}: <b>{point.percentage:.1f}%</b></span>',
       // 'footerFormat' => '</table>',
        //'valueDecimals'=> 2,
        // 'pointFormat' => '{series.name}: <b>{point.percentage:.1f}%</b>'
        ],
        'plotOptions' => [
            'pie' => [
                'allowPointSelect' => true,
                'cursor' => 'pointer',
                'dataLabels' => [
                    'enabled' => false,
                ],
                'showInLegend' => true
            ]
			
        ],
		'legend' => [
		 'borderRadius' => 0,
		 'itemStyle' => [
            'color' => '#474747',
            'fontWeight' => 'normal',
			 'fontSize' =>  '14px',
			  'borderRadius' => 0,
        ],
		 'labelFormat'=> '{name} <b> / {percentage:.1f}%</b>',
            'align' => 'left',
           // 'verticalAlign' => 'middle',
			//'layout' => 'vertical',
            'x' => 0,
            'y' => 0,
        ],
        'series' => [[
          //'type' => 'category',
            'name' => Yii::t('app', 'Percentage share'),
            'data' => $data,
        ]]
    ];
  }

  public function addCharsetJS($id, $params)
  {
    $this->view->registerJs('new Highcharts.chart("' . $id . '",' . Json::encode($params) . ');');
  }

  /**
   * Lists all Polls models.
   * @return mixed
   */
  public function actionIndex()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('PollsView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $searchModel = new PollsSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    $canCreate = Yii::$app->user->can('PollsCreate');
    $actions = "";
    $actions .= Yii::$app->user->can('PollsUpdate') ? "{update}" : "";
    $actions .= Yii::$app->user->can('PollsDelete') ? "{delete}" : "";
    $actions .= "{view}";
    $actions .= "{result}";
    $panelButtons = '';
    if (Yii::$app->user->can('PollsDelete')) {
      $panelButtons = BulkButtonWidget::widget();
    };
    $columns = include(__DIR__ . '/../views/admin/_columns.php');
    if (Yii::$app->user->isGuest) {
      $sel_column = Yii::$app->session->get("columns_Polls", false);
    } else {
      $user = Yii::$app->getUser()->getIdentity();
      $sel_column = $user->getActiveColumn("columns_Polls");
    }
    if (!$sel_column) {
      $sel_column = $this->def_sel_column;
    }
    foreach ($columns as $k => $column) {
      $column_name = !is_array($column) ? $column : (isset($column['attribute']) ? $column['attribute'] : false);
      if ($column_name && !in_array($column_name, $sel_column)) {
        unset($columns[$k]);
      }
    }

    return $this->render('index', [
        'searchModel' => $searchModel,
        'dataProvider' => $dataProvider,
        'columns' => $columns,
        'canCreate' => $canCreate,
        'panelButtons' => $panelButtons,
        'title' => Yii::t('app', 'Polls list'),
    ]);
  }

  public function actionView($id)
  {
    $request = Yii::$app->request;

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $poll = Polls::find()->where(['id' => $id, 'cafe_id' => Yii::$app->cafe->id])->one();
    if (!$poll) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Poll not fount'));
      return false;
    }

    Yii::$app->response->format = Response::FORMAT_JSON;
    $model = new PollsAns();
    $model->poll_id = $id;
    $model->visitor_id = null;

    if ($request->isPost && $model->load($request->post()) && $model->validate()) {
      return [
          'title' => Yii::t('app', 'Test poll.'),
          'content' => Yii::t('app', 'Test poll passed. The answer is stored only for real visitors.'),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"])
      ];
    }

    return [
        'title' => Yii::t('app', 'Please pass our poll. Thanks.'),
        'content' => $this->renderAjax('../default/view', [
            'model' => $model
        ]),
        'footer' => Html::button(Yii::t('app', 'CONFIRM'), ['class' => 'btn btn-primary', 'type' => "submit"])
    ];
  }

  public function actionResult($id)
  {
    $request = Yii::$app->request;

    if (!$request->isAjax && !YII_DEBUG) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    Yii::$app->response->format = Response::FORMAT_JSON;

    $poll = Polls::find()->where(['id' => $id, 'cafe_id' => Yii::$app->cafe->id])->one();
    if (!$poll) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Poll not fount'));
      return false;
    }

    $cnt = PollsAns::find()
        ->where(['poll_id' => $id])
        ->count();

    if ($cnt == 0) {
      return [
          'title' => Yii::t('app', 'Poll result #{id}.', [
              'id' => $poll->id
          ]),
          'content' => Yii::t('app', 'no voting results'),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"])
      ];
    }

    $ans = new PollsAns();
    $ans->poll_id = $id;
    $ans = $ans->getAllowANS(true);

    if (count($ans) > 1) {
      $data = PollsAns::find()
          ->where(['poll_id' => $id])
          ->select(['ans,count(ans) as cnt'])
          ->groupBy('ans')
          ->asArray()
          ->all();

      $char = [];
      foreach ($data as $item) {
        if (empty($ans[$item['ans']])) {
          continue;
          //$ans[$item['ans']] = 0;
        }
        $char[] = [
            'name' => '<span style="font-size: 14px">'.$ans[$item['ans']] . ' : <b>' . $item['cnt'] . '</b> '.Yii::t('main', 'person(s)').'</span>',
            'y' => $item['cnt'] * 1,
            'id' => $item['ans'],
        ];
      }
      $this->addCharsetJS('charts-result', $this->getChart($char));

    }

    $other_ans = [];
    if ($poll->other_ans = Polls::OTHER_ANS_SHOW) {
      $other_ans = PollsAns::find()
          ->where(['poll_id' => $id, 'ans' => -1])
          ->leftJoin('visitor', 'visitor.id=polls_ans.visitor_id')
          ->select(['txt', 'f_name', 'l_name', 'code'])
          ->asArray()
          ->all();
    }


    return [
        'title' => Yii::t('app', 'Poll result #{id}.', [
            'id' => $poll->id
        ]),
        'content' => $this->renderAjax('result', [
            'model' => $poll,
            'other_ans' => $other_ans
        ]),
        'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"])
    ];
  }

  /**
   * Config column in Polls model.
   * @param integer $id
   * @return mixed
   * @throws NotFoundHttpException if the model cannot be found
   */
  public function actionColumns()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('PollsView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    $model = new Polls();
    $searchModel = new PollsSearch();

    $request = Yii::$app->request;

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    Yii::$app->response->format = Response::FORMAT_JSON;

    if ($request->post('column')) {
      $col = $request->post('column');

      if (Yii::$app->user->isGuest) {
        Yii::$app->session->set("columns_Polls", $col);
      } else {
        $user = Yii::$app->getUser()->getIdentity();
        $user->setActiveColumn("columns_Polls", $col);
      }

      return [
          'forceClose' => 'true',
          'forceReload' => '#crud-datatable-pjax',
          'content' => Yii::$app->view->closeModal(),
      ];
    }
    $actions = "";
    $columns = include(__DIR__ . '/../views/admin/_columns.php');
    if (Yii::$app->user->isGuest) {
      $sel_column = Yii::$app->session->get("columns_Polls", false);
    } else {
      $user = Yii::$app->getUser()->getIdentity();
      $sel_column = $user->getActiveColumn("columns_Polls");
    }
    if (!$sel_column) {
      $sel_column = $this->def_sel_column;
    }
    foreach ($columns as $k => $column) {
      $column_name = !is_array($column) ? $column : (isset($column['attribute']) ? $column['attribute'] : false);
      if (!$column_name) {
        unset($columns[$k]);
      } else {
        $columns[$k] = $column_name;
      }
    }

    return [
        'title' => Yii::t('app', 'Change visible columns in Polls table'),
        'content' => $this->renderAjax('columns', [
            'sel_column' => $sel_column,
            'columns' => $columns,
            'model' => $model,
            'isAjax' => true
        ]),
        'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
            Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"])

    ];
  }

  /**
   * Creates a new Polls model.
   * For ajax request will return json object
   * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
   * @return mixed
   */
  public function actionCreate()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('PollsCreate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    $request = Yii::$app->request;
    $model = new Polls();

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $model->cafe_id = Yii::$app->cafe->id;
    /*
    *   Process for ajax request
    */
    Yii::$app->response->format = Response::FORMAT_JSON;
    if ($request->isGet) {
      return [
          'title' => Yii::t('app', 'Create new Polls'),
          'content' => $this->renderAjax('create', [
              'model' => $model,
              'isAjax' => true
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"])
      ];
    } else if ($model->load($request->post()) && $model->save()) {
      return $this->returnBlank(
          [
              'forceReload' => '#crud-datatable-pjax',
              'title' => Yii::t('app', 'Create new Polls'),
          ],
          Yii::t('app', 'Create Polls success')
      );
    } else {
      var_dump($model->errors);
      return [
          'title' => Yii::t('app', 'Create new Polls'),
          'content' => $this->renderAjax('create', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"])

      ];
    }
  }

  /**
   * Updates an existing Polls model.
   * For ajax request will return json object
   * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
   * @param integer $id
   * @return mixed
   */
  public function actionUpdate($id)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('PollsUpdate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $request = Yii::$app->request;
    $model = $this->findModel($id);

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    /*
    *   Process for ajax request
    */
    $title = Yii::t('app', 'Update Polls: {nameAttribute}', [
        'nameAttribute' => '' . $model->id,
    ]);
    Yii::$app->response->format = Response::FORMAT_JSON;
    if ($request->isGet) {
      return [
          'title' => $title,
          'content' => $this->renderAjax('update', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"])
      ];
    } else if ($model->load($request->post()) && $model->save()) {
      return $this->returnBlank(
          [
              'forceReload' => '#crud-datatable-pjax',
              'title' => $title,
          ],
          Yii::t('app', 'Poll updated successfully')
      );
    } else {
      return [
          'title' => $title,
          'content' => $this->renderAjax('update', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"])
      ];
    }
  }

  /**
   * Delete an existing Polls model.
   * For ajax request will return json object
   * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   */
  public function actionDelete($id)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('PollsDelete')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    $request = Yii::$app->request;
    $this->findModel($id)->delete();

    if ($request->isAjax) {
      /*
      *   Process for ajax request
      */
      Yii::$app->response->format = Response::FORMAT_JSON;
      return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
    } else {
      /*
      *   Process for non-ajax request
      */
      return $this->redirect(['index']);
    }
  }

  /**
   * Delete multiple existing Polls model.
   * For ajax request will return json object
   * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   */
  public function actionBulkDelete()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('PollsDelete')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    $request = Yii::$app->request;
    $pks = explode(',', $request->post('pks')); // Array or selected records primary keys
    foreach ($pks as $pk) {
      $model = $this->findModel($pk);
      $model->delete();
    }

    if ($request->isAjax) {
      /*
      *   Process for ajax request
      */
      Yii::$app->response->format = Response::FORMAT_JSON;
      return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
    } else {
      /*
      *   Process for non-ajax request
      */
      return $this->redirect(['index']);
    }

  }

  /**
   * Finds the Polls model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return Polls the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id)
  {
    if (($model = Polls::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException(Yii::t('app', 'Page does not exist'));
    }
  }
}
