<?php

namespace frontend\modules\polls\controllers;

use frontend\components\Controller;
use frontend\modules\polls\models\Polls;
use frontend\modules\polls\models\PollsAns;
use frontend\modules\visitor\models\Visitor;
use frontend\modules\visits\models\VisitorLog;
use Yii;
use yii\bootstrap\Html;
use yii\web\Response;

/**
 * Default controller for the `polls` module
 */
class DefaultController extends Controller
{


  public function beforeAction($action)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->cafe->can('Polls')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    return parent::beforeAction($action); // TODO: Change the autogenerated stub
  }

  /**
   * Renders the index view for the module
   * @return string
   */

  public function actionMake($visitor_id, $mode)
  {
    $request = Yii::$app->request;

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    Yii::$app->response->format = Response::FORMAT_JSON;

    if ($visitor_id == 0) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'poll not found'));
      return false;
    }
    $visitor = Visitor::find()->where(['id' => $visitor_id])->one();
    if (!$visitor) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'poll not found'));
      return false;
    }

    $model = new PollsAns();
    $model->visitor_id = $visitor_id;

    if ($request->isPost && $model->load($request->post())) {
      if ($model->save()) {

        Yii::$app->session->addFlash('success', Yii::t('app', 'Your answer was successfully recorded. Thank.'));
        Yii::$app->session->addFlash('polls', ['visitor_id' => $visitor_id, 'mode' => $mode]);

        $next_poll = $poll = self::findPollForUser($mode, $visitor_id);

        return [
            'title' => Yii::t('app', 'Please pass our poll. Thanks.'),
            'content' => $next_poll ? Yii::$app->view->blankPage() : Yii::$app->view->closeModal('#secondModal')
        ];
      }
    } else {
      $poll = self::findPollForUser($mode, $visitor_id);

      if (!$poll) {
        throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'poll not found'));
        return false;
      }
      $model->poll_id = $poll->id;
    }

    $btn = Html::button(Yii::t('app', 'CONFIRM'), ['class' => 'btn btn-primary', 'type' => "submit"]);
    return [
        'title' => Yii::t('app', 'Please pass our poll. Thanks.'),
        'content' => $this->renderAjax('view', [
            'model' => $model,
            'btn' => $btn
        ]),
        //'footer' => $btn
    ];
  }

  private function findPollForUser($mode, $visitor_id)
  {
    $visits_count = VisitorLog::find()->where(['visitor_id' => $visitor_id])->count();
    return Polls::find()
        ->andWhere([
            'user_status' => [
                Polls::USER_STATUS_ALL,
                $visits_count == 1 ? Polls::USER_STATUS_NEW : Polls::USER_STATUS_REGULAR,
            ],
            'status' => Polls::STATUS_ACTIVE,
            'event' => $mode,
            'cafe_id' => Yii::$app->cafe->id,
            'visitor_id' => null,
        ])
        ->leftJoin(PollsAns::tableName(), 'polls.id=poll_id and visitor_id=' . $visitor_id)
        ->one();
  }
}
