<?php

namespace frontend\modules\tasks\controllers;

use frontend\components\Controller;
use frontend\modules\tasks\models\DoTask;
use frontend\modules\tasks\models\Task;
use Yii;
use yii\helpers\Html;
use yii\web\Response;

/**
 * Default controller for the `visits` module
 */
class DefaultController extends Controller
{
  public function beforeAction($action)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->cafe->can('task')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    return parent::beforeAction($action); // TODO: Change the autogenerated stub
  }

  public function actionViews()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TaskMain')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $request = Yii::$app->request;
    if (!$request->isAjax || !$request->isGet) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $model = Task::findToDate(false, false, true)
        ->andWhere(['active' => Task::ACTIVE])
        ->all();
    //ddd($model);

    $content = $this->renderAjax('list', [
        'model' => $model,
        'isAjax' => true
    ]);
    //return $content;
    //ddd($model);

    Yii::$app->response->format = Response::FORMAT_JSON;
    return [
        'title' => Yii::t('app', 'Task List'),
        'content' => $content,
        'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-right', 'data-dismiss' => "modal"])
    ];
  }

  public function actionFinish($id, $failed = 0)
  {

    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TaskMain')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $request = Yii::$app->request;
    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    Yii::$app->response->format = Response::FORMAT_JSON;
    $title = Yii::t('app', 'Finish task');

    $model = Task::findToDate(false, false, true)
        ->andWhere(['task.id' => $id])
        ->andWhere(['active' => Task::ACTIVE])
        //->andWhere(['not in','status',[DoTask::STATUS_FAILED,DoTask::STATUS_COMPLITED]])
        ->one();

    if (!$model || in_array($model['status'], [DoTask::STATUS_FAILED, DoTask::STATUS_COMPLITED])) {
      return [
          'title' => $title,
          'content' => Yii::t('app', 'Task not find'),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"])
      ];
    }

    $do = DoTask::find()
        ->where('DATE(`datetime`)=\'' . date('Y-m-d') . '\' AND task_id=' . $id)
        ->one();

    if (!$do) {
      $do = new DoTask();
    }

    if(empty($do->text)) {
      $do->text = $model['text'];
    }

    $do->cafe_id = Yii::$app->cafe->id;
    $do->task_id = $model['id'];
    $do->user_id = Yii::$app->user->id;
    if (empty($do->datetime)) $do->datetime = date('Y-m-d H:i:s');
    $do->closedate = date('Y-m-d H:i:s');

    if ($failed == 0) {
      $do->status = DoTask::STATUS_COMPLITED;
      $do->save();
      Yii::$app->session->addFlash('success', Yii::t('app', 'Task completed successfully'));
      return [
          'forceClose' => 'true',
          'content' => Yii::$app->view->closeModal(),
      ];
    }

    $do->status = DoTask::STATUS_FAILED;

    if ($request->isPost && $do->load($request->post()) && $do->validate() && $do->save()) {
      Yii::$app->session->addFlash('success', Yii::t('app', 'Task finish with failed status'));
      return [
          'forceClose' => 'true',
          'content' => Yii::$app->view->closeModal(),
      ];
    }

    $content = $this->renderAjax('failed', [
        'model' => $do,
    ]);

    $title = Yii::t('app', 'Finish task (but not performed)');
    return [
        'title' => $title,
        'content' => $content,
        'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
            Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"])
    ];

  }
}