<?php
/**
 * Created by PhpStorm.
 * User: acid
 * Date: 13.09.18
 * Time: 16:46
 */

namespace common\components\widget;

use Yii;
use yii\helpers\Html;

class BulkButtonWidget extends \yii\base\Widget
{
	public $buttons = [];

	public $layout = "{delete}";
	public $urlPrefix = "";

	public function init()
	{
		$this->buttons['{delete}'] = Html::a('<i class="glyphicon glyphicon-trash"></i> '.Yii::t("app", "Delete All").'',
			[$this->urlPrefix."bulk-delete"],
			[
				"class"                => "btn btn-danger testChechedRow",
				'title'                => Yii::t("app", "Delete All"),
				'role'                 => 'modal-remote-bulk',
				'data-confirm'         => false, 'data-method' => false,// for overide yii data api
				'data-request-method'  => 'post',
				'data-confirm-title'   => Yii::t("app", "Are you sure?"),
				'data-confirm-message' => Yii::t("app", "Are you sure want to delete this item"),
			]);

		$this->buttons['{block}'] = Html::a('<i class="fa fa-stop"></i> '.Yii::t('app', 'Blocked All').'',
			[$this->urlPrefix."bulk-blocked"],
			[
				"class"                => "btn btn-warning testChechedRow",
				'title'                => Yii::t('app', 'Blocked All'),
				'role'                 => 'modal-remote-bulk',
				'data-confirm'         => false, 'data-method' => false,// for overide yii data api
				'data-request-method'  => 'post',
				'data-confirm-title'   => Yii::t('app', 'Are you sure?'),
				'data-confirm-message' => Yii::t('app', 'Are you sure want to Blocked this users'),
			]);

		$this->buttons['{restore}'] = Html::a('<i class="fa fa-play"></i> '.Yii::t('app', 'Restore All').'',
			[$this->urlPrefix."bulk-restore"],
			[
				"class"                => "btn btn btn-info testChechedRow",
				'title'                => Yii::t('app', 'Restore All'),
				'role'                 => 'modal-remote-bulk',
				'data-confirm'         => false, 'data-method' => false,// for overide yii data api
				'data-request-method'  => 'post',
				'data-confirm-title'   => Yii::t('app', 'Are you sure?'),
				'data-confirm-message' => Yii::t('app', 'Are you sure want to restore this users'),
			]);

		parent::init(); // TODO: Change the autogenerated stub
	}

	public function run()
	{
		$output = strtr($this->layout, $this->buttons);

		return $output;
	}
}
