<?php

namespace frontend\modules\shop\models;

use frontend\modules\cafe\models\Cafe;
use frontend\modules\franchisee\models\Franchisee;
use frontend\modules\shop\models\query\ShopProductQuery;
use Yii;

/**
 * This is the model class for table "{{%shop_product}}".
 *
 * @property int $id
 * @property int $franchisee_id
 * @property int $cafe_id
 * @property int $supplier_id
 * @property int $category_id
 * @property string $title
 * @property string $description
 * @property string $image
 * @property string $barcode
 * @property int $external_sale_available
 * @property int $accounting_critical_minimum
 * @property int $tax_required
 * @property int $weight
 * @property double $price
 * @property int $is_active
 * @property int $created_by
 * @property int $updated_by
 * @property int $updated_at
 * @property int $created_at
 */
class ShopProduct extends ShopBaseModel
{
  public $old_quantity;
  public $new_quantity;

  static $default_image = "/img/img_blank.png";

  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return '{{%shop_product}}';
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
        [['franchisee_id', 'title'], 'required'],
        [['franchisee_id', 'cafe_id', 'supplier_id', 'category_id', 'external_sale_available', 'accounting_critical_minimum', 'tax_required', 'weight', 'is_active', 'created_by', 'updated_by', 'new_quantity', 'old_quantity'], 'integer'],
        ['new_quantity', 'number', 'min' => 0],
        ['in_stock', 'number'],
        [['description'], 'string'],
        [['price'], 'number'],
        [['title', 'barcode'], 'string', 'max' => 255],
        [['updated_at', 'created_at'], 'safe'],

        ['image', 'string'],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
        'id' => Yii::t('app', 'ID'),
        'franchisee_id' => Yii::t('app', 'Franchisee'),
        'cafe_id' => Yii::t('app', 'Cafe'),
        'supplier_id' => Yii::t('app', 'Supplier'),
        'category_id' => Yii::t('app', 'Category'),
        'title' => Yii::t('app', 'Product Title'),
        'description' => Yii::t('app', 'Product Description'),
        'image' => Yii::t('app', 'Image'),
        'barcode' => Yii::t('app', 'Barcode'),
        'external_sale_available' => Yii::t('app', 'In shop'),
        'accounting_critical_minimum' => Yii::t('app', 'Accounting Critical Minimum'),
        'tax_required' => Yii::t('app', 'Tax'),
        'weight' => Yii::t('app', 'Weight'),
        'price' => Yii::t('app', 'Price'),
        'is_active' => Yii::t('app', 'Active'),
        'created_by' => Yii::t('app', 'Created By'),
        'updated_by' => Yii::t('app', 'Updated By'),
        'updated_at' => Yii::t('app', 'Updated At'),
        'created_at' => Yii::t('app', 'Created At'),
        'old_quantity' => Yii::t('app', 'Quantity'),
        'new_quantity' => Yii::t('app', 'Quantity'),
        'in_stock' => Yii::t('app', 'infinite amount'),
    ];
  }

  public function afterFind()
  {
    if (empty($this->cafe_id) && !empty($this->franchisee_id)) {
      $this->cafe_id = $this->franchisee_id * -1;
    }

    parent::afterFind(); // TODO: Change the autogenerated stub
  }

  /**
   * @inheritdoc
   */
  public static function find()
  {
    return new ShopProductQuery(get_called_class());
  }

  public function beforeValidate()
  {
    $cafe = Yii::$app->cafe;

    $this->franchisee_id = $cafe->getFranchiseeId();
    $this->cafe_id = $cafe->getId();

    if(empty($this->external_sale_available)){
      $this->external_sale_available=0;
    }
    /*if ($this->cafe_id > 0) {
      $cafe = Cafe::find()->where(['id' => $this->cafe_id])->one();

      if ($cafe) {
        $this->franchisee_id = $cafe->franchisee_id;
      }
    } elseif ($this->cafe_id < 0) {
      $this->franchisee_id = abs($this->cafe_id);
      $this->cafe_id = null;
    }*/

    return parent::beforeValidate(); // TODO: Change the autogenerated stub
  }

  public function afterSave($insert, $changedAttributes)
  {
    if ($this->old_quantity != $this->new_quantity) {
      $delta_quantity = $this->old_quantity - $this->new_quantity;
      if ($delta_quantity < 0) {
        ShopTransaction::createTransaction(
            ShopTransaction::OPERATION_TYPE_INCOME,
            $this->id,
            -$delta_quantity
        );
      } else {
        ShopTransaction::createTransaction(
            ShopTransaction::OPERATION_TYPE_WRITE_OFF,
            $this->id,
            $delta_quantity
        );
      }
    }

    parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
  }

  public function getImageUrl()
  {
    return !empty($this->image) ? $this->image : self::$default_image;
  }

  public function getQuantity($cafe_id = null)
  {
    if ($this->in_stock) {
      return null;
    }
    $warehouse = $this->getWarehouse($cafe_id)->one();

    return ($warehouse) ? $warehouse->quantity : 0;
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getFranchisee()
  {
    return $this->hasOne(Franchisee::className(), ['id' => 'franchisee_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getCafe()
  {
    return $this->hasOne(Cafe::className(), ['id' => 'cafe_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getSupplier()
  {
    return $this->hasOne(ShopSupplier::className(), ['id' => 'supplier_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getCategory()
  {
    return $this->hasOne(ShopCategory::className(), ['id' => 'category_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getWarehouses()
  {
    return $this->hasMany(ShopWarehouse::className(), ['product_id' => 'id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getWarehouse($cafe_id = null)
  {
    if ($cafe_id === null) {
      $cafe_id = Yii::$app->cafe->getId();
    }

    return $this->hasOne(ShopWarehouse::className(), ['product_id' => 'id'])->andOnCondition(['cafe_id' => $cafe_id]);
  }

  static function listToBay()
  {
    return self::find()
        ->leftJoin(
            ShopWarehouse::tableName(),
            self::tableName() . '.id=' . ShopWarehouse::tableName() . '.product_id and ' .
            ShopWarehouse::tableName() . '.cafe_id=' . Yii::$app->cafe->id
        )
        ->andWhere(['<', 'is_active', 2])
        ->andWhere(['and',
            [self::tableName() . '.in_stock' => 0],
            Yii::$app->helper->cafe_where(self::tableName()),
            ['or',
                'accounting_critical_minimum>quantity',
                'quantity is NULL',
            ],
            'accounting_critical_minimum>0',
        ])
        ->orderBy([
            'supplier_id' => SORT_ASC,
            'category_id' => SORT_ASC,
            'title' => SORT_ASC
        ]);
  }

  public function beforeDelete()
  {
    $count = ShopTransaction::find()
        ->where(
            ['product_id' => $this->id]
        )
        ->count();
    if ($count > 0) {
      $this->is_active = 2;
      $this->save();
      return false;
    }

    return parent::beforeDelete(); // TODO: Change the autogenerated stub
  }
}
