<?php

namespace frontend\modules\shop\models;

use frontend\models\Transaction;
use frontend\modules\cafe\models\Cafe;
use frontend\modules\cafe\models\CafeParams;
use frontend\modules\visitor\models\Visitor;
use frontend\modules\visits\models\VisitorLog;
use Yii;
use yii\db\Expression;

/**
 * This is the model class for table "{{%shop_sale}}".
 *
 * @property int $id
 * @property int $cafe_id
 * @property int $visitor_id
 * @property int $visitor_log_id
 * @property int $pay_man
 * @property string $comment
 * @property array $data
 * @property int $pay_state
 * @property int $created_by
 * @property int $updated_by
 * @property string $updated_at
 * @property string $created_at
 *
 * @property Cafe $cafe
 * @property Visitor $visitor
 * @property VisitorLog $visitorLog
 */
class ShopSale extends ShopBaseModel
{
  const SCENARIO_ANONYMOUS_MAIL_SET = 'anonymous_email_set'; // Setting email to anonymous Visit

  const DATA_TYPE_VISITOR_EMAIL = 'visitor_email';

  const STATUS_NOT_PAYED = 0;
  const STATUS_PAYED = 1;

  public $anonymous_email;

  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return '{{%shop_sale}}';
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
        [['cafe_id'], 'required'],
        [['cafe_id', 'visitor_id', 'visitor_log_id', 'pay_man', 'pay_state', 'created_by', 'updated_by'], 'integer'],
        [['comment'], 'string'],
        [['data', 'updated_at', 'created_at'], 'safe'],
        [['cafe_id'], 'exist', 'skipOnError' => true, 'targetClass' => Cafe::className(), 'targetAttribute' => ['cafe_id' => 'id']],
        [['visitor_id'], 'exist', 'skipOnError' => true, 'targetClass' => Visitor::className(), 'targetAttribute' => ['visitor_id' => 'id']],
        [['visitor_log_id'], 'exist', 'skipOnError' => true, 'targetClass' => VisitorLog::className(), 'targetAttribute' => ['visitor_log_id' => 'id']],

        ['anonymous_email', 'required', 'on' => self::SCENARIO_ANONYMOUS_MAIL_SET],
        ['anonymous_email', 'email', 'on' => self::SCENARIO_ANONYMOUS_MAIL_SET],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
        'id' => Yii::t('app', 'ID'),
        'cafe_id' => Yii::t('app', 'Cafe ID'),
        'visitor_id' => Yii::t('app', 'Visitor ID'),
        'visitor_log_id' => Yii::t('app', 'Visitor Log ID'),
        'comment' => Yii::t('app', 'Comment'),
        'data' => Yii::t('app', 'Data'),
        'pay_state' => Yii::t('app', 'Pay state'),
        'created_by' => Yii::t('app', 'Created By'),
        'updated_by' => Yii::t('app', 'Updated By'),
        'updated_at' => Yii::t('app', 'Updated At'),
        'created_at' => Yii::t('app', 'Created At'),
        'in_stock' => Yii::t('app', 'In stock'),
        'anonymous_email' => Yii::t('app', 'Email')
    ];
  }

  public function beforeSave($insert)
  {
    if ($this->scenario == self::SCENARIO_ANONYMOUS_MAIL_SET) {
      $data = $this->data;
      $data[self::DATA_TYPE_VISITOR_EMAIL] = $this->anonymous_email;
      $this->data = $data;
    }

    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }

  public function getCheckData()
  {
    $cafe = $this->cafe;
    $params = $cafe->getParam()->asArray()->one();
    $langParams = CafeParams::composeLangParams($params);
    $cafeCurrency = Yii::t('app', $cafe->currency);

    $total_cart = [
        'cost' => 0,
        'sum' => 0,
        'vat' => [],
        'vat_total' => 0,
    ];

    $summary_cart_vat = [];

    $cart_data = [];

    $transactions = $this->transactions;
    if (!empty($transactions)) {

      foreach ($transactions as $transaction) {
        $tVat = [];

        if (isset($transaction->vat)) {
          foreach ($transaction->vat as $vat) {
            $vat_merged = false;

            foreach ($summary_cart_vat as $uniteVatIndex => $uniteVat) {
              // If VAT equals - merge it
              if ($uniteVat['name'] == $vat['name']) {
                $vat_merged = true;
                $summary_cart_vat[$uniteVatIndex]['vat'] = ((float)$summary_cart_vat[$uniteVatIndex]['vat'] + (float)$summary_cart_vat[$uniteVatIndex]['vat']);
              }
            }

            // If VAT is absent - add it
            if (!$vat_merged) {
              $summary_cart_vat[] = $vat;
            }

            $tVat[$vat['name']] = $vat;
            $tVat[$vat['name']]['vat'] .= ' ' . $cafeCurrency;
          }
        }

        $cart_data[] = [
            'counter' => count($cart_data) + 1,
            'name' => $transaction->getProductTitle(),
            'price' => $transaction->price,
            'sum' => $transaction->sum . ' ' . $cafeCurrency,
            'vat' => $tVat,
            'count' => $transaction->quantity,
            'total' => $transaction->cost . ' ' . $cafeCurrency,
        ];

        $total_cart['cost'] += $transaction->cost;
        $total_cart['sum'] += $transaction->sum;
      }
    }


    foreach ($summary_cart_vat as $sCartVat) {
      $total_cart['vat'][$sCartVat['name']] = $sCartVat;
      $total_cart['vat'][$sCartVat['name']]['vat'] .= ' ' . $cafeCurrency;
      $total_cart['vat_total'] += $sCartVat['vat'];
    }

    $total_cart['cost'] .= ' ' . $cafeCurrency;
    $total_cart['sum'] .= ' ' . $cafeCurrency;
    $total_cart['vat_total'] .= ' ' . $cafeCurrency;

    $data = [
        "cafe" => $cafe->getAttributes(['id', 'name', 'max_person', 'address', 'currency', 'vat_code']),
        "visitor" => $this->visitor,
    ];

    if (!empty($cart_data)) {
      $data['cart'] = $cart_data;
      $data['total_cart'] = $total_cart;
    }

    $data['cafe']['logo'] = $cafe->getLogo();

    return $data;
  }

  public function afterDelete()
  {
    parent::afterDelete(); // TODO: Change the autogenerated stub
    $transaction = Transaction::find()
        ->where([
            'sale_id' => $this->id
        ])
        ->one();
    if ($transaction) {
      $transaction->delete();
    }
  }

  public function updateTransaction($time = false)
  {
    $transaction = Transaction::find()
        ->where([
            'sale_id' => $this->id
        ])
        ->one();
    if (!$transaction) {
      $transaction = new Transaction();
      $transaction->cafe_id = $this->cafe_id;
      $transaction->sale_id = $this->id;
    }
    $transaction->cost = $this->getCost();
    $transaction->sum = $this->getSum();
    $transaction->visitor_id = $this->visitor_id;

    $transaction->method = $this->pay_state;
    $transaction->pay_man = $this->pay_man;
    $transaction->created_at = $time ? $time : date("Y-m-d H:i:s");

    //сохраненеи если сумма больше 0 только
    //if ($transaction->sum > 0) {
    $transaction->save();
    //var_dump($transaction->errors)
  }

  public function afterSave($insert, $changedAttributes)
  {
    //if (isset($changedAttributes['pay_state']) && $changedAttributes['pay_state'] == 0) {

    $this->updateTransaction();
    // }
    //}
    parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
  }

  public static function cart($visit_id = null, $postProducts = [])
  {
    if (!$postProducts || count($postProducts) == 0) return false;

    $cafe = Yii::$app->cafe->get();

    $visitLog = null;
    if ($visit_id !== null) {
      $visitLog = VisitorLog::find()
          ->andWhere([
              'cafe_id' => $cafe->id,
              'id' => $visit_id,
          ])
          ->one();
    }

    $cafe = Yii::$app->cafe->get();
    $productIds = array_keys($postProducts);

    $fakeProductIds = [];
    foreach ($productIds as $productIdIndex => $productId) {
      if ($productId < 0) {
        $fakeProductIds[] = $productId;
        unset($productIds[$productIdIndex]);
      }
    }

    $products = ShopProduct::find()
        ->active()
        ->inCafe()
        ->andWhere(['id' => $productIds])
        ->asArray()
        ->indexBy('id')
        ->all();

    $transactionParams = [];

    if ($visitLog !== null) {
      $transactionParams['sale'] = [
          'cafe_id' => $cafe->id,
          'visitor_log_id' => $visitLog->id,
          'visitor_id' => $visitLog->visitor_id,
      ];
    }

    foreach ($postProducts as $postProductId => $postProductParams) {
      if (isset($products[$postProductId])) {
        ShopTransaction::makeSale((int)$postProductId, $postProductParams['quantity'], $transactionParams);
      } elseif (in_array($postProductId, $fakeProductIds)) {
        $fakeProductModel = new ShopProduct();
        $fakeProductModel->setAttributes([
            'title' => $postProductParams['title'],
            'price' => $postProductParams['price'],
            'tax_required' => $postProductParams['tax_required'],
        ]);
        ShopTransaction::makeSale($fakeProductModel, $postProductParams['quantity'], $transactionParams);
      }
    }

    Yii::$app->session->addFlash('success', Yii::t('app', 'Products added to visit basket'));
  }

  /**
   * Can email be sended to Visitor or not
   * Used to check availability of sending Check via Email
   *
   * @return bool
   */
  public function canSendMail()
  {
    return (
      // No visit - just Visitor
        $this->visitor && !empty($this->visitor->email)
        ||
        // Normal Visit
        $this->visitorLog && $this->visitorLog->canSendMail()
        ||
        // Anonymous and we have specified email
        !empty($this->data[self::DATA_TYPE_VISITOR_EMAIL])
    ) ? true : false;
  }

  /**
   * Get visit email
   *
   * @return null|string
   */
  public function getVisitorEmail()
  {
    if (!empty($this->data[self::DATA_TYPE_VISITOR_EMAIL])) {
      return $this->data[self::DATA_TYPE_VISITOR_EMAIL];
    } else if ($this->visitor && !empty($this->visitor->email)) {
      return $this->visitor->email;
    } else if ($this->visitorLog && $this->visitorLog->getVisitorEmail() !== null) {
      return $this->visitorLog->getVisitorEmail();
    }

    return null;
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getCafe()
  {
    return $this->hasOne(Cafe::className(), ['id' => 'cafe_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getVisitor()
  {
    return $this->hasOne(Visitor::className(), ['id' => 'visitor_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getVisitorLog()
  {
    return $this->hasOne(VisitorLog::className(), ['id' => 'visitor_log_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getTransactions()
  {
    return $this->hasMany(ShopTransaction::className(), ['sale_id' => 'id']);
  }

  public function getCost()
  {
    return $this->getTransactions()->select(new Expression('SUM(cost)'))->scalar();
  }

  public function getSum()
  {
    return $this->getTransactions()->select(new Expression('SUM(sum)'))->scalar();
  }

  public function getTransactionsCount()
  {
    return $this->getTransactions()->count();
  }

  public function getQuantitySummary()
  {
    return $this->getTransactions()->select(new Expression('SUM(quantity)'))->scalar();
  }
}
