<?php

namespace frontend\modules\shop\models;

use frontend\modules\cafe\models\Cafe;
use frontend\modules\franchisee\models\Franchisee;
use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "{{%shop_category}}".
 *
 * @property int $id
 * @property int $franchisee_id
 * @property int $cafe_id
 * @property string $title
 * @property int $created_by
 * @property int $updated_by
 * @property int $updated_at
 * @property int $created_at
 */
class ShopCategory extends ShopBaseModel
{
  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return '{{%shop_category}}';
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
        [['franchisee_id', 'title'], 'required'],
        [['cafe_id', 'franchisee_id', 'created_by', 'updated_by'], 'integer'],
        [['title'], 'string', 'max' => 255],
        [['updated_at', 'created_at'], 'safe'],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
        'id' => Yii::t('app', 'ID'),
        'franchisee_id' => Yii::t('app', 'Franchisee ID'),
        'cafe_id' => Yii::t('app', 'Cafe'),
        'title' => Yii::t('app', 'Title'),
        'created_by' => Yii::t('app', 'Created By'),
        'updated_by' => Yii::t('app', 'Updated By'),
        'updated_at' => Yii::t('app', 'Updated At'),
        'created_at' => Yii::t('app', 'Created At'),
    ];
  }


  public function afterFind()
  {
    if (empty($this->cafe_id) && !empty($this->franchisee_id)) {
      $this->cafe_id = $this->franchisee_id * -1;
    }

    parent::afterFind(); // TODO: Change the autogenerated stub
  }

  public function beforeValidate()
  {
    if ($this->cafe_id > 0) {
      $cafe = Cafe::find()->where(['id' => $this->cafe_id])->one();

      if ($cafe) {
        $this->franchisee_id = $cafe->franchisee_id;
      }
    } elseif ($this->cafe_id < 0) {
      $this->franchisee_id = abs($this->cafe_id);
      $this->cafe_id = null;
    }

    return parent::beforeValidate(); // TODO: Change the autogenerated stub
  }

  /**
   * Return array of suppliers with id => name
   */
  public static function getList($franchisee_id = null, $cafe_id = null)
  {
    $query = self::find();

    if ($franchisee_id === null) {
      $franchisee_id = Yii::$app->cafe->getFranchiseeId();
    }

    $query->andWhere([
        'franchisee_id' => $franchisee_id,
    ]);

    if ($cafe_id !== null) {
      $query->andWhere([
          'cafe_id' => $cafe_id,
      ]);
    }

    return ArrayHelper::map($query->asArray()->all(), 'id', 'title');
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getFranchisee()
  {
    return $this->hasOne(Franchisee::className(), ['id' => 'franchisee_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getCafe()
  {
    return $this->hasOne(Cafe::className(), ['id' => 'cafe_id']);
  }
}
