<?php

/**
 * Created by PhpStorm.
 * User: acid
 * Date: 11.09.18
 * Time: 17:37
 */

namespace frontend\modules\visits\models;

use common\components\VatHelper;
use DateTime;
use frontend\models\Transaction;
use frontend\modules\shop\models\ShopSale;
use Yii;

class VisitorLogEditForm extends \yii\base\Model
{
  const STATUS_PRESENT = 1;
  const STATUS_ABSENT = 2;

  public $status;
  public $pay_method;

  public $add_date;
  public $add_time;

  public $finish_date;
  public $finish_time;

  public $recalc_cost = true;
  public $cost;

  public $comment;

  /**
   * @var VisitorLog
   */
  private $_visit;

  /**
   * Creates a form model for given visitor log
   *
   */
  public function __construct(VisitorLog $visit)
  {
    $this->_visit = $visit;

    parent::__construct();
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
        [['status', 'add_date', 'add_time', 'recalc_cost'], 'required'],
        [['status'], 'integer'],

        [['comment'], 'string', 'max' => 255],
        [['comment'], 'required', 'when' => function ($model) {
          return $model->pay_method == VisitorLog::PAY_METHOD_NOT_PAID;
        }],

        [['cost'], 'number'],
        [['pay_method'], 'integer'],

        [['pay_method', 'finish_date', 'finish_time'], 'required', 'when' => function ($model) {
          return $model->status == self::STATUS_ABSENT;
        }],

        [['cost'], 'required', 'when' => function ($model) {
          return $model->recalc_cost == false;
        }],

        ['finish_time', 'validateDates'],
    ];
  }

  public function validateDates($attribute, $params, $validator)
  {
    $add_time = DateTime::createFromFormat(Yii::$app->params['lang']['datetime'], $this->add_date . ' ' . $this->add_time);
    $finish_time = DateTime::createFromFormat(Yii::$app->params['lang']['datetime'], $this->finish_date . ' ' . $this->finish_time);

    if ($add_time > $finish_time) {
      $this->addError('add_date', Yii::t('app', "Start time must be sooner then End time"));
      $this->addError('add_time', Yii::t('app', "Start time must be sooner then End time"));
      $this->addError('finish_date', Yii::t('app', "Start time must be sooner then End time"));
      $this->addError('finish_time', Yii::t('app', "Start time must be sooner then End time"));
    }
  }

  public function init()
  {
    $this->status = $this->_visit->finish_time ? self::STATUS_ABSENT : self::STATUS_PRESENT;
    $this->pay_method = $this->_visit->pay_state;

    $add_time = new DateTime($this->_visit->add_time);
    $finish_time = new DateTime($this->_visit->finish_time);

    $this->add_date = $add_time->format(Yii::$app->params['lang']['date']);
    $this->add_time = $add_time->format(Yii::$app->params['lang']['time']);

    $this->finish_date = $finish_time->format(Yii::$app->params['lang']['date']);
    $this->finish_time = $finish_time->format(Yii::$app->params['lang']['time']);

    $cost = $this->_visit->cost;

    // Summary of Add to cost VAT's
    list(, , , $add_to_cost_vats) = VatHelper::calculate($cost, null, null, [
        VatHelper::ADD_TO_COST_ONLY,
    ]);

    $this->cost = $cost - $add_to_cost_vats;

    $this->comment = $this->_visit->comment;

    parent::init(); // TODO: Change the autogenerated stub
  }

  public function save()
  {
    if (!$this->validate()) {
      return false;
    }

    $add_time = DateTime::createFromFormat(Yii::$app->params['lang']['datetime'], $this->add_date . ' ' . $this->add_time);

    $this->_visit->add_time = $add_time->format('Y-m-d H:i:s');

    if ($this->status == self::STATUS_ABSENT) {
      $finish_time = DateTime::createFromFormat(Yii::$app->params['lang']['datetime'], $this->finish_date . ' ' . $this->finish_time);

      $this->_visit->finish_time = $finish_time->format('Y-m-d H:i:s');

      $this->_visit->pay_state = $this->pay_method;

      $this->_visit->calcCost();

      if ($this->recalc_cost == false) {
        list($sum, $cost, $vat) = VatHelper::calculate($this->cost);
        $this->_visit->vat = $vat;
        $this->_visit->cost = $cost;
        $this->_visit->sum = $sum;
      }

    } else if ($this->status == self::STATUS_PRESENT) {
      $this->_visit->finish_time = null;

      $this->_visit->pay_state = 0;
      $this->_visit->sum = 0;
      $this->_visit->cost = null;
      $this->_visit->calcCost();

      if ($this->_visit->getOldAttribute('status') != $this->status) {
        //Удаляем последний платеж
        $tr = Transaction::find()
            ->where(['visit_id' => $this->_visit->id])
            ->orderBy(['id' => SORT_DESC])
            ->one();
        if ($tr) {
          $tr->delete();


          $tr = Transaction::find()
              ->where([
                  'visit_id' => null,
                  'visitor_id' => $tr->visitor_id,
                  'pay_man' => $tr->pay_man,
                  'created_at' => $tr->created_at,
                  'cafe_id' => $tr->cafe_id,
              ])
              ->orderBy(['id' => SORT_DESC])
              ->one();
          if ($tr) {
            $sale = ShopSale::find()
                ->where(['id' => $tr->sale_id])
                ->one();
            $sale->pay_state = ShopSale::STATUS_NOT_PAYED;
            $sale->save();

            $tr->delete();
          }
        }
      }
    }

    $this->_visit->comment = $this->comment;

    return $this->_visit->save(false);
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
        'add_date' => Yii::t('app', 'Start date'),
        'add_time' => Yii::t('app', 'Start time'),
        'finish_date' => Yii::t('app', 'End date'),
        'finish_time' => Yii::t('app', 'End time'),
        'cost' => Yii::t('app', 'Cost'),
        'status' => Yii::t('app', 'status'),
        'pay_method' => Yii::t('app', 'Pay State'),
        'recalc_cost' => Yii::t('app', 'Recalculate Cost'),
        'comment' => Yii::t('app', 'Comment'),
    ];
  }

  public static function getStatusLabels($index = null)
  {
    $items = [
        self::STATUS_PRESENT => Yii::t('app', "present"),
        self::STATUS_ABSENT => Yii::t('app', "absent"),
    ];

    if ($index !== null) {
      return (isset($items[$index])) ? $items[$index] : Yii::t('app', 'Unknown');
    } else {
      return $items;
    }
  }

  public function getId()
  {
    return $this->_visit->id;
  }

  public function getVisit()
  {
    return $this->_visit;
  }
}