<?php

namespace frontend\modules\visits\models;

use app\helpers\GridHelper;
use kartik\daterange\DateRangeBehavior;
use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use yii\db\Expression;

/**
 * VisitorLogSearch represents the model behind the search form of `frontend\modules\visits\models\VisitorLog`.
 */
class VisitorLogSearch extends VisitorLog
{
  public $add_time_from;
  public $add_time_to;
  public $finish_time_from;
  public $finish_time_to;
  public $cost_from;
  public $cost_to;
  public $sum_from;
  public $sum_to;
  public $guest_m_from;
  public $guest_m_to;
  public $guest_chi_from;
  public $guest_chi_to;
  public $sum_no_cert_from;
  public $sum_no_cert_to;
  public $pre_enter_from;
  public $pre_enter_to;
  public $kiosk_disc_from;
  public $kiosk_disc_to;
  public $status;

  public $query;
  public $visitor;
  public $visitor_code;
  public $visitor_email;

  private $slideParamsDb = true;

  private $slideParams = array(
      'user_id' =>
          array(
              'min' => 0,
              'max' => 100,
              'step' => 1,
          ),
      'cafe_id' =>
          array(
              'min' => 0,
              'max' => 100,
              'step' => 1,
          ),
      'cost' =>
          array(
              'min' => 0,
              'max' => 30,
              'step' => 0.1,
          ),
      'sum' =>
          array(
              'min' => 0,
              'max' => 30,
              'step' => 0.1,
          ),

      'certificate_val' =>
          array(
              'min' => 0,
              'max' => 100,
              'step' => 0.1,
          ),
      'guest_m' =>
          array(
              'min' => 0,
              'max' => 100,
              'step' => 1,
          ),
      'guest_chi' =>
          array(
              'min' => 0,
              'max' => 100,
              'step' => 1,
          ),

      'sum_no_cert' =>
          array(
              'min' => 0,
              'max' => 100,
              'step' => 0.1,
          ),
      'pre_enter' =>
          array(
              'min' => 0,
              'max' => 100,
              'step' => 1,
          ),
      'kiosk_disc' =>
          array(
              'min' => 0,
              'max' => 100,
              'step' => 1,
          ),
  );

  public function init()
  {
    $this->slideParams['sum']['max'] = Yii::$app->cafe->max_cost;
    $this->slideParams['cost']['max'] = Yii::$app->cafe->max_cost * 1.5;
    parent::init(); // TODO: Change the autogenerated stub
  }

  public function behaviors()
  {
    return [
        [
            "class" => DateRangeBehavior::className(),
            "attribute" => "add_time",
            "dateStartAttribute" => "add_time_from",
            "dateEndAttribute" => "add_time_to",
            "dateFormat" => false,
            "dateStartFormat" => false,
            "dateEndFormat" => false,
        ],
        [
            "class" => DateRangeBehavior::className(),
            "attribute" => "finish_time",
            "dateStartAttribute" => "finish_time_from",
            "dateEndAttribute" => "finish_time_to",
            "dateFormat" => false,
            "dateStartFormat" => false,
            "dateEndFormat" => false,
        ],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
        [['id', 'user_id', 'type', 'cafe_id', 'certificate_type', 'guest_m', 'guest_m_from', 'guest_m_to', 'guest_chi', 'guest_chi_from', 'guest_chi_to', 'is_child', 'pre_enter', 'pre_enter_from', 'pre_enter_to', 'kiosk_disc', 'kiosk_disc_from', 'kiosk_disc_to', 'terminal_ans', 'status', 'pay_state'], 'integer'],
        [['visitor_id', 'visitor', 'visitor_code', 'visitor_email', 'add_time', 'finish_time', 'comment', 'notice', 'visit_cnt', 'pay_man', 'cnt_disk', 'certificate_number', 'vat'], 'safe'],
        [['add_time', 'finish_time'], 'match', 'pattern' => '/^.+\s\-\s.+$/'],
        [['cost', 'cost_from', 'cost_to', 'sum', 'sum_from', 'sum_to', 'certificate_val', 'sum_no_cert', 'sum_no_cert_from', 'sum_no_cert_to'], 'number'],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function scenarios()
  {
    // bypass scenarios() implementation in the parent class
    return Model::scenarios();
  }

  /**
   * Creates data provider instance with search query applied
   *
   * @param array $params
   *
   * @return ActiveDataProvider
   */
  public function search($params, $isTips = false)
  {
    $query = VisitorLog::find();
    // add conditions that should always apply here

    $dataProvider = new ActiveDataProvider([
        'query' => $query,
        'sort' => array(
            'defaultOrder' => [
                'id' => SORT_DESC
            ]
        ),
    ]);

    $this->load($params);
    $this->query = $query;

    if (!$this->validate()) {
      // uncomment the following line if you do not want to return any records when validation fails
      // $query->where('0=1');
      return $dataProvider;
    }

    $join_visitors = false;

    /*$query->andFilterWhere(
        ['pay_state'=>-1]
    );*/

    if ($isTips) {
      $query->andFilterWhere(['and',
          ['>', 'tip', 0],
          ['pay_state' => [VisitorLog::PAY_METHOD_CARD, VisitorLog::PAY_METHOD_CASH]],
      ]);

      if (empty($this->finish_time) || is_null($this->finish_time)) {
        $this->finish_time_from = strtotime("-1 month");
        $this->finish_time_to = time();
        $this->finish_time = [$this->finish_time_from, $this->finish_time_to];

        $this->finish_time_from = date(Yii::$app->params['lang']['date'], $this->finish_time_from);
        $this->finish_time_to = date(Yii::$app->params['lang']['date'], $this->finish_time_to);
      } else {
        //ddd($this->finish_time,Yii::$app->params['lang']['date']);
        //$this->finish_time = [$this->finish_time_from,$this->finish_time_to];
      }
    }

    if ($this->visitor == Yii::t('app', 'Anonymous')) {
      $query->andFilterWhere(['is', 'visitor_id', (new Expression('Null'))]);
    } else if ($this->visitor) {
      $join_visitors = true;
      //Visitor::findByString($this->visitor, $query);
      $q = explode(' ', strtolower($this->visitor));
      if (count($q) == 1) {
        $query->andFilterWhere([
            'or',
            ['like', 'LOWER(f_name)', $q[0] . '%', false],
            ['like', 'LOWER(l_name)', $q[0] . '%', false]
        ]);
      } else if (count($q) == 2) {
        $query->andFilterWhere([
            'or', [
                'and',
                ['like', 'LOWER(l_name)', $q[0] . '%', false],
                ['like', 'LOWER(f_name)', $q[1] . '%', false],
            ], [
                'and',
                ['like', 'LOWER(l_name)', $q[1] . '%', false],
                ['like', 'LOWER(f_name)', $q[0] . '%', false],
            ]
        ]);
      } else {
        return false;
      }
    }

    if (!empty($this->visitor_code)) {
      $join_visitors = true;
      $query->andWhere(['like', 'LOWER(code)', strtolower($this->visitor_code)]);
    }

    if (!empty($this->visitor_email)) {
      $join_visitors = true;
      $query->andWhere([
          'or',
          ['like', 'LOWER(email)', strtolower($this->visitor_email)],
          ['like', 'JSON_EXTRACT(visitor_log.notice, "$.visitor_email")', $this->visitor_email]
      ]);
    }

    if ($join_visitors) {
      $query->leftJoin('visitor', 'visitor.id=visitor_id');
    }

    $user_id = $this->user_id;
    if ($user_id == 0) {
      $user_id = null;
    } else if ($this->user_id == -1) {
      $query->andFilterWhere(['is', 'user_id', (new Expression('Null'))]);
    } else if ($user_id) {
      $query->andFilterWhere(['user_id' => $user_id]);
    }

    if ($this->pay_state == -2) {
      unset($this->pay_state);
    }

    if ($this->type == -1) {
      unset($this->type);
    } elseif ($this->type == 50) {
      $query->andWhere('guest_m>0 or guest_chi>0');
      unset($this->type);
    }


    if ($this->status == 1) {
      $query->andFilterWhere(['is', 'finish_time', (new Expression('Null'))]);
      //ddd($query->count());
    } elseif ($this->status == 2) {
      $query->andWhere(['not', ['finish_time' => null]]);
    }
    // grid filtering conditions
    $query->andFilterWhere([
        'visitor_log.id' => $this->id,
        'visitor_log.cafe_id' => Yii::$app->cafe->id,
        'cost' => $this->cost,
        'sum' => $this->sum,
        'pay_state' => $this->pay_state,
        'pause_start' => $this->pause_start,
        'pause' => $this->pause,
        'certificate_type' => $this->certificate_type,
        //'certificate_val' => $this->certificate_val,
        'guest_m' => $this->guest_m,
        'guest_chi' => $this->guest_chi,
        'sum_no_cert' => $this->sum_no_cert,
        'pre_enter' => $this->pre_enter,
        'kiosk_disc' => $this->kiosk_disc,
        'terminal_ans' => $this->terminal_ans,
        'type' => $this->type,
        'is_child' => $this->is_child,
        'visitor_id' => $this->visitor_id,
    ]);

    $query->andFilterWhere(['like', '.comment', $this->comment])
        ->andFilterWhere(['like', '.notice', $this->notice])
        ->andFilterWhere(['like', '.visit_cnt', $this->visit_cnt])
        ->andFilterWhere(['like', '.pay_man', $this->pay_man])
        ->andFilterWhere(['like', '.cnt_disk', $this->cnt_disk])
        ->andFilterWhere(['like', '.certificate_number', $this->certificate_number])
        ->andFilterWhere(['like', '.vat', $this->vat]);


    //Filter for ranger add_time
    if ($this->add_time_from) {
      $query->andFilterWhere(['>=', 'add_time', GridHelper::getDbDateFromDateRangeFormat($this->add_time_from)]);
      $query->andFilterWhere(['<=', 'add_time', GridHelper::getDbDateFromDateRangeFormat($this->add_time_to)]);
    }

    //Filter for ranger finish_time
    if ($this->finish_time_from) {
      $t1 = strtotime($this->finish_time_from);
      $t2 = strtotime($this->finish_time_to);
      $t0 = mktime(0, 0, 0);
      $n_r = ($t0 >= $t1 && $t0 <= $t2);
      $w = [
          'and',
          ['>=', 'finish_time', GridHelper::getDbDateFromDateRangeFormat($this->finish_time_from, null, !$isTips)],
          ['<=', 'finish_time', GridHelper::getDbDateFromDateRangeFormat($this->finish_time_to, null, !$isTips)],
      ];
      if ($n_r) {
        $w = ['or',
            ['is', 'finish_time', null],
            $w,
        ];
      }
      $query->andWhere($w);
    } else {
      //$t1 = time();
      //$t2 = time();
      //$n_r = true;
    }


    //Filter for ranger cost
    if (is_numeric($this->cost_from)) {
      $query
          ->andFilterWhere(['>=', $this->tableName() . '.cost', $this->cost_from])
          ->andFilterWhere(['<=', $this->tableName() . '.cost', $this->cost_to]);
    };

    //Filter for ranger sum
    if (is_numeric($this->sum_to)) {
      $query
          ->andFilterWhere(['>=', $this->tableName() . '.sum', (float)$this->sum_from])
          ->andFilterWhere(['<=', $this->tableName() . '.sum', (float)$this->sum_to])
          ->andWhere(['not', ['finish_time' => null]]);;
    };


    //Filter for ranger guest_m
    if ($this->guest_m) {
      $query
          ->andFilterWhere(['>=', 'guest_m', $this->guest_m_from])
          ->andFilterWhere(['<=', 'guest_m', $this->guest_m_to]);
    };

    //Filter for ranger guest_chi
    if ($this->guest_chi) {
      $query
          ->andFilterWhere(['>=', 'guest_chi', $this->guest_chi_from])
          ->andFilterWhere(['<=', 'guest_chi', $this->guest_chi_to]);
    };


    //Filter for ranger sum_no_cert
    if ($this->sum_no_cert) {
      $query
          ->andFilterWhere(['>=', 'sum_no_cert', $this->sum_no_cert_from])
          ->andFilterWhere(['<=', 'sum_no_cert', $this->sum_no_cert_to]);
    };

    //Filter for ranger pre_enter
    if ($this->pre_enter) {
      $query
          ->andFilterWhere(['>=', 'pre_enter', $this->pre_enter_from])
          ->andFilterWhere(['<=', 'pre_enter', $this->pre_enter_to]);
    };

    //Filter for ranger kiosk_disc
    if ($this->kiosk_disc) {
      $query
          ->andFilterWhere(['>=', 'kiosk_disc', $this->kiosk_disc_from])
          ->andFilterWhere(['<=', 'kiosk_disc', $this->kiosk_disc_to]);
    };

    $this->query = $query;
    return $dataProvider;
  }

  public function getSlideParams($name)
  {
    if ($this->slideParamsDb) {
      $query = VisitorLog::find();

      $tableName = self::tableName() . '.';

      $query->andFilterWhere([
          $tableName . 'cafe_id' => $this->cafe_id,
      ]);

      $select = [];
      foreach ($this->slideParams as $key => $value) {
        $select[] = 'max(' . $tableName . $key . ') as max_' . $key;
        $select[] = 'min(case when ' . $tableName . $key . ' >= 0 then ' . $tableName . $key . ' end) as min_' . $key;
      }
      $query->select($select);

      $result = $query->asArray()->one();
      foreach ($this->slideParams as $key => &$value) {
        $value['min'] = $result['min_' . $key];
        $value['max'] = $result['max_' . $key];

        $value['min'] = round($value['min'], 2, $value['min'] < 0 ? PHP_ROUND_HALF_UP : PHP_ROUND_HALF_DOWN);
        $value['max'] = round($value['max'], 2, $value['max'] > 0 ? PHP_ROUND_HALF_UP : PHP_ROUND_HALF_DOWN);
        if ($value['min'] == $value['max']) {
          //$value['min']-=5;
          $value['max'] += 5;
        }
      }
      $this->slideParamsDb = false;
    }

    $base = (isset($this->slideParams[$name]) ? $this->slideParams[$name] : []);

    if (!isset($base['min'])) $base['min'] = isset($base['max']) ? $base['max'] - 100 : 0;
    if (!isset($base['max'])) $base['max'] = $base['min'] + 100;
    if (!isset($base['step'])) $base['step'] = ($base['max'] - $base['min']) / 100;

    return $base;
  }
}
