<?php

namespace frontend\modules\visits\controllers;

use common\components\widget\BulkButtonWidget;
use console\jobs\CheckMailSendJob;
use frontend\components\Controller;
use frontend\models\Transaction;
use frontend\modules\certificate\models\Certificate;
use frontend\modules\mails\models\TemplateMail;
use frontend\modules\visits\models\VisitorLog;
use frontend\modules\visits\models\VisitorLogEditForm;
use frontend\modules\visits\models\VisitorLogSearch;
use Yii;
use yii\db\Expression;
use yii\helpers\Html;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * AdminController implements the CRUD actions for VisitorLog model.
 */
class AdminController extends Controller
{

  private $def_sel_column = [
      'id',
      'user_id',
      'visitor',
      'duration',
      'type',
      'cafe_id',
      'add_time',
      'comment',
      'finish_time',
      'cost',
      'sum',
      'pay_state',
      'pause_start',
      'pause',
      'certificate_type',
      'certificate_val',
      'visit_cnt',
      'pay_man',
      'guest_m',
      'guest_chi',
      'cnt_disk',
      'chi',
      'sum_no_cert',
      'pre_enter',
      'kiosk_disc',
      'terminal_ans',
      'certificate_number',
      'vat',
      'status',
  ];

  private $col_cash = "columns_VisitorLog";

  /**
   * @inheritdoc
   */
  public function behaviors()
  {
    return [
    ];
  }

  public function createAction($id)
  {
    if ($id == 'columns-tips') {
      $id = 'columns';
      $this->col_cash = 'tips_columns';
      //return $this->actionColumns();
    }

    return parent::createAction($id); // TODO: Change the autogenerated stub
  }

  /**
   * Lists all VisitorLog models.
   * @return mixed
   */
  public function actionIndex()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('VisitorLogView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $searchModel = new VisitorLogSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    $canCreate = Yii::$app->user->can('VisitorLogCreate');
    $actions = "{view}{stop}";

    $panelButtons = '';

    if (
        Yii::$app->user->can('TemplateMailView') &&
        Yii::$app->cafe->can('mails')
    ) {
      $panelButtons .= TemplateMail::getButtons('visits');
    };

    if (Yii::$app->user->can('VisitorLogDelete')) {
      $actions .= '{delete}';
      $panelButtons .= BulkButtonWidget::widget();
    };

    if (Yii::$app->user->can('VisitorLogUpdate')) {
      $actions .= "{update}";
    };

    if (Yii::$app->user->can('VisitorLogUpdate') && Yii::$app->cafe->can('certificate')) {
      $actions .= "{certificate}";
      $actions .= "{certificate_delete}";
    }

    if (Yii::$app->cafe->can('endVisitPrintCheckManual')) {
      $actions .= "{check_print}";
    }

    if (Yii::$app->cafe->can('endVisitMailCheckManual')) {
      $actions .= "{check_mail}";
    }

    $columns = include(__DIR__ . '/../views/admin/_columns.php');
    if (Yii::$app->user->isGuest) {
      $sel_column = Yii::$app->session->get("columns_VisitorLog", false);
    } else {
      $user = Yii::$app->getUser()->getIdentity();
      $sel_column = $user->getActiveColumn("columns_VisitorLog");
    }
    if (!$sel_column) {
      $sel_column = $this->def_sel_column;
    }
    foreach ($columns as $k => $column) {
      $column_name = !is_array($column) ? $column : (isset($column['attribute']) ? $column['attribute'] : false);
      if ($column_name && !in_array($column_name, $sel_column)) {
        unset($columns[$k]);
      }
    }

//тотал база
    /*$tot = clone $searchModel->query;
    $tot->andWhere([
        'and',
        ['not', ['finish_time' => null]],
        ['>', 'finish_time' ,0],
    ]);
    $tot->select([
        'sum(`visitor_log`.`sum`) as `sum`',
        'sum(`visitor_log`.`cost`) as `cost`',
        'sum(UNIX_TIMESTAMP(`visitor_log`.`finish_time`)-UNIX_TIMESTAMP(`visitor_log`.`add_time`)) as `dt`',
        'count(`visitor_log`.`id`) as cnt'
    ]);
    $tot = $tot->asArray()->one();
*/
    $total = [
        'absent' => [
            'sum' => 0,//round($tot['sum'], 2),
            'cost' => 0,//round($tot['cost'], 2),
            'vat' => 0,//round($tot['cost'] - $tot['sum'], 2),
            'dt' => 0,//$tot['dt'],
            'cnt' => 0,//$tot['cnt'],
        ],
        'present' => [
            'sum' => 0,
            'cost' => 0,
            'dt' => 0,
            'cnt' => 0,
        ]
    ];

//тотал по присутствующим
    $tot = clone $searchModel->query;
    $tot->andFilterWhere(['is', 'finish_time', (new Expression('Null'))]);
    $tot = $tot->all();
    $total['present']['cnt'] = count($tot);
    foreach ($tot as $visit) {
      if ($visit->cost === false) continue;
      $total['present']['sum'] += $visit->sum;
      $total['present']['cost'] += $visit->cost;
      $total['present']['dt'] += $visit->duration;
    }
    $total['present']['vat'] = round($total['present']['cost'] - $total['present']['sum'], 2);
    $total['present']['cost'] = round($total['present']['cost'], 2);
    $total['present']['sum'] = round($total['present']['sum'], 2);

//чаевые
    $tot = clone $searchModel->query;
    $tot->andWhere(['not', ['finish_time' => null]]);
    $tot->select('sum(tip) as tip');
    $tot->asArray();
    $total += $tot->one();
    $total['tip'] = round($total['tip'], 2);

//по типам платежа
    $tot_select = [
        'pay_state' => 'if(tr.method>0,tr.method,pay_state)',
        'visitor_log.terminal_ans',
        'sum(if(tr.method>0,tr.sum,`visitor_log`.`sum`)) as `sum`',
        'sum(if(tr.method>0,tr.cost,`visitor_log`.`cost`)) as `cost`',
        'sum(UNIX_TIMESTAMP(`visitor_log`.`finish_time`)-UNIX_TIMESTAMP(`visitor_log`.`add_time`)) as `dt`',
        'count(`visitor_log`.`id`) as cnt',
    ];
    $tot = clone $searchModel->query;
    $tot->rightJoin(Transaction::tableName() . ' tr', 'tr.visit_id = `visitor_log`.id');
    $tot = $tot->andWhere([
            'and',
            ['not', ['finish_time' => null]],
            ['not', ['pay_state' => 0]],
        ]
    )
        ->groupBy(['if(tr.method>0,tr.method,pay_state)', 'if(visitor_log.terminal_ans>0,1,0)'])
        ->select($tot_select)
        ->asArray()
        ->all();

    $t = [
        'sum' => 0,
        'cost' => 0,
        'dt' => 0,
        'vat' => 0,
        'cnt' => 0,
    ];
    $total['by_pay'] = [
        -2 => $t,
        -1 => $t,
        0 => $t,
        1 => $t,
        2 => $t,
    ];

    foreach ($tot as $t) {
      $code =
          $t['pay_state'] == VisitorLog::PAY_METHOD_NOT_PAID ? -1 :
              ($t['pay_state'] == VisitorLog::PAY_METHOD_CASH ? 0 :
                  ($t['terminal_ans'] == 0 ? 1 : 2));
      $total['by_pay'][$code]['sum'] += round($t['sum'], 2);
      $total['by_pay'][$code]['cost'] += round($t['cost'], 2);
      $total['by_pay'][$code]['vat'] += round($t['cost'] - $t['sum'], 2);
      $total['by_pay'][$code]['cnt'] += $t['cnt'];
      $total['by_pay'][$code]['dt'] += $t['dt'];
    };

//неоплаченные платежи
    $sel = [
        'pay_state' => 'pay_state',
        'visitor_log.terminal_ans',
        'sum(`visitor_log`.`sum`) as `sum`',
        'sum(`visitor_log`.`cost`) as `cost`',
        'sum(UNIX_TIMESTAMP(`visitor_log`.`finish_time`)-UNIX_TIMESTAMP(`visitor_log`.`add_time`)) as `dt`',
        'count(`visitor_log`.`id`) as cnt',
    ];
    $tot = clone $searchModel->query;
    $t = $tot->andWhere(['pay_state' => -1])
        //->groupBy(['pay_state'])
        ->select($sel)
        ->asArray()
        ->one();

    $total['by_pay'][-1]['sum'] += round($t['sum'], 2);
    $total['by_pay'][-1]['cost'] += round($t['cost'], 2);
    $total['by_pay'][-1]['vat'] += round($t['cost'] - $t['sum'], 2);
    $total['by_pay'][-1]['cnt'] += $t['cnt'];
    $total['by_pay'][-1]['dt'] += $t['dt'];

//бесплатные платежи
    $tot = clone $searchModel->query;
    $t = $tot
        ->leftJoin(Transaction::tableName() . ' tr', 'tr.visit_id = `visitor_log`.id')
        ->andWhere(['not',['pay_state' => -1]])
        ->andWhere(['tr.id'=>null])
    //->groupBy(['pay_state'])
        ->select($sel)
        ->asArray()
        ->one();

    $total['by_pay'][-2]['sum'] += round($t['sum'], 2);
    $total['by_pay'][-2]['cost'] += round($t['cost'], 2);
    $total['by_pay'][-2]['vat'] += round($t['cost'] - $t['sum'], 2);
    $total['by_pay'][-2]['cnt'] += $t['cnt'];
    $total['by_pay'][-2]['dt'] += $t['dt'];
//тотал по отсутствующим
    foreach ($total['by_pay'] as $t){
      foreach ($t as $k=>$val) {
        $total['absent'][$k] += $val;
      }
    }
//общий тотал
    $total['total'] = [
        'sum' => round($total['present']['sum'] + $total['absent']['sum'], 2),
        'cost' => round($total['present']['cost'] + $total['absent']['cost'], 2),
        'vat' => round($total['present']['vat'] + $total['absent']['vat'], 2),
        'dt' => $total['present']['dt'] + $total['absent']['dt'],
        'cnt' => $total['present']['cnt'] + $total['absent']['cnt'],
    ];

    return $this->render('index', [
        'searchModel' => $searchModel,
        'dataProvider' => $dataProvider,
        'columns' => $columns,
        'canCreate' => $canCreate,
        'panelButtons' => $panelButtons,
        'title' => Yii::t('app', 'VisitorLog list'),
        'total' => $total,
    ]);
  }

  /**
   * Lists all VisitorLog models.
   * @return mixed
   */
  public function actionTips()
  {
    if (
        Yii::$app->user->isGuest ||
        !Yii::$app->user->can('VisitorLogView') ||
        !Yii::$app->cafe->can('Tips')
    ) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $searchModel = new VisitorLogSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams, true);

    $canCreate = Yii::$app->user->can('VisitorLogCreate');

    $panelButtons = '';

    $columns = include(__DIR__ . '/../views/admin/_columns_tips.php');


    if (Yii::$app->user->isGuest) {
      $sel_column = Yii::$app->session->get("tips_columns", false);
    } else {
      $user = Yii::$app->getUser()->getIdentity();
      $sel_column = $user->getActiveColumn("tips_columns");
    }

    if (!$sel_column) {
      $sel_column = $this->def_sel_column;
    }
    foreach ($columns as $k => $column) {
      $column_name = !is_array($column) ? $column : (isset($column['attribute']) ? $column['attribute'] : false);
      if ($column_name && !in_array($column_name, $sel_column)) {
        unset($columns[$k]);
      }
    }

    $tot = clone $searchModel->query;
    $tot->andWhere(['not', ['finish_time' => null]]);
    $tot->select('sum(tip) as tip');
    $tot->asArray();
    $tot = $tot->one();

    foreach ($tot as &$t) {
      $t = number_format($t, 2, '.', ' ');
    }

    return $this->render('tips', [
        'searchModel' => $searchModel,
        'dataProvider' => $dataProvider,
        'columns' => $columns,
        'total' => $tot,
        'title' => Yii::t('app', 'Tips'),
    ]);
  }


  /**
   * Config column in VisitorLog model.
   * @param integer $id
   * @return mixed
   * @throws NotFoundHttpException if the model cannot be found
   */
  public function actionColumns()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('VisitorLogView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    $model = new VisitorLog();
    $searchModel = new VisitorLogSearch();

    $request = Yii::$app->request;

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    Yii::$app->response->format = Response::FORMAT_JSON;

    if ($request->post('column')) {
      $col = $request->post('column');

      if (Yii::$app->user->isGuest) {
        Yii::$app->session->set($this->col_cash, $col);
      } else {
        $user = Yii::$app->getUser()->getIdentity();
        $user->setActiveColumn($this->col_cash, $col);
      }

      return [
          'forceClose' => 'true',
          'forceReload' => '#crud-datatable-pjax',
          'content' => Yii::$app->view->closeModal(),
      ];
    }
    $actions = "";
    $file = $this->col_cash == 'tips_columns' ? '_columns_tips.php' : '_columns.php';

    $columns = include(__DIR__ . '/../views/admin/' . $file);
    if (Yii::$app->user->isGuest) {
      $sel_column = Yii::$app->session->get($this->col_cash, false);
    } else {
      $user = Yii::$app->getUser()->getIdentity();
      $sel_column = $user->getActiveColumn($this->col_cash);
    }
    if (!$sel_column) {
      $sel_column = $this->def_sel_column;
    }
    foreach ($columns as $k => $column) {
      $column_name = !is_array($column) ? $column : (isset($column['attribute']) ? $column['attribute'] : false);
      if (!$column_name) {
        unset($columns[$k]);
      } else {
        $columns[$k] = $column_name;
      }
    }

    return [
        'title' => Yii::t('app', 'Change visible columns in VisitorLog table'),
        'content' => $this->renderAjax('columns', [
            'sel_column' => $sel_column,
            'columns' => $columns,
            'model' => $model,
            'isAjax' => true
        ]),
        'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
            Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"])
    ];
  }

  /**
   * Creates a new VisitorLog model.
   * For ajax request will return json object
   * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
   * @return mixed
   */
  public function actionCreate()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('VisitorLogCreate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    $request = Yii::$app->request;
    $model = new VisitorLog();

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    /*
    *   Process for ajax request
    */
    Yii::$app->response->format = Response::FORMAT_JSON;
    if ($request->isGet) {
      return [
          'title' => "Yii::t('app', 'Create new VisitorLog')",
          'content' => $this->renderAjax('create', [
              'model' => $model,
              'isAjax' => true
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"])
      ];
    } else if ($model->load($request->post()) && $model->save()) {
      return $this->returnBlank(
          [
              'forceReload' => '#crud-datatable-pjax',
              'title' => Yii::t('app', 'Create new VisitorLog'),
          ],
          Yii::t('app', 'VisitorLog Created successfully')
      );
    } else {
      return [
          'title' => "Yii::t('app', 'Create new VisitorLog')",
          'content' => $this->renderAjax('create', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"])

      ];
    }
  }

  /**
   * Updates an existing VisitorLog model.
   * For ajax request will return json object
   * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
   * @param integer $id
   * @return mixed
   */
  public function actionUpdate($id)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('VisitorLogUpdate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $request = Yii::$app->request;
    $visit = $this->findModel($id);

    $model = new VisitorLogEditForm($visit);

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    /*
    *   Process for ajax request
    */
    $title = Yii::t('app', 'Editing of data visit');

    Yii::$app->response->format = Response::FORMAT_JSON;
    if ($request->isGet) {
      return [
          'title' => $title,
          'content' => $this->renderAjax('update', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"])
      ];
    } else if ($model->load($request->post()) && $model->save()) {
      return $this->returnBlank(
          [
              'forceReload' => '#crud-datatable-pjax',
              'title' => $title,
          ],
          Yii::t('app', 'Visit updated successfully')
      );
    } else {
      return [
          'title' => $title,
          'content' => $this->renderAjax('update', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"])
      ];
    }
  }

  public function actionResume($id)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('VisitorLogUpdate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $request = Yii::$app->request;
    $visit = $this->findModel($id);

    if (!$request->isAjax || !$visit || !$visit->finish_time) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    Yii::$app->response->format = Response::FORMAT_JSON;

    $pause = time() - strtotime($visit->finish_time);
    $visit->pause = ($visit->pause ? $visit->pause : 0) + $pause;
    $visit->finish_time = null;
    $visit->pay_state = 0;
    $visit->pay_man = null;
    $visit->save();

    $visits = VisitorLog::find()
        ->where(['pay_man' => $visit->id])
        ->all();
    foreach ($visits as $visit) {
      $visit->pay_man = null;
      $visit->save();
    }

    Yii::$app->session->addFlash('success', Yii::t('app', 'The visit was successfully restored.'));

    return [
        'forceReload' => '#crud-datatable-pjax',
        'forceClose' => true,
        'content' => $this->view->getFlash(),
    ];
  }

  public function actionUpdateCertificate($id)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('VisitorLogUpdate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $request = Yii::$app->request;
    $model = $this->findModel($id);

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    /*
    *   Process for ajax request
    */
    $title = Yii::t('app', 'Update Visitor Log Certificate: {id}', [
        'id' => '' . $model->id,
    ]);
    Yii::$app->response->format = Response::FORMAT_JSON;

    if ($model->certificate_type != Certificate::TYPE_NONE) {
      return [
          'title' => $title,
          'content' => Yii::t('app', "Certificate has been already added"),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]),
      ];
    }

    if ($request->isGet) {
      return [
          'title' => $title,
          'content' => $this->renderAjax('../default/edit_certificate', [
              'model' => $model,
              'visit' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button('Close', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button('Save', ['class' => 'btn btn-primary', 'type' => "submit"])
      ];
    } else if ($model->load($request->post()) && $model->calcCost() && $model->save()) {
      return $this->returnBlank(
          [
              'forceReload' => '#crud-datatable-pjax',
              'title' => $title,
          ],
          Yii::t('app', 'Visit updated successfully')
      );
    } else {
      return [
          'title' => $title,
          'content' => $this->renderAjax('../default/edit_certificate', [
              'model' => $model,
              'visit' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button('Close', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button('Save', ['class' => 'btn btn-primary', 'type' => "submit"])
      ];
    }
  }

  public function actionDeleteCertificate($id)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('VisitorLogUpdate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $request = Yii::$app->request;
    $model = $this->findModel($id);

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    /*
    *   Process for ajax request
    */
    $title = Yii::t('app', 'Update Visitor Log Certificate: {id}', [
        'id' => '' . $model->id,
    ]);
    Yii::$app->response->format = Response::FORMAT_JSON;

    if ($model->certificate_type === Certificate::TYPE_NONE) {
      return [
          'title' => $title,
          'content' => Yii::t('app', "Certificate is absent"),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]),
      ];
    }

    $model->certificate_type = Certificate::TYPE_NONE;

    if ($model->calcCost() && $model->save()) {
      return [
          'forceReload' => '#crud-datatable-pjax',
          'title' => $title,
          'content' => "<script>$('.modal-header .close').click()</script>",
          'footer' => Html::button('Close', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::a('Edit', ['update', 'id' => $id], ['class' => 'btn btn-primary', 'role' => 'modal-remote'])
      ];
    } else {
      return [
          'title' => $title,
          'content' => $this->renderAjax('../default/edit_certificate', [
              'model' => $model,
              'visit' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button('Close', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button('Save', ['class' => 'btn btn-primary', 'type' => "submit"])
      ];
    }
  }

  public function actionCheckSendMail($id)
  {
    $request = Yii::$app->request;
    $model = $this->findModel($id);

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    /*
    *   Process for ajax request
    */
    $title = Yii::t('app', 'Mail sended');
    Yii::$app->response->format = Response::FORMAT_JSON;

    Yii::$app->session->addFlash('success', Yii::t('app', 'Check sended to mail'));
    Yii::$app->queue->delay(Yii::$app->params['checkMailSendDelay'])->push(new CheckMailSendJob(['visit_id' => $model->id]));

    return [
        'forceReload' => '#crud-datatable-pjax',
        'title' => $title,
        'content' => $title,
        'footer' => Html::button(Yii::t('app', 'OK'), ['class' => 'btn btn-primary', 'data-dismiss' => "modal"]),
    ];
  }

  /**
   * Delete an existing Tariffs model.
   * For ajax request will return json object
   * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   */
  public function actionDelete($id)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('VisitorLogDelete')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    $request = Yii::$app->request;
    $this->findModel($id)->delete();

    if ($request->isAjax) {
      /*
      *   Process for ajax request
      */
      Yii::$app->response->format = Response::FORMAT_JSON;
      return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
    } else {
      /*
      *   Process for non-ajax request
      */
      return $this->redirect(['index']);
    }
  }

  /**
   * Delete multiple existing Tariffs model.
   * For ajax request will return json object
   * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   */
  public function actionBulkDelete()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('VisitorLogDelete')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    $request = Yii::$app->request;
    $pks = explode(',', $request->post('pks')); // Array or selected records primary keys
    foreach ($pks as $pk) {
      $model = $this->findModel($pk);
      $model->delete();
    }

    if ($request->isAjax) {
      /*
      *   Process for ajax request
      */
      Yii::$app->response->format = Response::FORMAT_JSON;
      return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
    } else {
      /*
      *   Process for non-ajax request
      */
      return $this->redirect(['index']);
    }

  }

  /**
   * Finds the VisitorLog model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return VisitorLog the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id)
  {
    if (($model = VisitorLog::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException(Yii::t('app', 'Page does not exist'));
    }
  }
}
