<?php

namespace frontend\modules\visits\controllers;

use console\jobs\CheckMailSendJob;
use frontend\components\Controller;
use frontend\modules\cafe\components\Cafe;
use frontend\modules\certificate\models\Certificate;
use frontend\modules\polls\models\Polls;
use frontend\modules\shop\models\ShopSale;
use frontend\modules\templates\models\Template;
use frontend\modules\visits\models\StartVisit;
use frontend\modules\visits\models\VisitorEditForm;
use frontend\modules\visits\models\VisitorLog;
use kartik\widgets\Typeahead;
use Yii;
use yii\base\Exception;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * Default controller for the `visits` module
 */
class DefaultController extends Controller
{
  private $from_main = false;

  public function beforeAction($action)
  {
    $js = Yii::getAlias('@frontend/modules/visits/views/default/test_page_form.twig');
    $js = file_get_contents($js);
    \Yii::$app->view->registerJs($js);

    $request = Yii::$app->request;
    $host = $request->headers->get('host');
    $referer = $request->headers->get('referer');

    if ($host && $referer) {
      $page = explode($host, $referer);
      if (count($page) < 2) {
        $this->from_main = true;
      } else {
        $this->from_main = (trim($page[1], '/') == "");
      }
    } else {
      $this->from_main = true;
    }

    if ($this->from_main == false) {
      if ($request->post('isMain') || $request->get('isMain')) {
        $this->from_main = true;
      }
    }

    if (!YII_DEBUG) {
      if (Yii::$app->user->isGuest || !Yii::$app->cafe->can("startVisit")) {
        throw new ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      }

      // List of NOT AJAX request allowed actions in this controller
      $not_ajax_allowed_actions = [
          'print_check',
      ];

      $request = Yii::$app->request;
      if (!$request->isAjax && !in_array($action->id, $not_ajax_allowed_actions)) {
        throw new ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      }
    }
    Yii::$app->response->format = Response::FORMAT_JSON;

    return parent::beforeAction($action); // TODO: Change the autogenerated stub
  }

  public function actionView($id)
  {
    /** @var $model VisitorLog */
    $model = VisitorLog::find()->where(['id' => $id])->one();

    if (!$model) {
      return [
          'title' => Yii::t('app', "View visit error"),
          'content' => Yii::t('app', "Visit not found"),
          'footer' => Html::button(Yii::t('app', 'Close'), [
              'class' => 'btn btn-default pull-left',
              'data-dismiss' => "modal",
          ]),
      ];
    }

    $button = Html::button(Yii::t('app', 'Close'), [
        'class' => 'btn btn-default pull-left',
        'data-dismiss' => "modal",
    ]);

    $button_dop_line = '';
    if (empty($model->finish_time)) {
      if ($model->cost !== false) {

        if (Yii::$app->user->can('VisitorUpdate') && 
		//Yii::$app->cafe->can('UpdateVisitorOnVisit') &&
            $model->type != VisitorLog::TYPE_ANONYMOUS && $model->visitor) {
          $button_dop_line .= Html::a('<i class="fa fa-pencil"></i> ' . Yii::t('app', 'Edit user'), ['/visits/visitor-update', 'id' => $model->visitor_id, 'backToVisitViewId' => $model->id], [
              'class' => 'btn btn-xs btn-science-blue-border',
              "role" => "modal-remote",
          ]);
        }

        if (Yii::$app->cafe->can('unite')) {
          $button_dop_line .= Html::button('<i class="fa fa-chain"></i> ' . Yii::t('app', 'Unite'), [
              'class' => 'btn btn-xs btn-science-blue-border',
              "role" => "visit-unite",
          ]);
        }

        if (Yii::$app->user->can('VisitorUpdate') && Yii::$app->cafe->can('ChangeVisitorOnVisit')) {
          $button_dop_line .= Html::a('<i class="fa fa-exchange"></i> ' . Yii::t('app', 'Change user'), ['/visits/start', 'id' => $model->id, 'action' => VisitorLog::ACTION_CHANGE_USER], [
              'class' => 'btn btn-xs btn-science-blue-border',
              "role" => "modal-remote",
          ]);
        }

        if (Yii::$app->cafe->can('certificate') && $model->certificate_type == Certificate::TYPE_NONE) {
          $button .= Html::a(Yii::t('app', 'Add Certificate'), ['/visits/update-certificate', 'id' => $model->id], [
              'class' => 'btn btn-warning',
              "role" => "modal-remote",
          ]);
        }

        if ($model->pause_start) {
          $button .= Html::a(Yii::t('app', 'Resume'), ['/visits/pause', 'id' => $model->id, 'resume' => true], [
              'class' => 'btn bg-blue fg-white',
              "role" => "modal-remote",
          ]);
        } else {
          $button .= Html::a(Yii::t('app', 'Pause'), ['/visits/pause', 'id' => $model->id], [
              'class' => 'btn bg-blue fg-white',
              "role" => "modal-remote",
          ]);
        }

        $button .= Html::a(Yii::t('app', 'Stop'), ['/visits/stop', 'id' => $model->id], [
            'class' => 'btn btn-success',
            "role" => "modal-remote",
        ]);
      }
    }
    $model->endPause(true);

    $footer = "";
    if (strlen($button_dop_line) > 0) {
      $footer .= Html::tag('div', $button_dop_line, ['class' => 'wrap_button_dop_line']);
    }
    if (strlen($button) > 0) {
      $footer .= Html::tag('div', $button, ['class' => 'class']);
    }

    return [
        'title' => '<span class="fa fa-user antagon-color-main"></span> ' . Yii::t('app', "Estimation visit"),
        'content' => $this->renderAjax('view', [
            'model' => $model,
            'cafe' => Yii::$app->cafe,
        ]),
        'footer' => $footer,
    ];
  }

  public function actionViewUnite()
  {
    $request = Yii::$app->request;

    $visit_ids = $request->post('visit_ids');

    if ($visit_ids === null) {
      $visit_ids = $request->getRawBody();
    }

    $visit_ids = explode(',', $visit_ids);

    /** @var $models VisitorLog[] */
    $models = VisitorLog::find()->where(['id' => $visit_ids])->all();

    if (!$models) {
      return [
          'title' => Yii::t('app', "View visit error"),
          'content' => Yii::t('app', "Visit not found"),
          'footer' => Html::button(Yii::t('app', 'Close'), [
              'class' => 'btn btn-default pull-left',
              'data-dismiss' => "modal",
          ]),
      ];
    }

    $visit_ids = ArrayHelper::getColumn($models, 'id');

    $button = Html::button(Yii::t('app', 'Close'), [
        'class' => 'btn btn-default pull-left',
        'data-dismiss' => "modal",
    ]);

    $button .= Html::button(Yii::t('app', 'Stop'), [
        'class' => 'btn btn-success',
        'type' => "submit",
    ]);

    $model = new VisitorLog();
    VisitorLog::populateUniteData($model, $models);

    return [
        'title' => '<span class="fa fa-user antagon-color-main"></span> ' . Yii::t('app', "Estimation visit"),
        'content' => $this->renderAjax('view_unite', [
            'visit_ids' => $visit_ids,
            'models' => $models,
            'model' => $model,
            'cafe' => Yii::$app->cafe,
        ]),
        'footer' => $button,
        'header' => "1231",
    ];
  }

  public function actionStart($id = null, $action = null, $ungroup_id = null, $ungroup_type = null, $method = null, $visitor_id = null)
  {
    $request = Yii::$app->request;

    /* @var $cafe Cafe */
    $cafe = Yii::$app->cafe;

    $model = null;
    if ($visitor_id) {
      $model = StartVisit::find()->where(['id' => $visitor_id])->one();
      if ($model && $model->id > 0) {
        $model->type = VisitorLog::TYPE_REGULAR;
      } else {
        $model = null;
      }
    }

    if (!$model) {
      $model = new StartVisit();
    }


    // Visitor change during Visit
    if (
        Yii::$app->user->can('VisitorUpdate') && Yii::$app->cafe->can('ChangeVisitorOnVisit') &&
        $id !== null && $action == VisitorLog::ACTION_CHANGE_USER
    ) {
      $visits_model = VisitorLog::find()->where(['id' => $id])->one();
    } else {
      $visits_model = new VisitorLog();
    }

    if ($method == 'back') {
      if ($request->post('visit_data')) {
        try {
          $visit_data = json_decode($request->post('visit_data'), true);
          $visits_model->load(['VisitorLog' => $visit_data]);
        } catch (Exception $e) {
        }
      }
    }

    $products = false;
    if ($request->post('products')) {
      $products = json_encode($request->post('products'));
    }

    // Visitors un-grouping
    if ($ungroup_id !== null && $ungroup_type !== null) {
      $ungroupVisit = VisitorLog::find()->andWhere([
          'id' => $ungroup_id,
          'finish_time' => null,
      ])->one();

      if ($ungroupVisit === null) {
        throw new NotFoundHttpException(Yii::t('app', 'Visit not found'));
      }

      if ($ungroup_type == VisitorLog::UNGROUP_TYPE_CHILD) {
	    Yii::$app->session->addFlash('warning', Yii::t('app', 'You are going to leave child alone'));
      }

      $visits_model->setupUngroup($ungroupVisit, $ungroup_type);
    }

    $type_list = VisitorLog::typeList();
    // Cannot start GROUP visit directly
    unset($type_list[VisitorLog::TYPE_GROUP]);

    // We must load everything before validation - to not loose it further
    $modelLoaded = $model->load($request->post());
    $visitLoaded = $visits_model->load($request->post());

    if ($modelLoaded && $model->validate()) {
      $no_errors = true;

      $personsCountWithVisit = $cafe->getCurrentPersonsCount() + 1;

      if ($visitLoaded) {
        if (!$visits_model->validate()) {
          $no_errors = false;
        } else {
          $personsCountWithVisit += $visits_model->guest_m;
          $personsCountWithVisit += $visits_model->guest_chi;
        }
      }

      // Check Cafe max persons limit
      if ($cafe->can('personsLimit') && $personsCountWithVisit > $cafe->getMaxPersonsCount()) {
        Yii::$app->session->addFlash('error', Yii::t('app', 'Cafe reached max persons limit'));
      }

      if ($no_errors) {
        if ($model->type == VisitorLog::TYPE_REGULAR) {
          $model = StartVisit::find()->where(['id' => $model->id])->one();
          $model->load($request->post());
        }

        if ($model->type == VisitorLog::TYPE_NEW) {
          $model->id = null;
        }

        if (
            count($model->errors) == 0 &&
            ($model->type == VisitorLog::TYPE_ANONYMOUS || $model->save())
        ) {
          if ($model->type != VisitorLog::TYPE_ANONYMOUS) {
            $visits_model->visitor_id = $model->id;
          }

          $transaction = Yii::$app->getDb()->beginTransaction();
          try {
            $visits_model->type = $model->type;
            $visits_model->user_id = Yii::$app->user->id;

            if ($visits_model->getIsUngrouping()) {
              $visits_model->add_time = $visits_model->ungroup_model->add_time;
              $visits_model->pause_start = $visits_model->ungroup_model->pause_start;
              $visits_model->pause = $visits_model->ungroup_model->pause;

              $visits_model->applyUngroup();
            } else {
              if (empty($visits_model->add_time)) { //при смени юзера сбрасывало время
                $visits_model->add_time = date("Y-m-d H:i:s");
              }
            }

            $all_saved = $visits_model->save();

            if ($visits_model->getIsUngrouping()) {
              $all_saved = ($all_saved && $visits_model->ungroup_model->save());
            }

            if ($all_saved) {
              $transaction->commit();

              if ($request->post('products')) {
                try {
                  $products = json_decode($request->post('products'), true);
                  ShopSale::cart($visits_model->id, $products);
                } catch (Exception $e) {
                }
              }
              Yii::$app->session->addFlash('success', Yii::t('app', 'New visitor added to cafe'));
              Yii::$app->session->addFlash('polls', ['visitor_id' => $visits_model->visitor_id, 'mode' => Polls::EVENT_START_VISIT]);
              return [
                  'forceClose' => 'true',
                  'content' => Yii::$app->view->closeModal(),
                  'footer' => "",
              ];
            }

            $transaction->rollBack();

          } catch (\Exception $e) {
            $transaction->rollBack();
            Yii::$app->session->addFlash('error', Yii::t('app', 'The visit save error.'));
            throw new \Exception(Yii::t('app', 'The visit save error.'));
          }

          if (count($model->errors) == 0 && $model->type == VisitorLog::TYPE_NEW) {
            $model->type = VisitorLog::TYPE_REGULAR;
          }

          Yii::$app->session->addFlash('error', Yii::t('app', 'Error added visitor to cafe'));
        }
      }
    }

    if ($model->type === false) {
      $model->type = key($type_list);
    }

    if (!$model->lg) {
      $model->lg = Yii::$app->user->identity->lg;
    }

    if ($model->type == VisitorLog::TYPE_ANONYMOUS) {
      $model->code = "";
    }

    $buttons = '';
    $buttons .= Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]);

    if ($action == VisitorLog::ACTION_CHANGE_USER) {
      $title = Yii::t('app', "Change visit user");
	    $buttons = Html::a(
		    Yii::t('app', 'Back'),
		    ['/visits/view', 'id' => $id],
		    ['class' => 'btn btn-default pull-left', "role" => "modal-remote"]
	    );
      $buttons .= Html::button(Yii::t('app', 'Change user'), ['class' => 'btn btn-primary', 'type' => "submit"]);
    } else {
      $title = Yii::t('app', "Start new visit");
      $buttons .= Html::button(Yii::t('app', 'Start'), ['class' => 'btn btn-primary', 'type' => "submit"]);
    }

    return [
        'title' => $title,
        'content' => $this->renderAjax('start', [
            'model' => $model,
            'visit' => $visits_model,
            'AJ_classname' => Typeahead::classname(),
            'type_list' => $type_list,
            'products' => $products,
        ]),
        'footer' => $buttons,
    ];
  }

  public function actionStopUnite()
  {
    $request = Yii::$app->request;

    $visit_ids = $request->post('visit_ids');

    $visit_ids = explode(',', $visit_ids);

    $payManId = ArrayHelper::getValue($request->post(), 'VisitorLog.pay_man');

    /** @var $models VisitorLog[] */
    $models = VisitorLog::find()->where(['id' => $visit_ids])->all();
    $payManModel = VisitorLog::find()->where(['id' => $payManId])->one();

    if (!$models || $payManModel === null) {
      return [
          'title' => Yii::t('app', "View visit error"),
          'content' => Yii::t('app', "Visit not found"),
          'footer' => Html::button(Yii::t('app', 'Close'), [
              'class' => 'btn btn-default pull-left',
              'data-dismiss' => "modal",
          ]),
      ];
    }


    $transaction = Yii::$app->getDb()->beginTransaction();
    try {
      foreach ($models as $visit) {
        $visit->endPause();
        $visit->finish_time = date("Y-m-d H:i:s");
        $visit->pay_man = $payManModel->id;

        if (!$visit->save()) {
          throw new \Exception('Visit save error');
        }
      }

      $transaction->commit();
    } catch (\Exception $e) {
      $transaction->rollBack();
      Yii::$app->session->addFlash('error', Yii::t('app', 'The visit stop error.'));
      throw new Exception(Yii::t('app', 'The visit stop error.'));
    }

    Yii::$app->session->addFlash('success', Yii::t('app', 'The visit was successfully completed.'));
    Yii::$app->session->addFlash('polls', ['visitor_id' => $visit->visitor_id, 'mode' => Polls::EVENT_FINISH_VISIT]);

    return $this->actionPay($payManId);
  }

  public function actionPause($id, $resume = false)
  {
    /** @var $model VisitorLog */
    $model = VisitorLog::find()->where(['id' => $id])->one();

    if (!$model) {
      return [
          'title' => Yii::t('app', "View visit error"),
          'content' => Yii::t('app', "Visit not found"),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]),

      ];
    }

    if ($model->finish_time) {
      return [
          'title' => Yii::t('app', "View visit error"),
          'content' => Yii::t('app', "The visit has already been completed"),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]),
      ];
    }

    if ($resume) {
      if ($model->pause_start == 0) {
        return [
            'title' => Yii::t('app', "View visit error"),
            'content' => Yii::t('app', "The visit is not on a pause"),
            'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]),
        ];
      }
      $model->endPause();
    } else {
      if ($model->pause_start > 0) {
        return [
            'title' => Yii::t('app', "View visit error"),
            'content' => Yii::t('app', "The visit is already on a pause"),
            'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]),
        ];
      }
      $model->pause_start = time();
    }
    $model->save();

    Yii::$app->session->addFlash('success', Yii::t('app', $resume ? 'The visit was removed from a pause.' : 'The visit is paused'));
    return [
        'forceClose' => 'true',
        'content' => Yii::$app->view->closeModal(),
        'footer' => "",
    ];

  }

  public function actionStop($id)
  {
    /** @var $model VisitorLog */
    $model = VisitorLog::find()->where(['id' => $id])->one();

    if (!$model) {
      $result = [
          'title' => Yii::t('app', "View visit error"),
          'content' => Yii::t('app', "Visit not found"),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]),
      ];

      if (!$this->from_main) {
        $result['forceReload'] = '#crud-datatable-pjax';
      }

      return $result;
    }

    if ($model->finish_time) {

      $result = [
          'title' => Yii::t('app', "View visit error"),
          'content' => Yii::t('app', "The visit has already been completed."),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]),
      ];

      if (!$this->from_main) {
        $result['forceReload'] = '#crud-datatable-pjax';
      }

      return $result;
    }

    $model->endPause();
    $model->finish_time = date("Y-m-d H:i:s");
    $model->pay_man = null;
    $model->save();

    Yii::$app->session->addFlash('success', Yii::t('app', 'The visit was successfully completed.'));
	Yii::$app->session->addFlash( 'polls', ['visitor_id' => $model->visitor_id, 'mode' => Polls::EVENT_FINISH_VISIT]);


    return $this->actionPay($id);
  }

  public function actionPay($id, $method = false)
  {
    /** @var $model VisitorLog */
    $model = VisitorLog::find()->where(['id' => $id])->one();

    if (!$model) {
      return [
          'title' => Yii::t('app', "View visit error"),
          'content' => Yii::t('app', "Visit not found"),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]),
      ];
    }

    if ($model->pay_state != 0 && !YII_DEBUG) {
      $result = [
          'title' => Yii::t('app', "View visit error"),
          'content' => Yii::t('app', "The visit has already been paid."),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]),
      ];

      if (!$this->from_main) {
        $result['forceReload'] = '#crud-datatable-pjax';
      }

      return $result;
    }

    if ($model->getIsUniteMaster()) {
      VisitorLog::populateUniteData($model, $model->getUniteModels());
    }

    $button = '';//Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]);
    $request = Yii::$app->request;

    $cafe = Yii::$app->cafe;

    if (!$model->getIsUnite() && $method === false && !$model->getIsUniteMaster()) {
      if (Yii::$app->cafe->can('certificate') && $model->certificate_type == Certificate::TYPE_NONE) {
        $button .= Html::a(Yii::t('app', 'Add Certificate'), ['/visits/update-certificate', 'id' => $model->id], [
            'class' => 'btn btn-warning',
            "role" => "modal-remote",
        ]);
      }
    }

    if (!$model->getIsUnite() && $cafe->can('payNOT') && !$model->getIsUniteMaster()) {
      if ($method == VisitorLog::PAY_METHOD_NOT_PAID) {

        $model->pay_state = VisitorLog::PAY_METHOD_NOT_PAID;

        if ($model->load($request->post()) && $model->validate()) {
          //совершаем оплату и идем на следующий шаг
          $model->makePay(VisitorLog::PAY_METHOD_NOT_PAID);
          return $this->actionPrint_check($id);
        }

        $not_pay_button = Html::a(Yii::t('app', 'Back'),
            ['/visits/pay', 'id' => $model->id],
            ['class' => 'btn btn-default pull-left', "role" => "modal-remote"]
        );

        $not_pay_button .= Html::button(
            '<i class="icon-metro-cc-nc"></i>&nbsp;' . Yii::t('app', 'Not Paid'),
            ['class' => 'btn bg-scarlet fg-white', 'type' => "submit"]
        );

        return [
            'title' => Yii::t('app', "Acceptance of payment (NOT PAY)."),
            'content' => $this->renderAjax('not_pay', [
                    'model' => $model,
                    'cafe' => Yii::$app->cafe,
                ]),
            'footer' => $not_pay_button,
            'closeButton' => false,
        ];
      }

      $button .= Html::a(
          '<i class="icon-metro-cc-nc"></i>&nbsp;' . Yii::t('app', 'Not Paid'),
          ['/visits/pay', 'id' => $model->id, 'method' => VisitorLog::PAY_METHOD_NOT_PAID],
          ['class' => 'btn bg-scarlet fg-white', "role" => "modal-remote"]
      );
    }

    if ($cafe->can('payCard')) {
      if ($method == VisitorLog::PAY_METHOD_CARD) {
        //совершаем оплату и идем на следующий шаг
        $model->makePay(VisitorLog::PAY_METHOD_CARD);

        return $this->actionPrint_check($id, $method);
      };
      $button .= Html::a(
          '<i class="fa fa-credit-card"></i>&nbsp;' . Yii::t('app', 'Pay Card'),
          ['/visits/pay', 'id' => $model->id, 'method' => VisitorLog::PAY_METHOD_CARD],
          ['class' => 'btn btn-info fg-white', "role" => "modal-remote"]
      );
    }

    if ($cafe->can('payCash')) {
      if ($method == VisitorLog::PAY_METHOD_CASH) {
        //совершаем оплату и идем на следующий шаг
        $model->makePay(VisitorLog::PAY_METHOD_CASH);

        return $this->actionPrint_check($id, $method);
      };
      $button .= Html::a(
          '<i class="fa fa-money"></i>&nbsp;' . Yii::t('app', 'Pay Cash'),
          ['/visits/pay', 'id' => $model->id, 'method' => VisitorLog::PAY_METHOD_CASH],
          ['class' => 'btn btn-success fg-white', "role" => "modal-remote"]
      );
    }

    $js = '<script>app.unite_disable();</script>';

    $result = [
        'title' => Yii::t('app', "Acceptance of payment."),
        'content' => $this->renderAjax('stop', [
                'model' => $model,
                'cafe' => Yii::$app->cafe,
            ]) . $js ,
        'footer' => $button,
	    'closeButton' => false,
    ];

    if (!$this->from_main) {
      $result['forceReload'] = '#crud-datatable-pjax';
    }

    return $result;
  }

  public function actionPrint_check($id, $method = false)
  {
    /** @var $model VisitorLog */
    $model = VisitorLog::find()->where(['id' => $id])->one();

    if (!$model) {
      return [
          'title' => Yii::t('app', "View visit error"),
          'content' => Yii::t('app', "Visit not found"),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]),
      ];
    }

    $request = Yii::$app->request;

    $cafe = Yii::$app->cafe;

    $unPaidState = ($model->pay_state == VisitorLog::PAY_METHOD_NOT_PAID);

    if ($model->getIsUniteMaster()) {
      VisitorLog::populateUniteData($model, $model->getUniteModels());
    }

    $button = Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]);

    $afterContent = '';

    if ($method == VisitorLog::PAY_METHOD_CASH) {
      $afterContent = $this->renderPartial('_pay_cash_calculator', [
          'model' => $model,
          'cafe' => Yii::$app->cafe,
      ]);
    }

    if ($cafe->can('endVisitMailCheckManual') && $model->canMakeCheck()) {
      if ($method == VisitorLog::CHECK_MAIL) {

        if ($model->canSendMail()) {
          $model->send_mail_status = 1;
          Yii::$app->session->addFlash('success', Yii::t('app', 'Check sended to mail'));
          Yii::$app->queue->delay(Yii::$app->params['checkMailSendDelay'])->push(new CheckMailSendJob(['visit_id' => $model->id]));

        } else {
          $model->send_mail_status = 2;
          $model->scenario = VisitorLog::SCENARIO_ANONYMOUS_MAIL_SET;

          if ($model->load($request->post()) && $model->validate()) {
            //сохраняем и идем на следующий шаг
            $model->save(false);
            $model->send_mail_status = 1;
            return $this->actionPrint_check($id, VisitorLog::CHECK_MAIL);
          }

          $no_email_button = Html::button(
              Yii::t('app', 'Save and Send'),
              ['class' => 'btn btn-success', 'type' => "submit"]
          );

          $no_email_button .= Html::a(Yii::t('app', 'Back'),
              ['/visits/print_check', 'id' => $model->id],
              ['class' => 'btn btn-default pull-left', "role" => "modal-remote"]
          );

          $result = [
              'title' => Yii::t('app', "Email set"),
              'content' => $this->renderAjax('check_mail_email_set', [
                      'model' => $model,
                      'cafe' => Yii::$app->cafe,
                  ]),
              'footer' => $no_email_button,
              'closeButton' => false,
          ];

          if (!$this->from_main) {
            $result['forceReload'] = '#crud-datatable-pjax';
          }

          return $result;
        }
      }

      if (!$unPaidState) {
        $buttonMailParams = ['class' => 'btn btn-success', "role" => "modal-remote"];
        if ($method == VisitorLog::CHECK_MAIL) {
          // Check sended
          $buttonMailParams['disabled'] = 'disabled';
          $model->send_mail_status = 1;
        }
        $button .= Html::a(
            '<i class="fa fa-envelope-o"></i> ' . Yii::t('app', 'Send mail'),
            ['/visits/print_check', 'id' => $model->id, 'method' => VisitorLog::CHECK_MAIL],
            $buttonMailParams
        );
      }
    }

    $js = '';
    if (!$unPaidState) {
      if (
          ($cafe->can('endVisitPrintCheckManual') || $cafe->can('endVisitPrintCheckAuto')) &&
          $method == VisitorLog::CHECK_PRINT &&
          $model->canMakeCheck()
      ) {
        Yii::$app->response->format = Response::FORMAT_RAW;
        /* @var $template Template */
        $template = $cafe->get()->findTemplate(Template::TYPE_CHECK_PRINT);
        $language = 'en-EN';
        if ($model->visitor) {
              $language = $model->visitor->lg;
        }
        return $template->renderTemplate($model->getCheckData(), $language, $cafe->id);
      }

      if ($cafe->can('endVisitPrintCheckManual') && $model->canMakeCheck()) {
        $button .= Html::button(
            '<i class="fa fa-print"></i> ' . Yii::t('app', 'Print check'),
            ['class' => 'btn btn-info', "onClick" => 'app.print_check(' . $model->id . '); return false;']
        );
      }

      if (
          ($method == VisitorLog::PAY_METHOD_CASH || $method == VisitorLog::PAY_METHOD_CARD) &&
          $cafe->can('endVisitPrintCheckAuto') &&
          $model->canMakeCheck()
      ) {
        $js = '<script>app.print_check(' . $model->id . ');</script>';
      }
    }

    $result = [
        'title' => Yii::t('app', "Check visit"),
        'content' => $this->renderAjax('stop', [
                'model' => $model,
                'cafe' => Yii::$app->cafe,
            ]) . $afterContent . $js,
        'footer' => $button,
    ];

    if (!$this->from_main) {
      $result['forceReload'] = '#crud-datatable-pjax';
    }

    return $result;
  }

  public function actionUpdateCertificate($id)
  {
    /** @var $model VisitorLog */
    $model = VisitorLog::find()->where(['id' => $id])->one();

    if (!$model) {
      return [
          'title' => Yii::t('app', "View visit error"),
          'content' => Yii::t('app', "Visit not found"),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]),
      ];
    }

    $request = Yii::$app->request;

    if ($model->certificate_type != Certificate::TYPE_NONE) {
      return [
          'title' => Yii::t('app', "Visit Certificate Add"),
          'content' => Yii::t('app', "Certificate has been already added"),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]),
      ];
    }

    if (!$model->finish_time) {
      $button = Html::button(Yii::t('app', 'Close'), [
          'class' => 'btn btn-default pull-left',
          'data-dismiss' => "modal",
      ]);
    } else {
      $button = Html::a(Yii::t('app', 'Back'),
          ['/visits/pay', 'id' => $model->id],
          ['class' => 'btn btn-default pull-left', "role" => "modal-remote"]
      );
    }

    $button .= Html::button(Yii::t('app', 'Save'), [
        'class' => 'btn btn-success',
        'type' => "submit",
    ]);

    $js = '<script>$(\'.modal-body\').find(\'input,select\').not("[type=radio]").on(\'change\',userAA);</script>';

    if ($model->load($request->post()) && $model->validate()) {
      // Force cost recalculate
      $model->calcCost();
      if ($model->save()) {
        Yii::$app->session->addFlash('success', Yii::t('app', 'Certificate added'));
        if ($model->finish_time) {
          // Certificate was added after visit STOP - back to PAY
          return $this->actionPay($model->id);
        } else {
          // Certificate was added during visit - back to VIEW
          return $this->actionView($model->id);
        }
      }
    }

    return [
        'title' => Yii::t('app', "Visit Certificate Add"),
        'content' => $this->renderAjax('edit_certificate', [
                'model' => $model,
                'visit' => $model,
                'cafe' => Yii::$app->cafe,
            ]) . $js,
        'footer' => $button,
        'closeButton' => false,
    ];
  }

  /**
   * Current Visitor edit action
   *
   */
  public function actionVisitorUpdate($id, $backToVisitViewId = null)
  {
    //if (Yii::$app->user->isGuest || !Yii::$app->user->can('VisitorUpdate') || !Yii::$app->cafe->can('UpdateVisitorOnVisit')) {
	  if (Yii::$app->user->isGuest || !Yii::$app->user->can('VisitorUpdate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    $request = Yii::$app->request;

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    $model = VisitorEditForm::findOne($id);

    if ($model === null) {
      throw new NotFoundHttpException(Yii::t('app', 'Page does not exist'));
    }

    /*
    *   Process for ajax request
    */
    $title = Yii::t('app', 'Update Visitor: {f_name} {l_name}', $model->toArray());
    Yii::$app->response->format = Response::FORMAT_JSON;
    if ($request->isGet) {

	    $buttons = '';

	    if ($backToVisitViewId) {
		    $buttons .= Html::a(
			    Yii::t('app', 'Back'),
			    ['/visits/view', 'id' => $backToVisitViewId],
			    ['class' => 'btn btn-default pull-left', "role" => "modal-remote"]
		    );
	    } else {
		    $buttons .= Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]);
	    }

	    $buttons .= Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"]);

      return [
          'title' => $title,
          'content' => $this->renderAjax('_visitor_edit_form', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => $buttons,
      ];
    } else if ($model->load($request->post()) && $model->save()) {
      if ($backToVisitViewId) {
        $visitViewUrl = Url::toRoute(['/visits/view', 'id' => $backToVisitViewId]);
        return [
            'content' => Yii::$app->view->openModal($visitViewUrl),
        ];
      }

      return [
          'title' => $title,
          'forceClose' => 'true',
          'content' => Yii::$app->view->closeModal()
      ];
    } else {
      return [
          'title' => $title,
          'content' => $this->renderAjax('_visitor_edit_form', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"]),
      ];
    }
  }
}

