<?php

namespace frontend\modules\users\controllers;

use frontend\components\Controller;
use frontend\modules\users\models\AdminSession;
use frontend\modules\users\models\UserLog;
use Yii;
use yii\helpers\Html;
use yii\web\Response;

/**
 * AdminController implements the CRUD actions for Users model.
 */
class DefaultController extends Controller
{
  public function beforeAction($action)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->cafe->id || !Yii::$app->cafe->can('adminLog')) {
      throw new ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    return parent::beforeAction($action); // TODO: Change the autogenerated stub
  }

  public function actionStart($user_id = null)
  {
    $request = Yii::$app->request;
    $cafe = Yii::$app->cafe;
    if (!$cafe->can('adminLog') || Yii::$app->user->isGuest || !$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    Yii::$app->response->format = Response::FORMAT_JSON;

    $model = new AdminSession();

    if ($user_id !== null) {
      $model->user_id = $user_id;
    }

    $model->scenario = AdminSession::SCENARIO_START;

    if ($model->load($request->post()) && $model->validate()) {

      UserLog::sessionStart($cafe->id, $model->user_id);

      Yii::$app->session->addFlash('success', Yii::t('app', 'New user session added to cafe'));
      return [
          'forceClose' => 'true',
          'content' => Yii::$app->view->closeModal(),
          'footer' => "",
      ];
    };


    return [
        'title' =>
            '<span class="fa fa-user-secret antagon-color-main"></span> ' .
            Yii::t('app', 'Start admin session'),
        'content' => $this->renderAjax('start', [
            'model' => $model,
            'cafe' => Yii::$app->cafe,
        ]),
        'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
            Html::button(Yii::t('app', 'Start'), ['class' => 'btn btn-primary', 'type' => "submit"])
    ];
  }

  public function actionView($id)
  {

    return "23";
  }
}