<?php

namespace frontend\modules\timetable\controllers;

use frontend\components\Controller;
use frontend\modules\timetable\models\UserTimetable;
use frontend\modules\timetable\models\UserTimetableSearch;
use Yii;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * AdminController implements the CRUD actions for UserTimetable model.
 */
class AdminController extends Controller
{

  private $def_sel_column = [
      'id',
      'user_id',
      'start',
      'end',
      'cafe_id',
  ];

  public function beforeAction($action)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->cafe->can('Timetable')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    return parent::beforeAction($action); // TODO: Change the autogenerated stub
  }

  /**
   * Lists all UserTimetable models.
   * @return mixed
   */
  public function actionIndex()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('UserTimetableView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    if (Yii::$app->user->can('UserTimetableUpdate')) {
      $users = Yii::$app->cafe->getCafeUsersList();
      Yii::$app->view->registerJs(
          'resources=' . json_encode($users) . ';
          make_time_table_drag_list(resources);');
    };

    return $this->render('index', [
        'title' => Yii::t('app', 'User Timetables'),
    ]);
  }

  public function actionCreate()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('UserTimetableUpdate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    $request = Yii::$app->request;
    if (!$request->isAjax || !$request->isPost) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    Yii::$app->response->format = Response::FORMAT_JSON;

    $event = new UserTimetable();
    $event->cafe_id = Yii::$app->cafe->id;
    $event->user_id = $request->post('user');
    $event->start = date('Y-m-d H:i:s', strtotime($request->post('start')));
    if (empty($request->post('end'))) {
      $event->end = date('Y-m-d H:i:s', strtotime($request->post('start')) + 60 * 60 * 4);
    } else {
      $event->end = date('Y-m-d H:i:s', strtotime($request->post('end')));
    }
    $event->save();

    $event->event_id = $request->post('id');
    return $event->event;
  }

  public function actionUpdate($id)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('UserTimetableUpdate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $request = Yii::$app->request;
    $event = $this->findModel($id);

    if (!$request->isAjax || !$request->isPost || !$event) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    Yii::$app->response->format = Response::FORMAT_JSON;
    $event->start = date('Y-m-d H:i:s', strtotime($request->post('start')));
    if (empty($request->post('end'))) {
      $event->end = date('Y-m-d H:i:s', strtotime($request->post('start')) + 60 * 60 * 4);
    } else {
      $event->end = date('Y-m-d H:i:s', strtotime($request->post('end')));
    }
    $event->save();

    return $event->event;
  }

  /**
   * Delete an existing UserTimetable model.
   * For ajax request will return json object
   * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   */
  public function actionDelete($id)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('UserTimetableUpdate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $request = Yii::$app->request;
    $model = $this->findModel($id);

    if (!$request->isAjax || !$request->isPost || !$model) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    Yii::$app->response->format = Response::FORMAT_JSON;

    return $model->delete();
  }

  /**
   * Finds the UserTimetable model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return UserTimetable the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id)
  {
    if (($model = UserTimetable::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException(Yii::t('app', 'Page does not exist'));
    }
  }

  public function actionJsoncalendar($start = NULL, $end = NULL, $_ = NULL)
  {

    $request = Yii::$app->request;
    /*if (Yii::$app->user->isGuest || !Yii::$app->user->can('UserTimetableView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }*/

    Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

    $times = UserTimetable::find()
        ->andWhere([
            'and',
            ['<=', 'DATE(start)', $end],
            ['>=', 'DATE(end)', $start],
            ['cafe_id' => Yii::$app->cafe->id]
        ])->all();
    $events = array();

    foreach ($times AS $time) {
      $events[] = $time->event;
    }

    return $events;
  }
}
