<?php

namespace frontend\modules\tariffs\models;

use frontend\modules\cafe\models\Cafe;
use Yii;
use yii\validators\NumberValidator;
use yii\validators\RequiredValidator;

/**
 * This is the model class for table "tariffs".
 *
 * @property int $id
 * @property int $cafe_id
 * @property double $min_sum
 * @property double $max_sum
 * @property double $first_hour
 * @property array $data
 * @property double $start_visit
 * @property int $active
 *
 * @property Cafe $cafe
 */
class Tariffs extends \common\components\ActiveRecord
{
  const TYPE_CAFE_ORIENTED = 1;
  const TYPE_REGIONAL = 2;

  const DATA_HOURS_KEY = 'hours';

  public $_hours = []; // configurator

  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return 'tariffs';
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
        [['min_sum', 'max_sum', 'first_hour'], 'required'],
        [['cafe_id', 'active', 'type_id', 'franchisee_id'], 'integer'],
        [['min_sum', 'max_sum', 'first_hour', 'start_visit'], 'number'],
        [['cafe_id'], 'exist', 'skipOnError' => true, 'targetClass' => Cafe::className(), 'targetAttribute' => ['cafe_id' => 'id']],
        ['data', 'safe'],

        ['_hours', 'validateHoursData'],
    ];
  }

  public function validateHoursData($attribute)
  {
    $requiredValidator = new RequiredValidator();

    $integerValidator = new NumberValidator([
        'integerOnly' => true,
        'min' => 2,
    ]);

    $numberValidator = new NumberValidator([
        'min' => 0,
        'max' => 100,
    ]);

    $requiredAttributes = [
        'hour',
    ];

    $integerAttributes = [
        'hour',
    ];

    $priceAttributes = [
        'price',
    ];

    foreach ($requiredAttributes as $requiredAttribute) {
      foreach ($this->$attribute as $index => $row) {
        $error = null;
        $requiredValidator->validate($row[$requiredAttribute], $error);
        if (!empty($error)) {
          $key = $attribute . '[' . $index . '][' . $requiredAttribute . ']';
          $this->addError($key, $error);
        }
      }
    }

    foreach ($integerAttributes as $integerAttribute) {
      foreach ($this->$attribute as $index => $row) {
        $error = null;
        $integerValidator->validate($row[$integerAttribute], $error);
        if (!empty($error)) {
          $key = $attribute . '[' . $index . '][' . $integerAttribute . ']';
          $this->addError($key, $error);
        }
      }
    }

    foreach ($priceAttributes as $priceAttribute) {
      foreach ($this->$attribute as $index => $row) {
        $error = null;
        $numberValidator->validate($row[$priceAttribute], $error);
        if (!empty($error)) {
          $key = $attribute . '[' . $index . '][' . $priceAttribute . ']';
          $this->addError($key, $error);
        }
      }
    }
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
        'id' => Yii::t('app', 'ID'),
        'type_id' => Yii::t('app', 'Type'),
        'cafe_id' => Yii::t('app', 'Cafe'),
        'franchisee_id' => Yii::t('app', 'Franchisee'),
        'params_id' => Yii::t('app', 'Cafe Params'),
        'min_sum' => Yii::t('app', 'Min Sum'),
        'max_sum' => Yii::t('app', 'Max Sum'),
        'first_hour' => Yii::t('app', 'First Hour'),
        'data' => Yii::t('app', 'Data'),
        'start_visit' => Yii::t('app', 'Start Visit'),
        'active' => Yii::t('app', 'Active'),
    ];
  }

  public function afterFind()
  {
    if (isset($this->data[self::DATA_HOURS_KEY])) {
      $this->_hours = $this->data[self::DATA_HOURS_KEY];
    }

    parent::afterFind(); // TODO: Change the autogenerated stub
  }

  public function beforeValidate()
  {
    if (empty($this->start_visit)) {
      $this->start_visit = 1;
    }
    return parent::beforeValidate(); // TODO: Change the autogenerated stub
  }

  public function beforeSave($insert)
  {
    if ($this->isNewRecord) {
      $this->cafe_id = (!isset(Yii::$app->user) || Yii::$app->user->isGuest) ? 1 : Yii::$app->cafe->id;
      if (empty($this->franchisee_id)) {
        $this->franchisee_id = Yii::$app->cafe->franchiseeId;
      }
    }

    if ($this->type_id == self::TYPE_REGIONAL) {
      $this->cafe_id = null;
    }

    $data = [];
    $data[self::DATA_HOURS_KEY] = $this->_hours;
    $this->data = $data;

    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }

  public function afterSave($insert, $changedAttributes)
  {
    Yii::$app->cache->flush();
    parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
  }

  public static function getTypeLabels($index = null)
  {
    $labels = [
        self::TYPE_CAFE_ORIENTED => Yii::t('app', 'Cafe'),
        self::TYPE_REGIONAL => Yii::t('app', 'Regional'),
    ];

    if ($index !== null) {
      return isset($labels[$index]) ? $labels[$index] : Yii::t('app', 'Unknown');
    } else {
      return $labels;
    }
  }

  public function setupTypeDependentParams()
  {
    $cafe = Yii::$app->cafe;
    if ($this->type_id == self::TYPE_CAFE_ORIENTED) {
      $this->cafe_id = $cafe->getId();
      $this->params_id = null;
    } elseif ($this->type_id == self::TYPE_REGIONAL) {
      $this->cafe_id = null;
      $this->params_id = $cafe->getParamsId();
    }

    return true;
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getCafe()
  {
    return $this->hasOne(Cafe::className(), ['id' => 'cafe_id']);
  }

  public function getInfoline()
  {
    return Yii::t(
        'config',
        'tariff: min sum {min_sum}{currency};max sum {max_sum}{currency}; per hour: {first_hour}{currency}',
        $this->toArray() + ['currency' => Yii::$app->cafe->currency]
    );
  }

  public static function getRegionInfoline($params_id = false, $franchiseeId = false)
  {
    if (!$params_id) {
      $params_id = Yii::$app->cafe->getParamsId();
    }

    if (!$franchiseeId) {
      $franchiseeId = Yii::$app->cafe->franchiseeId;
    }

    $data = self::find()
        ->where([
            'and',
            ['cafe_id' => null],
            ['params_id' => $params_id],
        ])
        ->andWhere(['<=', 'start_visit', 1])
        ->andWhere(['active' => 0,
            'franchisee_id' => $franchiseeId
        ])->one();

    if (!$data) return "";

    return $data->getInfoline();
  }

  public static function test($fullResult = true)
  {
    $first_hour_tarif = self::find()
        ->where(['or', [
            'and',
            ['cafe_id' => Yii::$app->cafe->id],
            ['params_id' => null],
        ], [
            'and',
            ['cafe_id' => null],
            ['params_id' => Yii::$app->cafe->getParamsId()],
        ],
        ])
        ->andWhere(['<=', 'start_visit', 1])
        ->andWhere(['active' => 0,
            'franchisee_id' => Yii::$app->cafe->franchiseeId
        ]);

    if (!$fullResult) {
      return $first_hour_tarif->count();
    }

    $first_hour_tarif = $first_hour_tarif->one();
    $data = [
        'title' => 'Tariffs',
        'description' => 'Tariffs description',
        'icon' => 'fa fa-sliders',
        'buttons' => []
    ];

    if ($first_hour_tarif) {
      $data['buttons'][] = [
          'name' => 'edit',
          'modal' => true,
          'href' => '/tariffs/admin/update?id=' . $first_hour_tarif->id
      ];
      $data['infoline'] = $first_hour_tarif->getInfoline();
      //var_dump($first_hour_tarif->toArray());
    } else {
      $data['buttons'][] = [
          'name' => 'create',
          'modal' => true,
          'href' => '/tariffs/admin/create'
      ];
      $data['error'] = true;
      $data['infoline'] = Yii::t('app', 'No rates found for this cafe.');
    }
    return $data;
  }

}
