<?php

namespace frontend\modules\templates\controllers;

use frontend\components\Controller;
use frontend\modules\cafe\models\Cafe;
use frontend\modules\franchisee\models\Franchisee;
use frontend\modules\templates\models\Template;
use frontend\modules\templates\models\TemplateSearch;
use frontend\modules\templates\models\TemplateTestForm;
use frontend\modules\templates\models\TemplateToCafe;
use frontend\modules\users\models\Users;
use Yii;
use yii\base\Exception;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\db\Query;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * AdminController implements the CRUD actions for Template model.
 */
class AdminController extends Controller
{

  private $def_sel_column = [
      'id',
      'scope_id',
      'cafe_id',
      'franchisee_id',
      'type_id',
      'content',
      '_used_in_cafe',
      'updated_at',
      'created_at',
  ];

  /**
   * @inheritdoc
   */
  public function behaviors()
  {
    return [
        'verbs' => [
            'class' => VerbFilter::className(),
            'actions' => [
                'delete' => ['post'],
                'bulk-delete' => ['post'],
            ],
        ],];
  }

  public function beforeAction($action)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->cafe->can('TemplatesView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    return parent::beforeAction($action); // TODO: Change the autogenerated stub
  }

  /**
   * Lists all Template models.
   * @return mixed
   */
  public function actionIndex()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    $searchModel = new TemplateSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    $canCreate = true;
    $actions = "{update}{delete}";
    $actions .= "{use}";
    $actions .= "{send-on-email}";
    $actions .= "{print}";
    $afterTable = '';
    $panelButtons = Html::a(
        '<i class="fa fa-envelope"></i> ' . Yii::t('app', 'Email queue'),
        ['email-queue'],
        ['role' => 'modal-remote', 'class' => 'btn btn-default', 'title' => Yii::t('app', 'Email queue')]
    );

    $columns = include(__DIR__ . '/../views/admin/_columns.php');
    if (Yii::$app->user->isGuest) {
      $sel_column = Yii::$app->session->get("columns_Template", false);
    } else {
      $user = Yii::$app->getUser()->getIdentity();
      $sel_column = $user->getActiveColumn("columns_Template");
    }

    if (!$sel_column) {
      $sel_column = $this->def_sel_column;
    }

    foreach ($columns as $k => $column) {
      $column_name = !is_array($column) ? $column : (isset($column['attribute']) ? $column['attribute'] : false);
      if ($column_name && !in_array($column_name, $sel_column)) {
        unset($columns[$k]);
      }
    }

    return $this->render('index', [
        'searchModel' => $searchModel,
        'dataProvider' => $dataProvider,
        'columns' => $columns,
        'canCreate' => $canCreate,
        'afterTable' => $afterTable,
        'title' => Yii::t('app', 'Template list'),
        'panelButtons' => $panelButtons,
    ]);
  }

  public function actionEmailQueue()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    $request = Yii::$app->request;
    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException('Page does not exist');
    }

    Yii::$app->response->format = Response::FORMAT_JSON;

    try {
      $tableName = isset(Yii::$app->queue) ? Yii::$app->queue->tableName : '{{%queue}}';
      $stats = (new Query())
          ->from($tableName)
          ->select([
              'total' => 'COUNT(*)',
              'pending' => 'SUM(CASE WHEN reserved_at IS NULL AND done_at IS NULL THEN 1 ELSE 0 END)',
              'processing' => 'SUM(CASE WHEN reserved_at IS NOT NULL AND done_at IS NULL THEN 1 ELSE 0 END)',
              'done' => 'SUM(CASE WHEN done_at IS NOT NULL THEN 1 ELSE 0 END)',
          ])
          ->one();
    } catch (\Throwable $e) {
      Yii::error([
          'message' => 'Email queue stats failed',
          'error' => $e->getMessage(),
      ]);

      return [
          'title' => Yii::t('app', 'Email queue'),
          'content' => Html::tag('div', Yii::t('app', 'Unable to load queue stats.'), ['class' => 'text-danger']),
      ];
    }

    return [
        'title' => Yii::t('app', 'Email queue'),
        'content' => $this->renderAjax('email-queue', [
            'stats' => $stats,
        ]),
        'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]),
    ];
  }


  /**
   * Config column in Template model.
   * @param integer $id
   * @return mixed
   * @throws NotFoundHttpException if the model cannot be found
   */
  public function actionColumns()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    $model = new Template();
    $searchModel = new TemplateSearch();

    $request = Yii::$app->request;

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException('Page does not exist');
    }

    Yii::$app->response->format = Response::FORMAT_JSON;

    if ($request->post('column')) {
      $col = $request->post('column');

      if (Yii::$app->user->isGuest) {
        Yii::$app->session->set("columns_Template", $col);
      } else {
        $user = Yii::$app->getUser()->getIdentity();
        $user->setActiveColumn("columns_Template", $col);
      }

      return [
          'forceClose' => 'true',
          'forceReload' => '#crud-datatable-pjax',
          'content' => Yii::$app->view->closeModal(),
      ];
    }
    $actions = "";
    $columns = include(__DIR__ . '/../views/admin/_columns.php');
    if (Yii::$app->user->isGuest) {
      $sel_column = Yii::$app->session->get("columns_Template", false);
    } else {
      $user = Yii::$app->getUser()->getIdentity();
      $sel_column = $user->getActiveColumn("columns_Template");
    }
    if (!$sel_column) {
      $sel_column = $this->def_sel_column;
    }
    foreach ($columns as $k => $column) {
      $column_name = !is_array($column) ? $column : (isset($column['attribute']) ? $column['attribute'] : false);
      if (!$column_name) {
        unset($columns[$k]);
      } else {
        $columns[$k] = $column_name;
      }
    }

    return [
        'title' => Yii::t('app', "Change visible columns in Template table"),
        'content' => $this->renderAjax('columns', [
            'sel_column' => $sel_column,
            'columns' => $columns,
            'model' => $model,
            'isAjax' => true,
        ]),
        'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
            Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"]),

    ];
  }

  /**
   * Creates a new Template model.
   * For ajax request will return json object
   * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
   * @return mixed
   */
  public function actionCreate()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateCreate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    $request = Yii::$app->request;
    $model = new Template();

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException('Page does not exist');
      return false;
    }

    /*
    *   Process for ajax request
    */
    Yii::$app->response->format = Response::FORMAT_JSON;
    if ($request->isGet) {
      return [
          'title' => Yii::t('app', "Create new Template"),
          'content' => $this->renderAjax('create', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"]),
      ];
    } else if ($model->load($request->post()) && $model->setupScopeDependentParams() && $model->save()) {
      $url = Url::toRoute(['update', 'id' => $model->id]);
      \Yii::$app->session->addFlash('success', Yii::t('app', 'Template successfully created'));
      return [
          'title' => Yii::t('app', "Create new Template"),
          'content' => Yii::t('app', "Template successfully created") . Html::tag('script', "window.location.replace('{$url}')"),
      ];
    } else {
      return [
          'title' => Yii::t('app', "Create new Template"),
          'content' => $this->renderAjax('create', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"]),

      ];
    }
  }

  /**
   * Updates an existing Template model.
   * For ajax request will return json object
   * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
   * @param integer $id
   * @return mixed
   */
  public function actionUpdate($id)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateUpdate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    $request = Yii::$app->request;
    $model = $this->findModel($id);

    if ($model->load($request->post()) && $model->setupScopeDependentParams() && $model->save()) {

      Yii::$app->session->addFlash('success', Yii::t('app', 'Template updated'));

      return $this->refresh();
    }


    $js = 'editor.setData(' . $model->content . ')';
    Yii::$app->view->registerJs($js);

    return $this->render('update', [
        'title' => ''.Yii::t('app', "Update Template").'',
        'model' => $model,
        'back_url' => "/templates/admin",
        'used_in_cafe' => $model->getCafe(Yii::$app->cafe->getId())->exists()
    ]);
  }

  /**
   * Delete an existing Template model.
   * For ajax request will return json object
   * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   */
  public function actionDelete($id)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateDelete')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    $request = Yii::$app->request;
    $this->findModel($id)->delete();

    if ($request->isAjax) {
      /*
      *   Process for ajax request
      */
      Yii::$app->response->format = Response::FORMAT_JSON;
      return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
    } else {
      /*
      *   Process for non-ajax request
      */
      return $this->redirect(['index']);
    }
  }

  /**
   * Delete multiple existing Template model.
   * For ajax request will return json object
   * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
   * @param integer $id
   * @return mixed
   */
  public function actionBulkDelete()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateDelete')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    $request = Yii::$app->request;
    $pks = explode(',', $request->post('pks')); // Array or selected records primary keys
    foreach ($pks as $pk) {
      $model = $this->findModel($pk);
      $model->delete();
    }

    if ($request->isAjax) {
      /*
      *   Process for ajax request
      */
      Yii::$app->response->format = Response::FORMAT_JSON;
      return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
    } else {
      /*
      *   Process for non-ajax request
      */
      return $this->redirect(['index']);
    }

  }

  public function actionUsed($id)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateUpdate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    $request = Yii::$app->request;

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException('Page does not exist');
      return false;
    }

    if (!$request->isAjax) {
      return $this->goBack();
    }
    Yii::$app->response->format = Response::FORMAT_JSON;

    $model = $this->findModel($id);

    $transaction = Yii::$app->getDb()->beginTransaction();

    $cafeListTmp = Users::getCafesList();
    $cafeList = [];
    $allCafeIds = [];
    foreach ($cafeListTmp as $cafe) {
      $franchisee = Franchisee::find()->where(['id' => $cafe['franchisee_id']])->one();
      $cafeList[$cafe['franchisee_id']]['name'] = $franchisee['name'];
      $cafeList[$cafe['franchisee_id']]['items'][$cafe['id']] = $cafe['name'];
      $allCafeIds[] = $cafe['id'];
    }

    $model->used_in_cafe_ids = ArrayHelper::getColumn($model->getCafes()->asArray()->all(), 'id');

    if ($request->isPost && $model->load($request->post())) {
      if (count($allCafeIds) > 0) {
        // Disconnect this template from selected Cafe's
        TemplateToCafe::deleteAll([
            'cafe_id' => $allCafeIds,
            'template_id' => $model->id,
        ]);
      }

      if (!empty($model->used_in_cafe_ids)) {
        // Disconnect templates of this type from Cafe's before setting
        TemplateToCafe::deleteAll([
            'cafe_id' => $model->used_in_cafe_ids,
            'type_id' => $model->type_id,
        ]);

        foreach ($model->used_in_cafe_ids as $cafe_id) {
          $conn = new TemplateToCafe();
          $conn->setAttributes([
              'template_id' => $model->id,
              'cafe_id' => $cafe_id,
              'type_id' => $model->type_id,
          ]);
          if (!$conn->save()) {
            throw new Exception('Template to Cafe attach error');
          }
        }
      }

      $cafes = Cafe::find()
          ->leftJoin(TemplateToCafe::tableName(),
              "template_to_cafe.cafe_id=cafe.id AND " .
              'template_to_cafe.type_id=' . $model->type_id
          )
          ->where([
              'template_to_cafe.template_id' => null,
          ])
          ->select(['cafe.id', 'template_to_cafe.template_id'])
          ->asArray()
          ->all();

      if (count($cafes) > 0) {
        $defaultTemplate = Template::find()
            ->where([
                'type_id' => $model->type_id,
                'scope_id' => 1
            ])
            ->one();

        if ($defaultTemplate) {
          foreach ($cafes as $cafe) {
            $conn = new TemplateToCafe();
            $conn->setAttributes([
                'template_id' => $defaultTemplate->id,
                'cafe_id' => $cafe['id'],
                'type_id' => $defaultTemplate->type_id,
            ]);
            if (!$conn->save()) {
              var_dump($conn->errors);
              exit;
              throw new Exception('Template to Cafe attach error');
            }
          }
        }
      };
      $transaction->commit();

      Yii::$app->session->addFlash('success', Yii::t('app', 'Template updated'));

      $transaction->rollBack();

      return [
          'forceReload' => '#pjaxButton',
          'forceClose' => 'true',
          'content' => Yii::$app->view->closeModal(),
      ];
    }

    return [
        'title' => Yii::t('editor', "Select Cafe's to use this template"),
        'content' => $this->renderAjax('cafeList', [
            'cafeList' => $cafeList,
            'model' => $model
        ]),
        'footer' =>
            Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
            Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"]),
    ];


  }

  /**
   * Applies template to use in current Cafe
   * @param integer $id
   * @return mixed
   */
  public function actionUse($id)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateUpdate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    $request = Yii::$app->request;
    $model = $this->findModel($id);

    $cafe = Cafe::find()->where(['id' => Yii::$app->cafe->getId()])->one();

    TemplateToCafe::deleteAll([
        'cafe_id' => $cafe->id,
        'type_id' => $model->type_id,
    ]);

    $cafe->link('templates', $model, ['type_id' => $model->type_id]);

    if ($request->isAjax) {
      /*
      *   Process for ajax request
      */
      Yii::$app->response->format = Response::FORMAT_JSON;
      return [
          'forceClose' => true,
          'forceReload' => '#crud-datatable-pjax,#pjaxButton'
      ];
    } else {
      /*
      *   Process for non-ajax request
      */
      return $this->redirect(['index']);
    }
  }

  /**
   * Finds the Template model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return Template the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id)
  {
    if (($model = Template::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException('Page does not exist');
    }
  }

  /*
   * Временная функция для проверки генерируемого шаблона
   */
  public function actionView($id)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateUpdate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    $model = $this->findModel($id);
    return $model->getTemplate();
  }

  public function actionTestPrint($id, $db = 0)
  {
    $template = $this->findModel($id);

    $request = Yii::$app->request;

    $model = new TemplateTestForm($template);
    if (!$model->load($request->get()) && !$model->process()) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    if ($db == 1) {
      $data = Yii::$app->session->get('tpl_' . $id);
      if ($data) {
        $template->content = $data;
      }
    };

    Yii::$app->response->format = Response::FORMAT_RAW;
    return $template->renderTemplate($model->data);
  }

  public function actionPrint($id, $db = 0)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateUpdate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }
    $request = Yii::$app->request;

    if (!$request->isAjax && !YII_DEBUG) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    $template = $this->findModel($id);

    $model = new TemplateTestForm($template);

    if ($db == 1) {
      if ($request->isPost && $request->post('data')) {
        Yii::$app->session->set('tpl_' . $id, $request->post('data'));
        return "OK";
      } else {
        $data = Yii::$app->session->get('tpl_' . $id);
        if ($data) {
          $template->content = $data;
        }
      }
    }

    /*
    *   Process for ajax request
    */
    Yii::$app->response->format = Response::FORMAT_JSON;
    $title = Yii::t('app', "Template test");
    if (!$request->isGet ||
        ($model->load($request->post()) && $model->process())
    ) {
      return [
          'title' => $title,
          'content' => $model->getContent(),
          'template' => $template,
      ];
    } else {
      $btn = Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]);
      if ($template->params['is_print']) {
        $btn .= Html::button(Yii::t('app', 'Test'), [
            'class' => 'btn btn-primary print',
            'data' => [
                'type' => 'test',
                'link' => Url::toRoute(['test-print', 'id' => $id, 'db' => $db])
            ]
        ]);
      } else {
        $btn .= Html::button(Yii::t('app', 'Test'), ['class' => 'btn btn-primary', 'type' => "submit"]);
      }
      return [
          'title' => $title,
          'content' => $this->renderAjax('test', [
              'model' => $model,
              'isAjax' => true,
              'template' => $template,
          ]),
          'footer' => $btn,

      ];
    }
  }

  public function actionSendOnEmail($id, $db = 0)
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('TemplateView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }

    $request = Yii::$app->request;

    $template = $this->findModel($id);

    if ($db == 1) {
      $data = Yii::$app->session->get('tpl_' . $id);
      if ($data) {
        $template->content = $data;
      }
    }

    $model = new TemplateTestForm($template);

    /*
    *   Process for ajax request
    */
    Yii::$app->response->format = Response::FORMAT_JSON;
    $title = Yii::t('app', "Template test");
    if ($request->isGet) {
      return [
          'title' => $title,
          'content' => $this->renderAjax('test', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Test'), ['class' => 'btn btn-primary', 'type' => "submit"]),
      ];
    } else if ($model->load($request->post()) && $model->process()) {
      return [
          'title' => $title,
          'content' => $model->getContent(),
      ];
    } else {
      return [
          'title' => $title,
          'content' => $this->renderAjax('test', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Test'), ['class' => 'btn btn-primary', 'type' => "submit"]),

      ];
    }
  }
}