<?php

namespace frontend\modules\i18n\controllers;

use frontend\components\Controller;
use Yii;
use yii\jui\JuiAsset;

/**
 * Default controller for the `i18n` module
 */
class DefaultController extends Controller
{

  public function init()
  {
    if (Yii::$app->user->isGuest || !Yii::$app->user->can('Lang_edit')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('admin', 'Page does not exist'));
      return false;
    }

    parent::init(); // TODO: Change the autogenerated stub
  }

  /**
   * Renders the index view for the module
   * @return string
   */
  public function actionIndex()
  {
    $skip_files = [];

    $i18n = Yii::$app->getComponents()['i18n'];
    $basePath = [];
    foreach ($i18n['translations'] as $translation_group) {
      $base = $translation_group['basePath'];
      if (!isset($basePath[$base])) {
        $basePath[$base] = Yii::getAlias($base);
      }
    }
    $defaultLang = Yii::$app->params['defaultLang'];

    $lg_base = [];
    foreach ($basePath as $alies => $path) {
      $base_lg_dir = $path . '/' . $defaultLang;
      if (!is_readable($base_lg_dir)) {
        return '404';
      }
      $lg_base[$alies] = [];
      $files = scandir($base_lg_dir);
      foreach ($files as $file) {
        if (in_array($file, array(".", "..")) || in_array($file, $skip_files)) continue;
        $lg_base[$alies][$defaultLang][$file] = include $base_lg_dir . '/' . $file;
        foreach (Yii::$app->params['lg_list'] as $lang => $name) {
          if ($lang == $defaultLang) continue;
          $lg_path = $path . '/' . $lang . '/' . $file;
          if (is_readable($lg_path)) {
            $lg_base[$alies][$lang][$file] = include $lg_path;
          }
        }
      };
    }

    Yii::$app->view->registerJsFile('/js/i18n.js', [
        'depends' => [
            \yii\web\JqueryAsset::className(),
            JuiAsset::className(),
        ]]);

    return $this->render('index', [
        'lg_base' => $lg_base,
        'defaultLang' => $defaultLang,
        'lg_list' => Yii::$app->params['lg_list'],
        'title' => Yii::t('app', 'Translations'),
    ]);
  }

  function actionUpdate()
  {
    $request = Yii::$app->request;
    $path = $request->post('alies');
    $path .= '/' . $request->post('lg');
    $path = Yii::getAlias($path);

    if (!is_dir($path)) {
      mkdir($path, 0777, true);
    }

    $path .= '/' . $request->post('file');
    $path = str_replace('//', '/', $path);
    if (is_readable($path)) {
      $lg = require($path);
    } else {
      $lg = [];
    }
    $lg[$request->post('code')] = $request->post('value');
    $out = "<?php\n  return " . var_export($lg, true) . ";\n?>\n";
    if (file_put_contents($path, $out)) {
      return 'OK';
    } else {
      throw new \yii\web\ForbiddenHttpException(Yii::t('admin', 'Error writing file'));
      return false;
    }
  }
}
