<?php

namespace frontend\models;

use frontend\modules\visitor\models\Visitor;
use frontend\modules\visits\models\VisitorLog;

/**
 * This is the model class for table "{{%transaction}}".
 *
 * @property int $id ID
 * @property double $sum
 * @property double $cost
 * @property int $method
 * @property int $visit_id
 * @property int $sale_id
 * @property int $visitor_id
 * @property int $pay_man
 * @property string $created_at
 *
 * @property VisitorLog $visit
 * @property Visitor $visitor
 */
class Transaction extends \yii\db\ActiveRecord
{
  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return '{{%transaction}}';
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
        [['sum'], 'required'],
        [['sum', 'cost', 'terminal_ans'], 'number'],
        [['method', 'visit_id', 'sale_id', 'visitor_id', 'pay_man'], 'integer'],
        [['created_at'], 'safe'],
        [['visit_id'], 'exist', 'skipOnError' => true, 'targetClass' => VisitorLog::className(), 'targetAttribute' => ['visit_id' => 'id']],
        [['visitor_id'], 'exist', 'skipOnError' => true, 'targetClass' => Visitor::className(), 'targetAttribute' => ['visitor_id' => 'id']],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
        'id' => 'ID',
        'sum' => 'Sum',
        'cost' => 'Cost',
        'method' => 'Method',
        'visit_id' => 'Visit ID',
        'sale_id' => 'Sale ID',
        'visitor_id' => 'Visitor ID',
        'created_at' => 'Created At',
    ];
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getVisit()
  {
    return $this->hasOne(VisitorLog::className(), ['id' => 'visit_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getVisitor()
  {
    return $this->hasOne(Visitor::className(), ['id' => 'visitor_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getPayman()
  {
    return $this->hasOne(Visitor::className(), ['id' => empty($this->pay_man) ? 'visitor_id' : 'pay_man']);
  }

  public function beforeValidate()
  {
    if (empty($this->visitor_id)) $this->visitor_id = null;
    if (empty($this->sale_id)) $this->sale_id = null;
    if (empty($this->visit_id)) $this->visit_id = null;
    return parent::beforeValidate(); // TODO: Change the autogenerated stub
  }

  public function beforeSave($insert)
  {
    if ($this->sum < 0) {
      $this->sum = 0;
    }
    $this->sum = round($this->sum, 2);

    if (empty($this->cafe_id)) {
      $this->cafe_id = \Yii::$app->cafe->id;
    }
    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }
}
