<?php
/**
 * Created by PhpStorm.
 * User: acid
 * Date: 17.10.18
 * Time: 19:47
 */

namespace frontend\modules\selfservice\controllers;

use console\jobs\CheckMailSendJob;
use frontend\components\Controller;
use frontend\modules\polls\models\Polls;
use frontend\modules\selfservice\models\SelfServiceExistingUser;
use frontend\modules\selfservice\models\SelfServiceNewUser;
use frontend\modules\selfservice\models\SelfServiceUserQrInput;
use frontend\modules\visits\models\VisitorLog;
use Yii;
use yii\bootstrap\ActiveForm;
use yii\filters\AccessControl;
use yii\helpers\Html;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * DefaultController
 */
class DefaultController extends Controller
{
  public $layout = 'self_service';

  private $_session_mode_key;

  public function behaviors()
  {
    return [
        'access' => [
            'class' => AccessControl::className(),
            'rules' => [
                [
                    'allow' => true,
                    'roles' => ['SelfServiceModeEnter'],
                ],
            ],
        ],
    ];
  }

  public function init()
  {
    $module = Yii::$app->getModule('selfservice');

    $this->_session_mode_key = $module::SESSION_MODE_KEY;

    parent::init(); // TODO: Change the autogenerated stub
  }

  public function beforeAction($action)
  {
    $mode = $this->getMode();

    $withoutModeActions = [
        'index',
        'mode',
    ];

    if (!in_array($action->id, $withoutModeActions) && $mode === null) {
      return $this->redirect(['index']);
    }

    return parent::beforeAction($action); // TODO: Change the autogenerated stub
  }

  public function actionIndex()
  {
    if (Yii::$app->request->isAjax) {
      Yii::$app->response->format = Response::FORMAT_JSON;
      return [
          'title' => Yii::t('app', "Self service"),
          'content' => $this->renderPartial('index', [
              'isModal' => true,
          ]),
          'footer' => '',
      ];
    } else {
      $this->layout = "/form_page";
      return $this->render('index');
    }
  }

  public function actionKeepAlive()
  {
    return 'OK';
  }

  public function actionMode($value = null)
  {
    if (!Yii::$app->cafe->can($value)) {
      throw new ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
    }
    $this->setMode($value);
    $qrCode = Yii::$app->request->get('qr-code');

    return $this->redirect([$qrCode ? 'qr-input' : 'dashboard']);
  }

  public function actionDashboard()
  {
    $mode = $this->getMode();

    if ($mode == 'selfServiceLogoutOnlyMode') {
      return $this->redirect(['checkout']);
    }

    return $this->render('dashboard', [
        'mode' => $mode,
    ]);
  }

  public function actionWelcome($visit_id)
  {
    $model = VisitorLog::find()->where(['id' => $visit_id])->one();

    if (!$model) {
      throw new NotFoundHttpException(Yii::t('app', 'Page does not exist'));
    }

    Yii::$app->session->addFlash('polls', ['visitor_id' => $model->visitor_id, 'mode' => Polls::EVENT_START_VISIT]);

    return $this->render('welcome', [
        'model' => $model,
        'newUser' => $model->type == VisitorLog::TYPE_NEW,
    ]);
  }

  public function actionNewUser()
  {
    $model = new SelfServiceNewUser();

    if ($model->load(Yii::$app->request->post())) {
      if (Yii::$app->request->isAjax) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return ActiveForm::validate($model);
      }

      if ($model->start()) {
        return $this->redirect(['welcome', 'visit_id' => $model->visit->id]);
      }
    }

    return $this->render('new-user/index', [
        'model' => $model,
    ]);
  }

  public function actionExistingUser()
  {
    $model = new SelfServiceExistingUser();

    if ($model->load(Yii::$app->request->post())) {
      if (Yii::$app->request->isAjax) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return ActiveForm::validate($model);
      }

      if ($model->start()) {
        return $this->redirect(['welcome', 'visit_id' => $model->visit->id]);
      }
    }

    $this->view->registerJs('$(\'[type=reset]\').on(\'click\',function(){
     $(\'[name="SelfServiceExistingUser[visitor_id]"]\').attr(\'value\',\'\')
    })');
    return $this->render('existing-user/index', [
        'model' => $model,
    ]);
  }

  public function actionQrInput()
  {
    $mode = $this->getMode();

    if ($mode == 'selfServiceLogoutOnlyMode') {
       return $this->redirect(['checkout']);
    }

    $model = new SelfServiceUserQrInput();

    if ($model->load(Yii::$app->request->post())) {
          if (Yii::$app->request->isAjax) {
              Yii::$app->response->format = Response::FORMAT_JSON;
              return ActiveForm::validate($model);
          }

          if ($model->start()) {
              return $this->redirect(['welcome', 'visit_id' => $model->visit->id]);
          }
    }

    $this->view->registerJsFile('/js/qr-input.js');
    return $this->render('existing-user/qr_input', [
      'model' => $model,
    ]);
  }

  public function actionTips($visit_id = null)
  {
    $request = Yii::$app->request;

    if (!$request->isAjax) {
      return $this->redirect(['/']);
    }

    if (!Yii::$app->cafe->can('Tips')) {
      return $this->actionPay_card($visit_id);
    }

    Yii::$app->response->format = Response::FORMAT_JSON;
    $visit = VisitorLog::find()
        ->where(['id' => $visit_id])
        ->andWhere('finish_time is NULL')
        //->andWhere('pay_state = 0')
        ->one();

    if (!$visit) {
      $footer = Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]);
      return [
          'title' => Yii::t('selfservice', "Acceptance of payment."),
          'content' => Yii::t('selfservice', 'Visit not found'),
          'footer' => $footer,
      ];
    }

    if ($request->isPost && $visit->load($request->post())) {
      if (empty($visit->tip) || !is_numeric($visit->tip) || $visit->tip < 0) {
        $visit->addError('tip', Yii::t('selfservice', 'Enter tip amount'));
      } else {
        $visit->tip = round($visit->tip, 2);
        return [
            'title' => '<span class="fa fa-credit-card antagon-color-main"></span> ' . Yii::t('selfservice', "Pay card"),
            'content' => $this->renderAjax('pay_card', [
                'model' => $visit,
                'cafe' => Yii::$app->cafe,
                'selfservice' => true,
            ]),
            'footer' => ''
        ];
      }
    }


    $footer = Html::button(Yii::t('selfservice', 'Confirm'), ['class' => 'btn btn-lg btn-primary', 'type' => "submit"]);
    $footer = $this->renderAjax('tips_footer', [
        'model' => $visit,
        'cafe' => Yii::$app->cafe,
        'selfservice' => true,
        'btn' => $footer
    ]);
    return [
        'title' => '<span class="icon-metro-coins antagon-color-main"></span> ' . Yii::t('selfservice', "Tips"),
        'content' => $this->renderAjax('tips', [
            'model' => $visit,
            'cafe' => Yii::$app->cafe,
            'selfservice' => true,
        ]),
        'footer' => $footer
    ];

  }

  public function actionPayment_status()
  {
    $request = Yii::$app->request;

    if (!$request->isAjax || !$request->isPost || !$request->post('visit_id')) {
      throw new NotFoundHttpException('denye');
    }

    Yii::$app->response->format = Response::FORMAT_JSON;
    $visit = VisitorLog::find()
        ->where(['id' => $request->post('visit_id')])
        ->andWhere('finish_time is not NULL')
        ->andWhere('pay_state = ' . VisitorLog::PAY_METHOD_CARD)
        ->one();

    if ($visit) {
      if ($visit->canSendMail()) {
        $visit->send_mail_status = 1;
        Yii::$app->queue->delay(Yii::$app->params['checkMailSendDelay'])->push(new CheckMailSendJob(['visit_id' => $visit->id]));
      }
      return 'ok';
    }

    throw new NotFoundHttpException('visit not found');
  }

  public function actionAdd_tips($visit_id = null)
  {
    $request = Yii::$app->request;

    if (!$request->isAjax) {
      return $this->redirect(['/']);
    }

    Yii::$app->response->format = Response::FORMAT_JSON;
    $visit = VisitorLog::find()
        ->where(['id' => $visit_id])
        ->andWhere('finish_time is not NULL')
        ->andWhere('pay_state = 0')
        ->one();

    if (!$visit) {
      $footer = Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]);
      return [
          'title' => Yii::t('selfservice', "Acceptance of payment."),
          'content' => Yii::t('selfservice', 'Visit not found'),
          'footer' => $footer,
      ];
    }

    //$visit->endPause();
    //$visit->finish_time = date("Y-m-d H:i:s");
    //$visit->save();

    $footer = Html::a(
            Yii::t('app', 'NO'),
            ['pay_card', 'visit_id' => $visit_id],
            ['class' => 'btn btn-warning btn-lg', "role" => "modal-remote"]
        ) .
        Html::a(
            Yii::t('app', 'Yes'),
            ['tips', 'visit_id' => $visit_id],
            ['class' => 'btn btn-success btn-lg', "role" => "modal-remote"]
        );

    return [
        'title' => '',//Yii::t('selfservice', "Acceptance of payment."),
        'content' => $this->renderAjax('tips_question', [
            'model' => $visit,
            'cafe' => Yii::$app->cafe,
            'selfservice' => true,
        ]),
        'footer' => $footer,
    ];
  }

  public function actionPay_card($visit_id = null)
  {
    $request = Yii::$app->request;

    if (!$request->isAjax) {
      return $this->redirect(['/']);
    }

    Yii::$app->response->format = Response::FORMAT_JSON;
    $visit = VisitorLog::find()
        ->where(['id' => $visit_id])
        ->andWhere('finish_time is  NULL')
        ->andWhere('pay_state = 0')
        ->one();


    if (!$visit) {
      $footer = Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]);
      return [
          'title' => Yii::t('selfservice', "Acceptance of payment."),
          'content' => Yii::t('selfservice', 'Visit not found'),
          'footer' => $footer,
      ];
    }


    return [
        'title' => '<span class="fa fa-credit-card antagon-color-main"></span> ' . Yii::t('selfservice', "Pay card"),
        'content' => $this->renderAjax('pay_card', [
            'model' => $visit,
            'cafe' => Yii::$app->cafe,
            'selfservice' => true,
        ]),
        'footer' => ''
    ];
  }

  public function actionCheckout($visit_id = null)
  {
    if ($visit_id !== null) {
      $visit = VisitorLog::find()
          ->where(['id' => $visit_id])
          ->andWhere('finish_time is NULL')
          ->one();

      //$visit->endPause();
      //$visit->finish_time = date("Y-m-d H:i:s");
      //$visit->save();

      Yii::$app->response->format = Response::FORMAT_JSON;

      $footer = Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]);

      if ($visit) {
        /*if(Yii::$app->request->isPost){
          $visit->endPause();
          $visit->finish_time = date("Y-m-d H:i:s");
          $visit->save();

          $cafe = Yii::$app->cafe;
          $footer = Html::button(
              '<i class="fa fa-money"></i>&nbsp;' . Yii::t('app', 'Pay Cash'),
              ['class' => 'btn btn-success fg-white', 'data-dismiss' => "modal"]
          );

          if ($cafe->can('payCard')) {
            $footer .= Html::a(
                '<i class="fa fa-credit-card"></i>&nbsp;' . Yii::t('app', 'Pay Card'),
                ['pay_card', 'id' => $visit_id, 'method' => VisitorLog::PAY_METHOD_CARD],
                ['class' => 'btn btn-info fg-white', "role" => "modal-remote"]
            );
          }

          return [
              'title' => Yii::t('selfservice', "Payment method."),
              'content' => $this->renderAjax('@frontend/modules/visits/views/default/stop.twig', [
                  'model' => $visit,
                  'cafe' => Yii::$app->cafe,
                  'selfservice' => true,
              ]),
              'footer' => $footer,
          ];
        }*/

        $visit->endPause();
        $visit->pay_man = null;
        $visit->finish_time = date("Y-m-d H:i:s");
        //$visit->save();

        Yii::$app->view->registerJs('$(\'.__checkout_user_name_input__\').val(\'\');$(\'#finded_visits_wrapper\').html(\'\')');

        $cafe = Yii::$app->cafe;
        //if ($cafe->can('payCard')) {
        $footer .= Html::a(
            '<i class="fa fa-credit-card"></i>&nbsp;' . Yii::t('app', 'Pay Card'),
            //['add_tips', 'visit_id' => $visit_id],
            ['tips', 'visit_id' => $visit_id],
            ['class' => 'btn btn-info fg-white', "role" => "modal-remote"]
        );
        //}

        //подумать куда перенести
        //Yii::$app->session->addFlash('polls', ['visitor_id' => $visit->visitor_id, 'mode' => Polls::EVEVT_FINISH_VISIT]);
        return [
            'title' => Yii::t('selfservice', "Acceptance of payment."),
            'content' => $this->renderAjax('@frontend/modules/visits/views/default/stop.twig', [
                'model' => $visit,
                'cafe' => Yii::$app->cafe,
                'selfservice' => true,
            ]),
            'footer' => $footer,
        ];
      }
      return [
          'title' => Yii::t('selfservice', "Acceptance of payment."),
          'content' => Yii::t('selfservice', 'Visit not found'),
          'footer' => $footer,
      ];
    }

    $lang = [
        1 => '<img src="/img/loading.gif">',
        2 => Yii::t('selfservice', 'Communication error with terminal<div>contact administrator</div>'),
        3 => Yii::t('selfservice', 'Service payment does not work.<div>contact administrator</div>'),
        4 => Yii::t('selfservice', 'Terminal busy, repeat please<div>or contact administrator</div>'),
		5 => Yii::t('selfservice', 'Insert the card<div>and perform the payment.</div>'),
        6 => Yii::t('selfservice', 'Terminal waits<div>for a new request.</div>'),
        7 => '<img src="img/loading.gif">',
        8 => Yii::t('selfservice', 'Successful payment!<div>Thank you for visiting!</div>'),
        9 => Yii::t('selfservice', 'Payment error<div>contact administrator</div>'),
        10 => Yii::t('selfservice', 'Problem with the card <div>contact administrator</div>'),
        11 => Yii::t('selfservice', 'Canceled visitor'),
        12 => Yii::t('selfservice', 'Timed out..Try again!'),
        13 => Yii::t('selfservice', 'No connection'),
        14 => Yii::t('selfservice', 'CANCEL'),
        15 => Yii::t('selfservice', 'RETRY'),
        16 => Yii::t('selfservice', 'Connection Error'),
        17 => Yii::t('selfservice', '<i class="fa fa-credit-card"></i> Insert the card'),
        18 => Yii::t('selfservice', 'Card declined'),
        19 => Yii::t('selfservice', 'Terminal busy'),
		20 => Yii::t('selfservice', 'Repeat'),
        21 => Yii::t('selfservice', 'Wait..'),
        22 => Yii::t('selfservice', 'Paid'),
        23 => Yii::t('selfservice', 'Payment error'),
        24 => Yii::t('selfservice', 'Timed out'),
        25 => Yii::t('selfservice', 'Communication Error'),
        26 => Yii::t('selfservice', 'Communication Error.<div>contact administrator</div>'),
        27 => Yii::t('selfservice', 'Not Completed'),
        28 => Yii::t('selfservice', 'Transaction/Function Not Completed <div>contact administrator</div>'),
        29 => Yii::t('selfservice', 'Batch Empty'),
        30 => Yii::t('selfservice', 'Batch Empty <div>contact administrator</div>'),
        31 => Yii::t('selfservice', 'Declined by Merchant'),
        32 => Yii::t('selfservice', 'Declined by Merchant<div>contact administrator</div>'),
        33 => Yii::t('selfservice', 'Payment amount too small to pay by card'),
    ];
    foreach ($lang as &$lg) {
      $lg = trim($lg);
      if (strip_tags($lg) != 0) {
        $lg = Yii::t('selfservice', $lg);
      }
    };
    Yii::$app->view->registerJsFile('/js/payment.js');
    Yii::$app->view->registerJs(
        '
        lang = ' . json_encode($lang) . '
        close_modal_timer_max=' . Yii::$app->cafe->get()->selfservice_timaout . ';
        setInterval(close_modal_timer,1000);
        ');
    return $this->render('checkout/index');
  }

  public function actionFindActiveVisits($term)
  {
    $term = str_replace('  ', ' ', trim(strip_tags($term)));
    $term = addslashes($term);
    $term = mb_strtolower($term);
    Yii::$app->response->format = Response::FORMAT_JSON;

    $results = [];

    $visits = VisitorLog::find()
        ->alias('t')
        ->innerJoinWith('visitor')
        ->andWhere([
            't.cafe_id' => Yii::$app->cafe->getId(),
            't.finish_time' => null,
        ])
        ->andWhere(['NOT', ['t.visitor_id' => NULL]])
        ->andWhere([
            'OR',
	        ['like', 'CONCAT_WS(" ", LOWER(visitor.f_name), LOWER(visitor.l_name))', $term . '%', false], // Имя + Фамилия
            ['like', 'LOWER(visitor.l_name)', $term . '%', false], // Фамилия
        ])->limit(5)->all();

    foreach ($visits as $model) {
      $email = $model->visitor->email;

      if (!empty($email)) {
        // Email mask
        $emailParts = explode('@', $email);
        $length = floor(strlen($emailParts[0]) / 2);
        for ($i = 0; $i <= $length; $i++) {
          $emailParts[0] = substr_replace($emailParts[0], '*', $i, 1);
        }
        $email = implode('@', $emailParts);
      }

      $data = [
          'id' => $model['id'],
          'f_name' => $model->visitor->f_name,
          'l_name' => $model->visitor->l_name,
          'email' => $email,
      ];
      $results[] = $data;
    }

    return $results;
  }

  public function setMode($mode)
  {
	  Yii::$app->response->cookies->add(new \yii\web\Cookie([
		  'name' => $this->_session_mode_key,
		  'value' => $mode,
		  'httpOnly' => true,
		  'secure' => Yii::$app->request->isSecureConnection,
		  'sameSite' => \yii\web\Cookie::SAME_SITE_LAX,
	  ]));

    return Yii::$app->session->set($this->_session_mode_key, $mode);
  }

  public function getMode()
  {
	  // Setting Mode from cookie if not setted
	  if (
		  !Yii::$app->session->get($this->_session_mode_key, false) &&
		  $mode = Yii::$app->request->cookies->getValue($this->_session_mode_key, false)
	  ) {
		  Yii::$app->session->set($this->_session_mode_key, $mode);
	  }

    return Yii::$app->session->get($this->_session_mode_key);
  }
}