<?php

/**
 * Created by PhpStorm.
 * User: acid
 * Date: 17.09.18
 * Time: 18:16
 */

namespace frontend\modules\shop\widgets\merchant\models;

use frontend\modules\cafe\models\Cafe;
use frontend\modules\shop\models\ShopProduct;
use frontend\modules\shop\models\ShopTransaction;
use Yii;
use yii\base\Model;

class MerchantSaleForm extends Model
{
  public $barcode;
  public $quantity = 1;

  /* @var Cafe */
  private $_cafe;

  /* @var ShopProduct */
  public $product;

  public function init()
  {
    $this->_cafe = Yii::$app->cafe->get();

    parent::init(); // TODO: Change the autogenerated stub
  }

  public function rules()
  {
    return [
        [['barcode', 'quantity'], 'required'],
        [['quantity'], 'integer', 'min' => 1],
        [['barcode'], 'validateProductBeforeSale'],
    ];
  }

  public function validateProductBeforeSale($attribute, $params)
  {
    $product = ShopProduct::find()
        ->where(['and',
            'barcode=' . $this->barcode,
            Yii::$app->helper->cafe_where()
        ])
        ->andWhere(['<', 'is_active', 2])
        ->one();

    if (!$product) {
      $this->addError($attribute, Yii::t('main', 'Product not found'));
      return false;
    }

    if ($this->quantity > $product->quantity) {
      $this->addError($attribute, Yii::t('main', 'Product quantity not enough. Only {0} available.', $product->quantity));
      return false;
    }

    return true;
  }

  public function attributeLabels()
  {
    return [
        'barcode' => Yii::t('main', 'Barcode'),
        'quantity' => Yii::t('main', 'Quantity'),
    ];
  }

  public function process()
  {
    if (!$this->validate()) {
      return false;
    }

    $this->product = ShopProduct::find()
        ->where(['and',
            'barcode=' . $this->barcode,
            Yii::$app->helper->cafe_where()
        ])
        ->one();

    if ($this->product->in_stock == 1) {
      $this->addError('barcode', Yii::t('main', 'Product in stock'));
      return false;
    }

    if (ShopTransaction::makeWriteOff($this->product, $this->quantity, ['price' => $this->product->price])) {
      return true;
    }

    return true;
  }
}