<?php

/**
 * Created by PhpStorm.
 * User: acid
 * Date: 17.09.18
 * Time: 18:16
 */

namespace frontend\modules\shop\widgets\merchant\models;

use frontend\modules\cafe\models\Cafe;
use frontend\modules\shop\models\ShopProduct;
use frontend\modules\shop\models\ShopTransaction;
use Yii;
use yii\base\Model;

class MerchantIncomeForm extends Model
{
	public $barcode;
	public $quantity = 1;

	/* @var Cafe */
	private $_cafe;

	/* @var ShopProduct */
	public $product;

	public function init()
	{
		$this->_cafe = Yii::$app->cafe->get();

		parent::init(); // TODO: Change the autogenerated stub
	}

	public function rules()
	{
		return [
			[['barcode', 'quantity'], 'required'],
			[['quantity'], 'integer', 'min' => 1],
			[['barcode'], 'validateProductExist'],
		];
	}

	public function validateProductExist($attribute, $params)
	{
		$exists = ShopProduct::find()
			->active()
			->inCafe()
			->andWhere(['barcode' => $this->barcode])
			->exists();

		if (!$exists) {
			$this->addError($attribute, Yii::t('main', 'Product not found'));
		}
	}

	public function attributeLabels()
	{
		return [
			'barcode'  => Yii::t('main', 'Barcode'),
			'quantity' => Yii::t('main', 'Quantity'),
		];
	}

	public function process()
	{
		if (!$this->validate()) {
			return false;
		}

		$this->product = ShopProduct::find()
			->active()
			->inCafe()
			->andWhere(['barcode' => $this->barcode])
			->one();

		if($this->product->in_stock==1){
      $this->addError('barcode', Yii::t('main', 'Product in stock'));
		  return false;
    }

		if (ShopTransaction::makeIncome($this->product, $this->quantity, ['price' => $this->product->price])) {
			return true;
		}

		return false;
	}
}