<?php

namespace frontend\modules\franchisee\models;

use frontend\modules\cafe\models\Cafe;
use frontend\modules\cafe\models\Discount;
use frontend\modules\users\models\Users;
use frontend\modules\visitor\models\Visitor;
use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "franchisee".
 *
 * @property int $id
 * @property int $max_cafe
 * @property int $tariff_id
 * @property string $date_end
 * @property string $name
 * @property string $active_until
 * @property string $code
 * @property string $roles
 * @property string $languages
 * @property string $created_at
 * @property array $data
 *
 * @property Cafe[] $cafes
 * @property Users[] $users
 * @property Visitor[] $visitors
 */
class Franchisee extends \common\components\ActiveRecord
{
  public $roles_ids = [];
  public $language_ids = [];

  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return 'franchisee';
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
        [['name', 'code'], 'required'],
        [['active_until', 'created_at'], 'safe'],
        [['roles', 'languages'], 'safe'],
        [['name', 'code'], 'string', 'max' => 255],
        [['roles_ids', 'language_ids'], 'safe'],
        [['roles_ids', 'language_ids'], 'required'],
        [['code'], 'unique', 'targetAttribute' => 'code'],
        ['max_cafe', 'integer'],
        [['data'], 'safe'],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
        'id' => Yii::t('app', 'ID'),
        'name' => Yii::t('app', 'Name'),
        'active_until' => Yii::t('app', 'Active Until'),
        'code' => Yii::t('app', 'Code'),
        'roles' => Yii::t('app', 'Roles'),
        'languages' => Yii::t('app', 'Languages'),
        'created_at' => Yii::t('app', 'Created At'),
        'max_cafe' => Yii::t('app', 'Max cafe count'),
        'tariff_id' => Yii::t('app', 'Tariff'),

        'roles_ids' => Yii::t('app', 'Roles'),
        'language_ids' => Yii::t('app', 'Languages'),
    ];
  }

  /**
   * Return array of franchisee with id => name
   */
  public static function getList()
  {
    return ArrayHelper::map(self::find()->asArray()->all(), 'id', 'name');
  }

  public function afterFind()
  {
    if (strlen($this->roles) > 0) {
      $roles = explode(',', $this->roles);
      foreach ($roles as $role) {
        $this->roles_ids[$role] = $role;
      }
    } else {
      $this->roles_ids = [];
    }

    if (strlen($this->languages) > 0) {
      $languages = explode(',', $this->languages);
      foreach ($languages as $language) {
        $this->language_ids[$language] = $language;
      }
    } else {
      $this->language_ids = [];
    }

    parent::afterFind(); // TODO: Change the autogenerated stub
  }

  public function validate($attributeNames = null, $clearErrors = true)
  {
    $valid = parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub

    if (!empty($this->id)) {
      $count_cafe = Cafe::find()
          ->andWhere([
              'franchisee_id' => $this->id
          ])->count();

      if ($this->max_cafe < $count_cafe) {
        $this->addError('max_cafe', Yii::t('app', 'The maximum number of cafes can not be less than the current. The current number of cafes {n}', [
            'n' => $count_cafe
        ]));
        return false;
      }
    }
    return $valid;
  }

  public function beforeSave($insert)
  {
    $this->roles = implode(',', is_array($this->roles_ids) ? $this->roles_ids : []);
    $this->languages = implode(',', is_array($this->language_ids) ? $this->language_ids : []);

    if ($this->isNewRecord) {
      if (empty($this->created_at)) {
        $this->created_at = date("Y-m-d H:i:s");
      }
    }
    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }

  public function load($data, $formName = null)
  {
    if (!$formName) {
      $formName = $this->formName();
    }
    if (isset($data[$formName]['role_ids'])) {
      $this->roles = implode(',', array_filter($data[$formName]['role_ids']));
      $this->roles_ids = explode(',', $this->roles);
    }

    return parent::load($data, $formName); // TODO: Change the autogenerated stub
  }

  public function getRolesArray()
  {
    return explode(',', $this->roles);
  }

  public function getDiscounts()
  {
    $key = Discount::DISCOUNT_KEY;
    return (isset($this->data[$key]) && is_array($this->data[$key])) ? $this->data[$key] : [];
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getCafes()
  {
    return $this->hasMany(Cafe::className(), ['franchisee_id' => 'id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getUsers()
  {
    return $this->hasMany(Users::className(), ['franchisee_id' => 'id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getVisitors()
  {
    return $this->hasMany(Visitor::className(), ['franchisee_id' => 'id']);
  }

  public function getCafeCount()
  {
    return $this->getCafes()->count();
  }

  public function getBalans()
  {
    $balans = 0;
    $tariff = $this->tariff_id ?
        FranchiseeTariffs::find()
            ->where(['id' => $this->tariff_id])
            ->one() : null;

    if ($tariff && !empty($this->active_until)) {
      $days = (strtotime($this->active_until) - time()) / (60 * 60 * 24);
      //$days = ceil($days);
      $days = floor($days);
      $balans = $days * $tariff->day_price;
    }
    return round($balans, 2);
  }
}
