<?php

namespace frontend\modules\franchisee\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "{{%franchisee_tariffs}}".
 *
 * @property int $id ID
 * @property string $cafe_count
 * @property string $roles
 * @property double $day_price
 * @property int $days_period
 * @property int $active
 * @property string $created_at
 */
class FranchiseeTariffs extends \yii\db\ActiveRecord
{

  const ACTIVE_NO = 0;  //not_active
  const ACTIVE_YES = 1;  //active
  const ACTIVE_WAITING = 2;

  const LABEL_NO = 0;
  const LABEL_BEST_PRICE = 1;


  /**
   * @var role_ids
   */
  public $role_ids = [];

  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return '{{%franchisee_tariffs}}';
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
        [['roles', 'day_price', 'days_period', 'cafe_count'], 'required'],
        [['day_price'], 'number'],
        [['role_ids', 'description', 'name'], 'safe'],
        [['days_period', 'active', 'cafe_count', 'label'], 'integer'],
        [['created_at'], 'string', 'max' => 255],
        [['roles'], 'string'],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
        'id' => Yii::t('app', 'ID'),
        'name' => Yii::t('app', 'TariffLanding'),
        'description' => Yii::t('app', 'Tariff description'),
        'cafe_count' => Yii::t('app', 'Cafe count'),
        'roles' => Yii::t('app', 'Rules'),
        'role_ids' => Yii::t('app', 'Rules'),
        'day_price' => Yii::t('app', 'Day price'),
        'days_period' => Yii::t('app', 'Days period'),
        'active' => Yii::t('app', 'Activity'),
        'created_at' => Yii::t('app', 'Created at'),
        'label' => Yii::t('app', 'Label'),
		'price' => ''.Yii::t('app', 'PriceTariffFranchisee').', USD($)',
    ];
  }

  public static function getActiveLabels($index = null)
  {
    $items = [
        self::ACTIVE_NO => Yii::t('app', 'Non active'),
        self::ACTIVE_YES => Yii::t('app', 'Active'),
      //self::ACTIVE_WAITING => Yii::t('app', 'waiting'),
    ];

    if ($index !== null) {
      return isset($items[$index]) ? $items[$index] : 'Unknown';
    }
    return $items;
  }

  public static function getLabelsLabels($index = false)
  {
    $items = [
        self::LABEL_NO => Yii::t('app', 'no label'),
        self::LABEL_BEST_PRICE => Yii::t('app', 'Best price'),
      //self::ACTIVE_WAITING => Yii::t('app', 'waiting'),
    ];

    if ($index !== false) {
      return isset($items[$index]) ? $items[$index] : '-';
    }
    return $items;
  }

  public function beforeValidate()
  {
    if (strpos($this->className(), 'Search')) return parent::beforeValidate();
    $this->roles = implode(',', array_filter($this->role_ids));

    if ($this->isNewRecord) {
      $this->created_at = date("Y-m-d H:i:s");
    }
    return parent::beforeValidate(); // TODO: Change the autogenerated stub
  }

  public function afterFind()
  {
    if (empty($this->roles)) {
      $this->role_ids = [];
    } else {
      $this->role_ids = explode(',', $this->roles);
    }

    if (!empty($this->description)) {
      $this->description = json_decode($this->description, true);
    } else {
      $this->description = [];
    }

    if (!empty($this->name)) {
      $this->name = json_decode($this->name, true);
    } else {
      $this->name = [];
    }
    parent::afterFind(); // TODO: Change the autogenerated stub
  }

  public function beforeSave($insert)
  {
    if (!empty($this->description)) {
      $this->description = json_encode($this->description);
    } else {
      $this->description = '';
    }
    if (!empty($this->name)) {
      $this->name = json_encode($this->name);
    } else {
      $this->name = '';
    }
    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }

  public function afterSave($insert, $changedAttributes)
  {
    if (!empty($this->description)) {
      $this->description = json_decode($this->description, true);
    } else {
      $this->description = [];
    }

    if (!empty($this->name)) {
      $this->name = json_decode($this->name, true);
    } else {
      $this->name = [];
    }

    parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
  }

  public function getLgDescription($lg = false)
  {
    if (!$lg) {
      $lg = Yii::$app->language;
    }

    $description = $this->description;
    if (
        empty($description) ||
        !isset($description[$lg])
    ) {
      return '';
    }

    return $description[$lg];
  }

  public function getLgName($lg = false)
  {
    if (!$lg) {
      $lg = Yii::$app->language;
    }

    $name = $this->name;
    if (
        empty($name) ||
        !isset($name[$lg])
    ) {
      return '';
    }

    return $name[$lg];
  }

  public function getPrice($cnt = 1)
  {
    return round($this->day_price * $this->days_period * $cnt,2);
  }

  public function load($data, $formName = null)
  {
    $res = parent::load($data, $formName); // TODO: Change the autogenerated stub

    if (empty($formName)) {
      $formName = $this->formName();
    }
    if (!empty($data[$formName]['price'])) {
      $this->day_price = $data[$formName]['price'] / $this->days_period;
    }

    return $res;
  }

  static function getList()
  {
    $list = self::find()
        ->asArray()
        ->select(['id', 'name'])
        ->orderBy([
            'active' => SORT_DESC,
            'id' => SORT_DESC
        ])
        ->all();
    $list = ArrayHelper::map($list, 'id', 'name');

    $lg = Yii::$app->language;

    foreach ($list as &$item) {
      $item = json_decode($item, true);
      $item = $item[$lg];
    }

    return $list;
  }
}
