<?php

namespace frontend\modules\tasks\models;

use Yii;

/**
 * This is the model class for table "task".
 *
 * @property int $id
 * @property int $cafe
 * @property int $type
 * @property int $active
 * @property int $start_date
 * @property int $start_time
 * @property int $end_time
 * @property int $period
 * @property string $text
 * @property int $weak_n
 * @property int $weekday
 */
class Task extends \common\components\ActiveRecord
{

  const TYPE_ONCE = 1;
  const TYPE_EVERYDAY = 6;
  const TYPE_WEAKLY = 3;
  const TYPE_MONTH_WEAKLY = 4;
  const TYPE_MONTH_DAY = 5;

  const NOT_ACTIVE = 0;
  const ACTIVE = 1;

  public $todayDo = false;

  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return 'task';
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
        [['cafe_id', 'type', 'active', 'period', 'weak_n', 'weekday'], 'integer'],
        [['text', 'type', 'active', 'start_date', 'start_time', 'end_time'], 'required'],
        [['text', 'start_date', 'start_time', 'end_time'], 'string'],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
        'id' => Yii::t('app', 'ID'),
        'cafe_id' => Yii::t('app', 'Cafe'),
        'type' => Yii::t('app', 'Type'),
        'active' => Yii::t('app', 'Activity'),
        'start_date' => Yii::t('app', 'Start Date'),
        'start_time' => Yii::t('app', 'Start Time'),
        'end_time' => Yii::t('app', 'End Time'),
        'period' => Yii::t('app', 'Period'),
        'text' => Yii::t('app', 'Task'),
        'weak_n' => Yii::t('app', 'Ordinal number'),
        'weekday' => Yii::t('app', 'Weekday'),
        'periodText' => Yii::t('app', 'Period'),
        'status' => Yii::t('app', 'Status'),
        'user_id' => Yii::t('app', 'Closed by'),
        'comment' => Yii::t('app', 'Comment'),
    ];
  }

  public static function getTypes($index = null)
  {
    $labels = [
        self::TYPE_ONCE => Yii::t('app', 'Once'),
        self::TYPE_EVERYDAY => Yii::t('app', 'Everyday'),
        self::TYPE_WEAKLY => Yii::t('app', 'Weekly'),
        self::TYPE_MONTH_WEAKLY => Yii::t('app', 'Monthly (weekday)'),
        self::TYPE_MONTH_DAY => Yii::t('app', 'Monthly (day)'),
    ];

    if ($index !== null) {
      return isset($labels[$index]) ? $labels[$index] : Yii::t('app', 'Unknown');
    } else {
      return $labels;
    }
  }

  public static function getActive($index = null)
  {
    $labels = [
        self::ACTIVE => Yii::t('app', 'Active'),
        self::NOT_ACTIVE => Yii::t('app', 'Non active'),
    ];

    if ($index !== null) {
      return isset($labels[$index]) ? $labels[$index] : Yii::t('app', 'Unknown');
    } else {
      return $labels;
    }
  }

  public function validate($attributeNames = null, $clearErrors = true)
  {
    $res = parent::validate($attributeNames, $clearErrors);

    if (strpos($this->formName(), 'Search') === false) {
      if (!is_numeric($this->start_time)) {
        $date = \DateTime::createFromFormat(Yii::$app->params['lang']['time'], $this->start_time);
        $start_time = $date->getTimestamp();
      }

      if (!is_numeric($this->end_time)) {
        $date = \DateTime::createFromFormat(Yii::$app->params['lang']['time'], $this->end_time);
        $end_time = $date->getTimestamp();
      }

      if ($start_time > $end_time) {
        $this->addError('end_time', Yii::t('app', 'The end time of the visit should be longer than the start time.'));
        return false;
      }
    }

    return $res;
  }

  public function beforeSave($insert)
  {
    $this->cafe_id = Yii::$app->cafe->id;

    if (!is_numeric($this->start_date)) {
      $date = \DateTime::createFromFormat(Yii::$app->params['lang']['date'], $this->start_date);
      $this->start_date = DATE('Y-m-d', $date->getTimestamp());
    }

    if (!is_numeric($this->start_time)) {
      $date = \DateTime::createFromFormat(Yii::$app->params['lang']['time'], $this->start_time);
      $this->start_time = DATE('H:i:s', $date->getTimestamp());
    }

    if (!is_numeric($this->end_time)) {
      $date = \DateTime::createFromFormat(Yii::$app->params['lang']['time'], $this->end_time);
      $this->end_time = DATE('H:i:s', $date->getTimestamp());
    }

    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }

  public function getPeriodText()
  {

    $wd_list = [
        0 => 'Su',
        1 => 'Mo',
        2 => 'Tu',
        3 => 'We',
        4 => 'Th',
        5 => 'Fr',
        6 => 'Sa',
    ];

    if ($this->type == 3) {
      return Yii::t('app', 'Every {weekday}', [
          'weekday' => Yii::t('app', $wd_list[$this->weekday])
      ]);
    }

    if ($this->type == 4) {
      if ($this->weak_n > 0) {
        return Yii::t('app', 'Every {n}nd (from the stаrt of the month) {weekday}', [
            'n' => $this->weak_n,
            'weekday' => Yii::t('app', $wd_list[$this->weekday]),
        ]);
      } else {
        return Yii::t('app', 'Every {n}nd (from the end of the month) {weekday}', [
            'n' => -$this->weak_n,
            'weekday' => Yii::t('app', $wd_list[$this->weekday]),
        ]);
      }
    }

    if ($this->type == 5) {
      if ($this->weak_n > 0) {
        return Yii::t('app', 'Every {n}nd day (from the start of the month) of the month', [
            'n' => $this->weak_n,
        ]);
      } else {
        return Yii::t('app', 'Every {n}nd day (from the end of the month)', [
            'n' => -$this->weak_n,
        ]);
      }
    }

    return '';
  }

  public static function findToDate($date_unix = false, $query = false, $asArray = false, $onlyActive = true)
  {
    if (!$date_unix) $date_unix = time();
    if (!$query) $query = self::find();

    $date = DATE('Y-m-d', $date_unix);

    Yii::$app->params['task_data'] = $date;

    $query->orWhere([
        'and',
        ['type' => 1,
            'start_date' => $date,
        ]
    ]);

    $query->orWhere([
        'and',
        ['=', 'type', 6],
        ['<=', 'start_date', $date],
    ]);

    $query->orWhere([
        'and',
        ['=', 'type', 7],
        'DAYOFWEEK(start_date)=DAYOFWEEK(\'' . $date . '\')',
    ]);

    //Monthly (weekday)
    $n = date('N', $date_unix);
    $query->orWhere([
        'and',
        ['=', 'type', 4],
        ['=', 'weak_n', floor((date('d') - $n) / 7 + 1)],
    ]);
    $query->orWhere([
        'and',
        ['=', 'type', 4],
        ['=', 'weak_n', -(floor((date('t', $date_unix) - date('d', $date_unix)) / 7) + 1)],
    ]);

    //Monthly (day)
    $n = date('d', $date_unix);
    $query->orWhere([
        'and',
        ['=', 'type', 5],
        ['=', 'weak_n', $n],
    ]);
    $query->orWhere([
        'and',
        ['=', 'type', 5],
        ['=', 'weak_n', ($n - date('t', $date_unix) - 1)],
    ]);

    $query->andWhere([
        'task.cafe_id' => Yii::$app->cafe->id,
    ]);

    if ($onlyActive) {
      $query->andWhere([
          'task.active' => self::ACTIVE
      ]);
    }

    if ($asArray) {
      $query->leftJoin('do_task', 'do_task.task_id=task.id AND DATE(do_task.`datetime`)=\'' . $date . '\'');
      $query->leftJoin('user', 'user.id=do_task.user_id');
      $query->asArray();
      $query->select(['task.*, do_task.closedate,do_task.status,user.name,IF(end_time<\'' . date("H:i:s") . '\',1,0) as time_up,IF(start_time<\'' . date("H:i:s") . '\',1,0) as is_start,do_task.id as do_id']);
    }

    return $query;
  }

  public static function waitToDo()
  {

    //Стартуем таски если пришло время
    $mast_start = self::findToDate(false, false, true)
        ->andHaving([
            'and',
            ['is_start' => 1],
            ['is', 'do_id', null]
        ])->all();
    if ($mast_start) {
      foreach ($mast_start as $task) {
        $do = new DoTask();
        $do->cafe_id = Yii::$app->cafe->id;
        //$do->user_id = Yii::$app->user->id;
        $do->text = $task['text'];
        $do->task_id = $task['id'];
        $do->datetime = date('Y-m-d H:i:s');
        $do->status = DoTask::STATUS_IN_WORK;
        $do->save();
      }
    }

    //Закрываем таски если закончилось время
    $mast_finish = self::findToDate(false, false, true)
        ->andHaving([
            'and',
            ['time_up' => 1],
        ])->all();
    if ($mast_finish) {
      foreach ($mast_finish as $task) {
        $do = false;
        if ($task['do_id']) {
          $do = DoTask::find()
              ->where(['id' => $task['do_id']])
              ->one();
        }
        if (!$do) {
          $do = new DoTask();
          $do->cafe_id = Yii::$app->cafe->id;
          //$do->user_id = Yii::$app->user->id;
          $do->task_id = $task['id'];
          $do->datetime = date('Y-m-d H:i:s');
        }
        if (empty($do->text)) {
          $do->text = $task['text'];
        }
        $do->status = DoTask::STATUS_TIME_UP;
        $do->closedate = date('Y-m-d H:i:s');
        $do->save();
      }
    }

    //ищим таски для выводов
    $do = self::findToDate(false, false, true)
        //->andWhere(['<','start_time',date ("H:i:s")])
        ->andHaving([
            'and',
            ['is_start' => 1],
            ['is not', 'do_id', null]
        ])
        ->all();


    return self::getExportData($do, 'wait_do');
  }

  public static function getExportData($do, $template)
  {
    $out = [];

    if ($template) {
      $template = file_get_contents(Yii::$app->viewPath . '/' . $template . '.twig');
    };

    foreach ($do as $task) {
      if (!in_array($task['status'], [DoTask::STATUS_IN_WORK, null])) continue;

      if ($template) {
        //$visitor = Yii::$app->viewPath;
        $task['code'] = md5('task_' . $task['id']);
        $task = [
            'msg' => Yii::$app->TwigString->render($template, $task),
            'code' => $task['code'],
            'title' => '<div class="mod_task_title">' . Yii::t('app', 'Task') . ' <i class="fa fa-bell-o beller"></i><a type="button" aria-hidden="true" class="close btn but_hide" data-notify="dismiss"><div class="text_but_task">' . Yii::t('main', 'hide') . '</div><i class="icon-metro-cancel-2 abba"></i></a></div>'
        ];
      }
      $out[] = $task;
    }

    return $out;
  }

  private function getDo()
  {
    if (!$this->todayDo) {
      if (empty(Yii::$app->params['task_data'])) return false;
      $this->todayDo = DoTask::find()
          ->where('date(`datetime`)=\'' . Yii::$app->params['task_data'] . '\'')
          ->andWhere(['task_id' => $this->id])
          ->one();

    }
    return $this->todayDo;
  }

  public function getStatus()
  {
    $d = $this->getDo();
    if ($d === false) return Yii::t('app', 'error');
    if (!$d) return -1;
    return $d->status;
  }

  public function getComment()
  {
    $d = $this->getDo();
    if (!$d) return '';
    return $d->comment;
  }

  public function getCloseDateStr()
  {
    $d = $this->getDo();
    if (!$d) return '';
    if (!$d->closedate) return '';

    $date = strtotime($d->closedate);
    return date(Yii::$app->params['lang']['time'], strtotime($d->closedate));
  }

  public function getUserDo()
  {
    $d = $this->getDo();
    if (!$d) return '';
    if (!$d->closedate) return '';

    return $d->user;
  }

  public static function test($fullResult = true)
  {
    if (!$fullResult) {
      return true;
    }

    $data = [
        'title' => 'Task',
        'description' => 'Task description',
        'icon' => 'icon-metro-alarm',
        'buttons' => [
            [
                'name' => 'add',
                'modal' => true,
                'href' => '/tasks/admin/create'
            ]
        ],
    ];

    $tasks = Task::find()
        ->where([
            'task.cafe_id' => Yii::$app->cafe->id,
        ])
        ->select('active as task_active,count(id) as cnt')
        ->groupBy('active')
        ->asArray()
        ->all();

    $out = [];
    foreach ($tasks as $task) {
      $task['task_active'] = self::getActive($task['task_active']);
      $out[] = Yii::t('config', "total in {task_active}: {cnt}", $task);
    }

    $tasks = self::findToDate()
        ->leftJoin('do_task', 'do_task.task_id=task.id AND DATE(do_task.`datetime`)=\'' . DATE('Y-m-d') . '\'')
        ->select('do_task.status,count(task.id) as cnt')
        ->groupBy('status')
        ->asArray()
        ->all();

    foreach ($tasks as $task) {
      if (is_null($task['status'])) $task['status'] = -1;
      $task['task_status'] = DoTask::getStatus($task['status']);
      $out[] = Yii::t('config', "today in {task_status}: {cnt}", $task);
    }
    $data['infoline'] = implode('<br>', $out);
    return $data;
  }
}
