<?php

namespace frontend\modules\tasks\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;

/**
 * TaskSearch represents the model behind the search form of `frontend\modules\tasks\models\Task`.
 */
class TaskSearch extends Task
{

  public $date;
  public $status;
  public $user_id;

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
        [['id', 'cafe_id', 'type', 'active', 'period', 'weak_n', 'weekday', 'user_id'], 'integer'],
        [['start_date', 'start_time', 'end_time', 'text', 'date', 'status'], 'safe'],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function scenarios()
  {
    // bypass scenarios() implementation in the parent class
    return Model::scenarios();
  }

  /**
   * Creates data provider instance with search query applied
   *
   * @param array $params
   *
   * @return ActiveDataProvider
   */
  public function search($params)
  {
    $query = Task::find();

    // add conditions that should always apply here

    $dataProvider = new ActiveDataProvider([
        'query' => $query,
        'sort' => array(
            'defaultOrder' => [
                'active' => SORT_DESC,
                'id' => SORT_DESC,
            ]
        ),
    ]);

    $this->load($params);

    if (!$this->validate()) {
      // uncomment the following line if you do not want to return any records when validation fails
      // $query->where('0=1');
      return $dataProvider;
    }


    $date_unix = \DateTime::createFromFormat(Yii::$app->params['lang']['date'], $this->date)->getTimestamp();

    Task::findToDate($date_unix, $query, false, false);

    // grid filtering conditions
    $query->andFilterWhere([
        'id' => $this->id,
        'cafe_id' => $this->cafe_id,
        'type' => $this->type,
        'active' => $this->active,
      //'start_time' => $this->start_time,
      //'end_time' => $this->end_time,
        'period' => $this->period,
        'weak_n' => $this->weak_n,
        'weekday' => $this->weekday,
    ]);

    $query->andFilterWhere(['like', 'text', $this->text]);


    $nead_do_table = false;
    if (is_numeric($this->status)) {
      if ($this->status == -1) {
        $query->andWhere(['status' => null]);
      } else {
        $query->andWhere(['status' => $this->status]);
      }
      //ddd($this->status);

      $nead_do_table = true;
    }

    if (is_numeric($this->user_id)) {
      if ($this->status == -1) {
        $query->andWhere(['do_task.user_id' => null]);
      } else {
        $query->andWhere(['do_task.user_id' => $this->user_id]);
      }

      $nead_do_table = true;
    }


    if ($nead_do_table) {
      $query->leftJoin('do_task', 'do_task.task_id=task.id AND DATE(do_task.`datetime`)=\'' . DATE('Y-m-d', $date_unix) . '\'');
    }

    if (!empty($this->start_date)) {
      if (!is_numeric($this->start_date)) {
        $start_date = explode(' - ', $this->start_date);
        //ddd($this->start_date);
        foreach ($start_date as &$t) {
          $date = \DateTime::createFromFormat(Yii::$app->params['lang']['date'], $t)->getTimestamp();
          $t = DATE('Y-m-d', $date);
        }

        $query
            ->andFilterWhere(['>=', 'start_date', $start_date[0]])
            ->andFilterWhere(['<=', 'start_date', $start_date[1]]);
      }
    };


    return $dataProvider;
  }


  public function beforeValidate()
  {
    if (empty($this->date)) {
      $this->date = date(Yii::$app->params['lang']['date']);
    }
    return parent::beforeValidate(); // TODO: Change the autogenerated stub
  }
}
