<?php

namespace frontend\modules\shop\controllers;

use common\components\widget\BulkButtonWidget;
use frontend\components\Controller;
use frontend\modules\shop\models\ShopProduct;
use frontend\modules\shop\models\ShopProductSearch;
use frontend\modules\shop\models\ShopTransaction;
use frontend\modules\shop\models\ShopTransactionSearch;
use Yii;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * InventoryController implements the CRUD actions for ShopProduct model.
 */
class InventoryController extends Controller
{

  private $is_shop = false;
  private $col_cash = "columns_ShopInventory";

  private $def_sel_column_shop = [
      'id',
      'title',
      'barcode',
      'quantity'
  ];

  private $def_sel_column = [
      'id',
      'image',
      'title',
      'weight',
      'category_id',
      'supplier_id',
      'price',
      'quantity'
  ];

  /**
   * @inheritdoc
   */
  public function behaviors()
  {
    return [
        'verbs' => [
            'class' => VerbFilter::className(),
            'actions' => [
                'delete' => ['post'],
                'bulk-delete' => ['post'],
            ],
        ],];
  }

  public function createAction($id)
  {
    if ($id == "shop" || $id == 'columns_shop') {
      $this->is_shop = true;
      $id = $id == "shop" ? "index" : "columns";
      $this->col_cash = "columns_ShopInventory_shop";
      if (Yii::$app->user->isGuest || !Yii::$app->cafe->can("shopAll")) {
        throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
        return false;
      }
    }else{
      if (Yii::$app->user->isGuest || !Yii::$app->cafe->can("merchandiseAll")) {
        throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
        return false;
      }
    }


    return parent::createAction($id); // TODO: Change the autogenerated stub
  }

  /**
   * Lists all ShopProduct models.
   * @return mixed
   */
  public function actionIndex()
  {
    if (!Yii::$app->user->can('ShopInventoryView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $searchModel = new ShopProductSearch();
    $searchModel->is_shop = $this->is_shop;
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    $canCreate = Yii::$app->user->can('ShopInventoryCreate') && $this->is_shop;
    $actions = "";
    $actions .= Yii::$app->user->can('ShopInventoryUpdate') ? "{update}" : "";
    $actions .= Yii::$app->user->can($this->is_shop?'ShopInventoryDelete':'ShopInventoryDelete') ? "{delete}" : "";
    $panelButtons = '';
    if (Yii::$app->user->can($this->is_shop?'ShopInventoryDelete':'ShopInventoryDelete')) {
      $panelButtons = BulkButtonWidget::widget(['urlPrefix' => '/shop/catalog/']);
    };
    $columns = include(__DIR__ . '/../views/inventory/_columns.php');
    if (Yii::$app->user->isGuest) {
      $sel_column = Yii::$app->session->get($this->col_cash, false);
    } else {
      $user = Yii::$app->getUser()->getIdentity();
      $sel_column = $user->getActiveColumn($this->col_cash);
    }
    if (!$sel_column) {
      $sel_column = $this->is_shop ? $this->def_sel_column_shop : $this->def_sel_column;
    }
    foreach ($columns as $k => $column) {
      $column_name = !is_array($column) ? $column : (isset($column['attribute']) ? $column['attribute'] : false);
      if ($column_name && !in_array($column_name, $sel_column)) {
        unset($columns[$k]);
      }
    }

    if ($this->is_shop) {
      $searchSale = new ShopTransactionSearch();
      $searchSale->operation_type_id = ShopTransaction::OPERATION_TYPE_SALE;
      $searchSale->search([]);
    } else {
      $searchSale = false;
    }

    return $this->render('index', [
        'searchModel' => $searchModel,
        'dataProvider' => $dataProvider,
        'columns' => $columns,
        'canCreate' => $canCreate,
        'panelButtons' => $panelButtons,
        'title' => Yii::t('app', $this->is_shop ? 'Shop Inventory' : 'ShopProduct list'),
        'is_shop' => $this->is_shop,
        'sales' => $searchSale,
        'inventory' => $searchModel,
    ]);
  }


  /**
   * Config column in ShopProduct model.
   * @param integer $id
   * @return mixed
   * @throws NotFoundHttpException if the model cannot be found
   */
  public function actionColumns()
  {
    if (!Yii::$app->user->can('ShopInventoryView')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    $model = new ShopProduct();
    $searchModel = new ShopProductSearch();

    $request = Yii::$app->request;

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    Yii::$app->response->format = Response::FORMAT_JSON;

    if ($request->post('column')) {
      $col = $request->post('column');

      if (Yii::$app->user->isGuest) {
        Yii::$app->session->set($this->col_cash, $col);
      } else {
        $user = Yii::$app->getUser()->getIdentity();
        $user->setActiveColumn($this->col_cash, $col);
      }

      return [
          'forceClose' => 'true',
          'forceReload' => '#crud-datatable-pjax',
          'content' => Yii::$app->view->closeModal(),
      ];
    }
    $actions = "";
    $columns = include(__DIR__ . '/../views/inventory/_columns.php');
    if (Yii::$app->user->isGuest) {
      $sel_column = Yii::$app->session->get($this->col_cash, false);
    } else {
      $user = Yii::$app->getUser()->getIdentity();
      $sel_column = $user->getActiveColumn($this->col_cash);
    }
    if (!$sel_column) {
      $sel_column = $this->is_shop ? $this->def_sel_column_shop : $this->def_sel_column;
    }
    foreach ($columns as $k => $column) {
      $column_name = !is_array($column) ? $column : (isset($column['attribute']) ? $column['attribute'] : false);
      if (!$column_name) {
        unset($columns[$k]);
      } else {
        $columns[$k] = $column_name;
      }
    }

    return [
        'title' => Yii::t('app', 'Change visible columns in ShopProduct table'),
        'content' => $this->renderAjax('columns', [
            'sel_column' => $sel_column,
            'columns' => $columns,
            'model' => $model,
            'isAjax' => true,
        ]),
        'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
            Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"]),

    ];
  }

  /**
   * Updates an existing ShopProduct model.
   * For ajax request will return json object
   * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
   * @param integer $id
   * @return mixed
   */
  public function actionUpdate($id)
  {
    if (!Yii::$app->user->can('ShopInventoryUpdate')) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $request = Yii::$app->request;
    $model = $this->findModel($id);

    if (!$request->isAjax) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }
    /*
    *   Process for ajax request
    */
    $title = Yii::t('app', 'Update Shop Product: {title}', [
        'title' => '' . $model->title,
    ]);
    Yii::$app->response->format = Response::FORMAT_JSON;
    if ($request->isGet) {
      return [
          'title' => $title,
          'content' => $this->renderAjax('update', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"]),
      ];
    } else if ($model->load($request->post()) && $model->save()) {
      return $this->returnBlank(
          [
              'forceReload' => '#crud-datatable-pjax',
              'title' => $title,
          ],
          Yii::t('app', 'Update Shop Product updated successfully')
      );
    } else {
      return [
          'title' => $title,
          'content' => $this->renderAjax('update', [
              'model' => $model,
              'isAjax' => true,
          ]),
          'footer' => Html::button(Yii::t('app', 'Close'), ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
              Html::button(Yii::t('app', 'Save'), ['class' => 'btn btn-primary', 'type' => "submit"]),
      ];
    }
  }

  /**
   * Finds the ShopProduct model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param integer $id
   * @return ShopProduct the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id)
  {
    if (($model = ShopProduct::findOne($id)) !== null) {
      return $model;
    } else {
      throw new NotFoundHttpException(Yii::t('app', 'Page does not exist'));
    }
  }
}
