<?php

namespace frontend\helpers;

use yii\helpers\ArrayHelper;
use yii\helpers\Html;

class MyHtml extends Html
{
  public static function checkboxList($name, $selection = null, $items = [], $options = [])
  {
    $itemOptions = isset($options['itemOptions']) ? $options['itemOptions'] : [];
    $encode = ArrayHelper::getValue($options, 'encode', true);
    $options['item'] = function ($index, $label, $name, $checked, $value) use ($itemOptions, $encode) {
      $options = array_merge([
          'label' => Html::tag('span', '', ['class' => 'fa fa-check']) . ' ' . ($encode ? Html::encode($label) : $label),
          'value' => $value
      ], $itemOptions);
      return '<div class="checkbox">' . Html::checkbox($name, $checked, $options) . '</div>';
    };
    return parent::checkboxList($name, $selection, $items, $options); // TODO: Change the autogenerated stub
  }
}