<?php

namespace frontend\modules\cafe\controllers;

use frontend\components\Controller;
use frontend\modules\cafe\models\Cafe;
use frontend\modules\visits\models\VisitorLog;
use Yii;

/**
 * AdminController implements the CRUD actions for Cafe model.
 */
class TerminalController extends Controller
{
  public function actions()
  {
    $this->enableCsrfValidation = false;
    return parent::actions(); // TODO: Change the autogenerated stub
  }

  public function actionIndex()
  {
    $data = Yii::$app->request->post('data');
    $key = Yii::$app->request->post('key');

    $code = array(
        'sum' => $data['sum'],
        'time' => $data['time'],
    );

    
    $code = md5(http_build_query($code));

    $cafe = Cafe::find()
        ->limit(1)
        ->where('md5(CONCAT(:code,api_key))=:key',
            [
                'code' => $code,
                'key' => $key,
            ]
        )->one();

    if (!$cafe) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    $visit = VisitorLog::find()
        ->andWhere([
            'cafe_id' => $cafe->id,
            'id' => $data['order']
        ])
        ->one();

    if (!$visit) {
      throw new \yii\web\ForbiddenHttpException(Yii::t('app', 'Page does not exist'));
      return false;
    }

    Yii::$app->cafe->start($cafe->id);

    $visit->finish_time = date("Y-m-d H:i:s", $data['time']);
    $visit->tip = $data['tip'] / 100;
    $visit->terminal_ans = 1;
    $visit->pay_state = VisitorLog::PAY_METHOD_CARD;
    $visit->endPause();
    $visit->calcCost();


	//  echo $visit->finish_time."\n";

    if ($visit->save()) {
	//if(true){
      return 'SUMM OK';
    } else {
      return 'save ERROR';
    }
  }
}
