<?php

namespace frontend\modules\polls\models;

use frontend\modules\cafe\models\Cafe;
use frontend\modules\users\models\Users;
use Yii;

/**
 * This is the model class for table "polls".
 *
 * @property int $id
 * @property string $question
 * @property string $answers
 * @property int $status
 * @property int $user_id
 * @property string $created
 * @property int $other_ans
 * @property int $user_status
 * @property int $event
 * @property int $cafe_id
 * @property int $is_poll
 *
 * @property User $user
 * @property Cafe $cafe
 * @property PollsAns[] $pollsAns
 */
class Polls extends \common\components\ActiveRecord
{

  const STATUS_ACTIVE = 1;
  const STATUS_HIDDEN = 0;

  const OTHER_ANS_SHOW = 1;
  const OTHER_ANS_HIDDEN = 0;

  const EVENT_START_VISIT = 0;
  const EVEVT_FINISH_VISIT = 1;

  const USER_SATATUS_NEW = 1;
  const USER_SATATUS_REGULAR = 2;
  const USER_SATATUS_ALL = -1;


  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return 'polls';
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
        [['question'], 'string'],
        [['status', 'user_id', 'other_ans', 'user_status', 'event', 'cafe_id', 'is_poll'], 'integer'],
        [['created', 'answers'], 'safe'],
        [['user_status', 'event', 'cafe_id'], 'required'],
        [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['user_id' => 'id']],
        [['cafe_id'], 'exist', 'skipOnError' => true, 'targetClass' => Cafe::className(), 'targetAttribute' => ['cafe_id' => 'id']],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
        'id' => Yii::t('app', 'ID'),
        'question' => Yii::t('app', 'Question'),
        'answers' => Yii::t('app', 'Answers'),
        'status' => Yii::t('app', 'Status'),
        'user_id' => Yii::t('app', 'Creator'),
        'created' => Yii::t('app', 'Created'),
        'other_ans' => Yii::t('app', 'Other Ans'),
        'user_status' => Yii::t('app', 'Show clients'),
        'event' => Yii::t('app', 'When displayed'),
        'cafe_id' => Yii::t('app', 'Cafe ID'),
        'is_poll' => Yii::t('app', 'Is Poll'),
    ];
  }

  public function afterFind()
  {
    if (is_array($this->answers)) {
      $ans = [];
      foreach ($this->answers as $k => $label) {
        if (!is_array($label)) {
          $label = [
              'answers' => $label,
              'id' => $k,
          ];
        }
        if (empty($label['id'])) $label['id'] = ($k + 1);
        $ans[] = $label;
      }
      $this->answers = $ans;
    } else {
      $this->answers = [];
    }
    parent::afterFind(); // TODO: Change the autogenerated stub
  }

  public function beforeValidate()
  {
    if (is_array($this->answers)) {
      $ans = [];
      $increment = false;
      foreach ($this->answers as $k => $label) {
        if (empty($label['answers'])) continue;
        if (empty($label['id'])) {

          if ($increment === false) {
            $increment = 0;
            if ($this->id) {
              $increment = PollsAns::find()
                  ->where(['poll_id' => $this->id])
                  ->select('max(ans) as m')
                  ->asArray()
                  ->groupBy('poll_id')
                  ->one();
              if (is_array($increment)) $increment = $increment['m'];
            }

            if (!$increment || $increment < 0) $increment = 0;
            foreach ($this->answers as $item) {
              if (
                  is_array($item) &&
                  !empty($item['id']) &&
                  $item['id'] > $increment
              ) {
                $increment = $item['id'];
              }
            }
          }


          $increment++;
          $label['id'] = $increment;
        }
        $ans[] = $label;
      }
      $this->answers = $ans;
    }

    return parent::beforeValidate(); // TODO: Change the autogenerated stub
  }

  public function beforeSave($insert)
  {

    if (!(Yii::$app instanceof Yii\console\Application)) {
      $this->cafe_id = Yii::$app->cafe->id;
    }

    if ($this->isNewRecord) {
      $this->created = DATE('Y-m-d H:i:s');
      $this->user_id = Yii::$app->user->id;
    }

    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getUser()
  {
    return $this->hasOne(Users::className(), ['id' => 'user_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getCafe()
  {
    return $this->hasOne(Cafe::className(), ['id' => 'cafe_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getPollsAns()
  {
    return $this->hasMany(PollsAns::className(), ['poll_id' => 'id']);
  }

  public static function getStatus($index = null)
  {
    $labels = [
        self::STATUS_ACTIVE => Yii::t('app', 'Active'),
        self::STATUS_HIDDEN => Yii::t('app', 'Non active'),
    ];

    if ($index !== null) {
      return isset($labels[$index]) ? $labels[$index] : Yii::t('app', 'Unknown');
    } else {
      return $labels;
    }
  }

  public static function getOtherAns($index = null)
  {
    $labels = [
        self::OTHER_ANS_SHOW => Yii::t('app', 'Active'),
        self::OTHER_ANS_HIDDEN => Yii::t('app', 'Non active'),
    ];

    if ($index !== null) {
      return isset($labels[$index]) ? $labels[$index] : Yii::t('app', 'Unknown');
    } else {
      return $labels;
    }
  }


  public static function getEvents($index = null)
  {
    $labels = [
        self::EVENT_START_VISIT => Yii::t('app', 'Start visit'),
        self::EVEVT_FINISH_VISIT => Yii::t('app', 'Finish visit'),
    ];

    if ($index !== null) {
      return isset($labels[$index]) ? $labels[$index] : Yii::t('app', 'Unknown');
    } else {
      return $labels;
    }
  }

  public static function getUserStatus($index = null)
  {
    $labels = [
        self::USER_SATATUS_ALL => Yii::t('app', 'ALL visitors'),
        self::USER_SATATUS_NEW => Yii::t('app', 'New visitors'),
        self::USER_SATATUS_REGULAR => Yii::t('app', 'Regular visitors'),
    ];

    if ($index !== null) {
      return isset($labels[$index]) ? $labels[$index] : Yii::t('app', 'Unknown');
    } else {
      return $labels;
    }
  }

  public function beforeDelete()
  {
    PollsAns::deleteAll(['poll_id' => $this->id]);
    return parent::beforeDelete(); // TODO: Change the autogenerated stub
  }
}
