<?php

namespace frontend\modules\templates\models;

use frontend\modules\cafe\models\Cafe;
use frontend\modules\cafe\models\CafeParams;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;

/**
 * This is the model class for table "{{%template}}".
 *
 * @property int $id
 * @property int $scope_id
 * @property int $cafe_id
 * @property int $franchisee_id
 * @property int $type_id
 * @property string $content
 * @property int $updated_at
 * @property int $created_at
 *
 * @property TemplateToCafe[] $templateToCafes
 * @property Cafe[] $cafes
 */
class Template extends \common\components\ActiveRecord
{
  const SCOPE_DEFAULT = 1;
  const SCOPE_FRANCHISEE = 2;
  const SCOPE_CAFE = 3;

  const TYPE_CHECK_PRINT = 1;
  const TYPE_CHECK_MAIL = 2;
  const TYPE_TIMETABLE_MAIL = 3;

  public $used_in_cafe_ids; // Used to select Cafes to use Template during Update

  private $config_files = [
      1 => 'var_check', //TYPE_CHECK_PRINT
      2 => 'var_check_mail', //TYPE_CHECK_MAIL
      3 => 'var_timetable_mail', //TYPE_TIMETABLE_MAIL
  ];
  private $_params = false;

  public $subject = false;

  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return '{{%template}}';
  }

  public function behaviors()
  {
    $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub

    $behaviors['timestamp'] = TimestampBehavior::class;

    return $behaviors;
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
        [['scope_id', 'type_id'], 'required'],
        [['scope_id', 'cafe_id', 'franchisee_id', 'type_id', 'updated_at', 'created_at', 'width'], 'integer'],
        [['content', 'background'], 'string'],
        ['type_id', 'validateUniqueTypeInScope', 'when' => function ($model) {
          return $model->scope_id == self::SCOPE_DEFAULT;
        }],
        [['used_in_cafe_ids'], 'safe'],
    ];
  }

  public function validateUniqueTypeInScope($attribute, $params)
  {
    $existsQuery = self::find()
        ->andWhere(['scope_id' => $this->scope_id])
        ->andWhere(['type_id' => $this->type_id]);

    if (!$this->isNewRecord) {
      $existsQuery->andWhere(['!=', 'id', $this->id]);
    }

    if ($existsQuery->exists()) {
      $this->addError($attribute, Yii::t('app', 'Template of this Type already exists in this Scope', [
          'attribute' => $attribute,
          'value' => $this->$attribute,
      ]));
    }
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
        'id' => Yii::t('app', 'ID'),
        'scope_id' => Yii::t('app', 'Scope'),
        'cafe_id' => Yii::t('app', 'Cafe'),
        'franchisee_id' => Yii::t('app', 'Franchisee'),
        'type_id' => Yii::t('app', 'Type'),
        'content' => Yii::t('app', 'Content'),
        'updated_at' => Yii::t('app', 'Updated At'),
        'created_at' => Yii::t('app', 'Created At'),
        'width' => Yii::t('app', 'Width'),
        'background' => Yii::t('app', 'Background'),
        'used_in_cafe_ids' => Yii::t('app', "Cafe list"),
    ];
  }

  public static function getTypeLabels($index = null)
  {
    $labels = [
        self::TYPE_CHECK_PRINT => Yii::t('app', 'Check to print'),
        self::TYPE_CHECK_MAIL => Yii::t('app', 'Check to mail'),
        self::TYPE_TIMETABLE_MAIL => Yii::t('app', 'Timetable to mail'),
    ];

    if ($index !== null) {
      return isset($labels[$index]) ? $labels[$index] : Yii::t('app', 'Unknown');
    } else {
      return $labels;
    }
  }

  public static function getScopeLabels($index = null)
  {
    $labels = [
        self::SCOPE_DEFAULT => Yii::t('app', 'Default'),
        self::SCOPE_FRANCHISEE => Yii::t('app', 'Franchisee'),
        self::SCOPE_CAFE => Yii::t('app', 'Cafe'),
    ];

    if ($index !== null) {
      return isset($labels[$index]) ? $labels[$index] : Yii::t('app', 'Unknown');
    } else {
      return $labels;
    }
  }

  public function setupScopeDependentParams()
  {
    $cafe = Yii::$app->cafe;

    if ($this->scope_id == self::SCOPE_CAFE) {
      $this->cafe_id = $cafe->getId();
      unset($this->franchisee_id);
    } elseif ($this->scope_id == self::SCOPE_FRANCHISEE) {
      unset($this->cafe_id);
      $this->franchisee_id = $cafe->getFranchiseeId();
    } else if ($this->scope_id == self::SCOPE_DEFAULT) {
      unset($this->cafe_id);
      unset($this->franchisee_id);
    }

    return true;
  }

  public static function findDefault($type_id)
  {
    return static::find()->andWhere([
        'scope_id' => self::SCOPE_DEFAULT,
        'type_id' => $type_id,
    ])->one();
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getTemplateToCafes()
  {
    return $this->hasMany(TemplateToCafe::className(), ['template_id' => 'id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getCafes()
  {
    return $this->hasMany(Cafe::className(), ['id' => 'cafe_id'])->viaTable('{{%template_to_cafe}}', ['template_id' => 'id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getCafe($cafe_id = null)
  {
    $query = $this->hasMany(Cafe::className(), ['id' => 'cafe_id'])
        ->viaTable('{{%template_to_cafe}}', ['template_id' => 'id'], function (ActiveQuery $q) use ($cafe_id) {
          if ($cafe_id !== null) {
            $q->andOnCondition('{{%template_to_cafe}}.cafe_id = :cafe_id', [
                ':cafe_id' => $cafe_id,
            ]);
          }
          return $q;
        });

    return $query;
  }

  public function getTemplate($language = false, $cafe_id = false)
  {
    if (!$language) {
      $language = Yii::$app->user->identity->lg;
    }
    if (!$cafe_id) {
      $cafe = Yii::$app->cafe->get();
      $params = Yii::$app->cafe->params;
    } else {
      $cafe = Cafe::find()->where(['id' => $cafe_id])->one();
      $params = CafeParams::find()->where(['id' => $cafe->params_id])->asArray()->one();
    }

    $tpl_params = $this->params;

    try {
      $content = json_decode($this->content, true);
    } catch (Exception $e) {
      $content = [];
    }

    if (isset($content['data'])) {
      if (isset($content['subject'][$language])) {
        $this->subject = $content['subject'][$language];
      }
      if(empty($this->subject)){
        $this->subject=$cafe->name;
      }

      if (isset($content['width'])) {
        $this->width = $content['width'];
      }

      if (isset($content['background'])) {
        $this->background = $content['background'];
      }

      $content = $content['data'];
    }

    $this_tpl_data = [
        "width" => $tpl_params['is_print'] ? $cafe->width . "mm" : $this->width . "px",
        "bg" => $tpl_params['is_print'] ? "#fff" : $this->background,
        'padding' => $tpl_params['is_print'] ? "0" : "0 0",
    ];


    $vat_list = $params['vat_list'];
    if (is_string($vat_list)) $vat_list = json_decode($vat_list, true);

    $content = $this->renderTemplateLevel($content, $language, $vat_list);
    //$content=$this->xmlpp($content);
    //ddd($content);
    $content = Yii::$app->TwigString->render(
        $content,
        $this_tpl_data
    );

    if ($this->_params['is_print']) {
      $content =
	      '<link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,700&display=swap&subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext" rel="stylesheet">' .
          //'<link href="//fonts.googleapis.com/css?family=Roboto+Mono:400,700&amp;subset=cyrillic,greek,latin-ext" rel="stylesheet">' .
          //'<link href="//fonts.googleapis.com/css?family=VT323" rel="stylesheet">' .
          $content;
    }

    $content = str_replace('}', '}}', $content);
    $content = str_replace('{', '{{', $content);
    $content = str_replace('\{{', '{', $content);
    $content = str_replace('\}}', '}', $content);
    $content = str_replace('{{\%', '{%', $content);
    $content = str_replace('%\}}', '%}', $content);

    if (!empty($this->_params['vars'])) {
      foreach ($this->_params['vars'] as $param) {
        if (!empty($param['wrap'])) {
          foreach ($param['wrap'] as $wrap => $vars) {
            foreach ($vars as $var) {
              $var = $param['prefix'] . $var;
              $content = str_replace($var, $wrap . '( ' . $var . ')', $content);
            }
          }
        }
        if (!empty($param['raw'])) {
          foreach ($param['raw'] as $var) {
            $content = str_replace($var, $var . '|raw', $content);
          }
        }

      }
    }

    // load our document into a DOM object
    /*$dom = new \DOMDocument();
    // we want nice output
    $dom->preserveWhiteSpace = false;
    $dom->loadHTML($content);
    $dom->formatOutput = true;
    return($dom->saveHTML());*/

    return $content;
  }

  static function renderTemplateLevel($data, $language = 'ru-RU', $vat_list = [], $level = 0)
  {
    $out = "";

    if (!is_array($data)) {
      $data = [];
    };

    $viewFolder = \Yii::getAlias('@frontend/views/editor') . '/';
    foreach ($data as $item) {
      $item['data']['language'] = $language;
      $item['data']['logo'] = '{ cafe.logo }';
      $item['data']['path'] = $viewFolder;
      $item['data']['vat_list'] = $vat_list;
      if (isset($item['sub_type'])) {
        $item['data']['sub_type'] = $item['sub_type'];
        if ($item['data']['sub_type'] == "total") {
          $item['data']['total_label'] = 'global_total';
        }
      }

      if ($item['type'] == "row") {
        foreach ($item['data']['items'] as $k => $el) {
          $item['data']['rows'][$k] = [
              'width' => $item['data']['rows'][$k],
              'content' => Template::renderTemplateLevel($el, $language, $vat_list, $level + 1)
          ];
        }
      }
      //d($item);
      $tpl = file_get_contents($viewFolder . $item['type'] . '.twig');

      $out .= '<tr>' . Yii::$app->TwigString->render(
              $tpl,
              $item['data']
          ) . '</tr>';
    }

    $out = '<table width="' . ($level == 0 ? "{{ width }}" : "100%") . '" border="0" cellpadding="0" cellspacing="0">' . $out . '</table>';

    if ($level == 0) {
      $out = '
      <title>{ cafe.name }</title><meta content="exported via StampReady" name="sr_export"><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
      <style type="text/css">
      html \{ width: 100%; \}
      body \{ -webkit-text-size-adjust: none; -ms-text-size-adjust: none; margin: 0; padding: 0; \}
      table \{ border-spacing: 0; border-collapse: collapse; margin:0 auto; \}
      img \{ display: block !important; \}
      </style>
      <table width="100%" border="0" cellpadding="0" cellspacing="0"' . ($level == 0 ? " style='background-color:{{ bg }};padding:{{ padding }};' bgcolor='{{ bg }}'" : "") . '><tr><td align="center" >' . $out . '</td></tr></table>';
    }
    return $out;
  }

  private function sum_cost($a, $b)
  {
    $a = str_replace(' ', '', $a);
    $b = str_replace(' ', '', $b);
    $v1 = preg_replace("/[^,.0-9]/", '', $a);
    $v2 = preg_replace("/[^,.0-9]/", '', $b);
    if (strlen($v1) == 0) return $a;
    $str = preg_replace("/[,.0-9]/", '', $b);
    $v = number_format($v1 + $v2, 2, '.', ' ');
    return trim($v . ' ' . $str);
  }

  private function sum_array($a, $b)
  {
    foreach ($a as $index => $v) {
      if (!isset($b[$index])) continue;
      //d($v,$b[$index]);
      if (is_array($v)) {
        $a[$index] = $this->sum_array($v, $b[$index]);
      } else {
        if (in_array($index, ['name', 'value'])) continue;
        $a[$index] = $this->sum_cost($v, $b[$index]);
      }
    }
    return $a;
  }

  public function renderTemplate($data, $language = false, $params_id = false, $cafe_id = false)
  {
    if (!empty($data['visitor']) && $language == false) {
      $language = empty($data['visitor']['lg']) ? '' : $data['visitor']['lg'];
    } elseif (!empty($data['user']) && $language == false && !empty($data['user']['lg'])) {
      $language = $data['user']['lg'];
    }

    if (!empty($language)) {
      Yii::$app->language = $language; //устанавливаем язык
    }
    if (!empty($data['cafe']) && $data['cafe']['id'] && $data['cafe']['id'] != Yii::$app->cafe->id) {
      Yii::$app->cafe->start($data['cafe']['id']);//инициализация кафе
    }

    $tpl = $this->getTemplate($language, $params_id, $cafe_id);

    if(!empty($data['cafe']) && !empty($data['cafe']['vat_code'])){
      $vats = [];
      foreach ($data['cafe']['vat_code'] as $name => $vat){
        if(!empty($vat)){
          $vats[]=$name.':  '.$vat['value'];
        }
      }
      if(!empty($vats)){
        $data['cafe']['vat_code_line'] = implode($vats,', ');
        $data['cafe']['vat_code_column'] = implode($vats,'<br>');
      }
    }

    $total_data = false;
    $count_total = 0;
    foreach ($data as $k => $d) {
      if (strpos($k, 'total_') !== false) {
        $count_total++;
        //d($d);
        if (!$total_data) {
          $total_data = $d;
        } else {
          $total_data = $this->sum_array($total_data, $d);
        }
      }
    };
    //ddd($total_data);
    if ($count_total > 1) {
      $data['total'] = true;
      $data['total_total'] = $total_data;
    }

    $content = Yii::$app->TwigString->render(
        $tpl,
        $data
    );

    $site_url = isset(Yii::$app->params['site_url']) ?
        Yii::$app->params['site_url'] :
        (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://" . $_SERVER["HTTP_HOST"];
    preg_match_all('/(img|src)=("|\')[^"\'>]+/i', $content, $result);
    $result = preg_replace('/(img|src)("|\'|="|=\')(.*)/i', "$3", $result[0]);
    foreach ($result as $img_base) {
      if (strpos($img_base, '//') !== false) continue;
      $img = $img_base;
      if ($img[0] != "/") $img = "/" . $img;
      $img = $site_url . $img;
      $content = str_replace($img_base, $img, $content);
    }

    if ($this->subject) {
      $this->subject = Yii::$app->TwigString->render(
          $this->subject,
          $data
      );
    }

    return $content;
  }

  public function getParams()
  {
    if (!$this->_params) {
      $file = $this->config_files[$this->type_id] . ".json";
      $this->_params = Yii::$app->helper->load_json($file);
    }
    return $this->_params;
  }

  public function getMyWidth()
  {
    if (isset($this->params['is_print']) && $this->params['is_print']) {
      return Yii::$app->cafe->width;
    } else {
      return $this->getAttribute('width');
    }
  }

  public function getTable_list()
  {
    $table_list = [];
    if ($this->type_id == self::TYPE_CHECK_PRINT) {
      $table_list['visits'] = 'visits';
      $table_list['cart'] = 'cart';
      $table_list['sum'] = 'total';
    }
    if ($this->type_id == self::TYPE_CHECK_MAIL) {
      $table_list['visits'] = 'visits';
      $table_list['cart'] = 'cart';
      $table_list['sum'] = 'total';
    }
    return $table_list;
  }
  /*
    private function xmlpp($xml, $html_output=false) {
      $xml_obj = new \SimpleXMLElement($xml);
      $level = 4;
      $indent = 0; // current indentation level
      $pretty = array();

      // get an array containing each XML element
      $xml = explode("\n", preg_replace('/>\s*</', ">\n<", $xml_obj->asXML()));

      // shift off opening XML tag if present
      if (count($xml) && preg_match('/^<\?\s*xml/', $xml[0])) {
        $pretty[] = array_shift($xml);
      }

      foreach ($xml as $el) {
        if (preg_match('/^<([\w])+[^>\/]*>$/U', $el)) {
          // opening tag, increase indent
          $pretty[] = str_repeat(' ', $indent) . $el;
          $indent += $level;
        } else {
          if (preg_match('/^<\/.+>$/', $el)) {
            $indent -= $level;  // closing tag, decrease indent
          }
          if ($indent < 0) {
            $indent += $level;
          }
          $pretty[] = str_repeat(' ', $indent) . $el;
        }
      }
      $xml = implode("\n", $pretty);
      return ($html_output) ? htmlentities($xml) : $xml;
    } */
}
