<?php
/**
 * Created by PhpStorm.
 * User: acid
 * Date: 16.09.18
 * Time: 10:33
 */

namespace frontend\modules\templates\models;

use common\components\VatHelper;
use frontend\modules\cafe\models\CafeParams;
use frontend\modules\certificate\models\Certificate;
use frontend\modules\visitor\models\Visitor;
use Yii;

class TemplateTestForm extends \yii\base\Model
{
  public $options;

  public $data;

  private $_rules = [];
  private $_attributes = [];
  private $_attributes_labels = [];
  private $_attributes_hints = [];

  /* @var Template */
  private $_template;

  public function getFieldTemplate($fieldOptions)
  {
    return [];
  }

  /**
   * Creates a form model for given template.
   *
   */
  public function __construct(Template $template)
  {
    $this->_template = $template;

    parent::__construct();
  }

  public function init()
  {
    $this->configureOptions($this->getVisitorCheckOptions());

    parent::init(); // TODO: Change the autogenerated stub
  }

  public function rules()
  {
    return array_merge([], $this->_rules);
  }

  public function attributeLabels()
  {
    return array_merge(parent::attributeLabels(), $this->_attributes_labels);
  }

  public function attributeHints()
  {
    return array_merge(parent::attributeHints(), $this->_attributes_hints);
  }

  public function process()
  {
    if (!$this->validate()) {
      return false;
    }

    foreach ($this->options as $fieldName => $fieldOptions) {
      if (isset($fieldOptions['fetchData'])) {
        $fetchData = $fieldOptions['fetchData'];
        call_user_func($fetchData, $this->{$fieldName});
      }
    }

    return true;
  }

  public function getContent()
  {
    $id = $this->_template->id;

    if ($this->_template->params['is_print']) {
      $jsonParams = json_encode($this->data);

      return Yii::$app->view->closeModal() . "<script>app.print_check_by_params({$id}, $jsonParams)</script>";
    } else {
      $content = $this->_template->renderTemplate($this->data);

      try {
        $sended = \Yii::$app->mailer->compose()
            ->setFrom(Yii::$app->params['robotEmail'])
            ->setTo($this->email)
            ->setSubject(Yii::t('main', 'Cafe Email template test letter'))
            ->setHtmlBody($content);

        //$content='test';
        if (Yii::$app->cafe->get()->pdf_to_mail) {
          Yii::$app->helper->addPdfToMail($sended, $content);
        }
        $sended->send();
      } catch (\Exception $e) {
        $sended = false;
      }

      if ($sended) {
        return Yii::t('main','Email successfully sended, check your inbox');
      } else {
        return Yii::t('main','Email sending error');
      }
    }

    return 'Test';
  }

  public function getVisitorCheckOptions()
  {
    $cafe = Yii::$app->cafe->get();
    $params = $cafe->getParam()->asArray()->one();
    $langParams = CafeParams::composeLangParams($params);
    $cafeCurrency = Yii::t('app', $cafe->currency);

    $options = [];
    $summary_vat = [];

    if (in_array($this->_template->type_id, [Template::TYPE_CHECK_MAIL, Template::TYPE_CHECK_PRINT])) {
      $total_visit = [
          'cost' => 0,
          'sum' => 0,
          'vat' => [],
          'vat_total' => 0,
      ];

      $visit = [
          'id' => 4654,
          'add_time' => date($langParams['datetime'], strtotime('2018-10-17 21:03:57')),
          'finish_time' => date($langParams['datetime'], strtotime('2018-10-17 22:03:57')),
          'duration' => Yii::$app->helper->echo_time(3600),
          'pause' => Yii::$app->helper->echo_time(0),
          'cost' => 5.06,
          'sum' => 4.4,
          'guest_m' => 0,
          'guest_chi' => 0,
      ];

      list($sum, $cost, $vat, $vatTotal) = VatHelper::calculate($visit['sum']);
      $visit['vat'] = $vat;

      $total_visit['cost'] = $visit['cost'];
      $total_visit['sum'] = $visit['sum'];

      // VAT Merging copy-paste from populateUniteData()
      foreach ($visit['vat'] as $vat) {
        $vat_merged = false;

        foreach ($summary_vat as $uniteVatIndex => $uniteVat) {
          // If VAT equals - merge it
          if ($uniteVat['name'] == $vat['name']) {
            $vat_merged = true;
            $summary_vat[$uniteVatIndex]['vat'] = ((float)$summary_vat[$uniteVatIndex]['vat'] + (float)$summary_vat[$uniteVatIndex]['vat']);
          }
        }

        // If VAT is absent - add it
        if (!$vat_merged) {
          $summary_vat[] = $vat;
        }

        $visit['vat'][$vat['name']] = $vat;
        $visit['vat'][$vat['name']]['vat'] .= ' ' . $cafeCurrency;
      }

      foreach ($summary_vat as $sVat) {
        $total_visit['vat'][$sVat['name']] = $sVat;
        $total_visit['vat'][$sVat['name']]['vat'] .= ' ' . $cafeCurrency;
        $total_visit['vat_total'] += $sVat['vat'];
      }

      $total_visit['cost'] .= ' ' . $cafeCurrency;
      $total_visit['sum'] .= ' ' . $cafeCurrency;
      $total_visit['vat_total'] .= ' ' . $cafeCurrency;

      $this->data = [
          'visits' => [$visit],
          'total_visits' => $total_visit,
          'visitor' => null,
      ];
      $options = array_merge($options, [
          'visitorLog_userData' => [
              'label' => Yii::t('app', 'Visitor'),
              'value' => 1,
              'rules' => [
                  ['required'],
              ],
              'inputOptions' => [
                  'type' => 'dropDown',
                  'items' => [
                      0 => Yii::t('app', 'Anonymous'),
                      1 => Yii::t('app', 'Regular'),
                  ],
              ],
              'fetchData' => function ($value) {
                if ($value == '1') {
                  $visitor = new Visitor();
                  $visitor->setAttributes([
                      'f_name' => 'John',
                      'l_name' => 'Wick',
                      'code' => 'VISITOR_CODE',
                      'email' => 'john.wick@example.com',
                      'phone' => '+381234567890',
                      'lg' => 'en-EN',
                  ]);
                  $this->data['visitor'] = $visitor;
                }
              },
          ],
          'visitorLog_guest_mature' => [
              'label' => Yii::t('app', 'Visitor with mature guests'),
              'value' => 1,
              'rules' => [
                  ['required'],
              ],
              'inputOptions' => [
                  'type' => 'checkbox',
              ],
              'fetchData' => function ($value) {
                if ($value == '1') {
                  $this->data["visits"][0]['guest_m'] = 7;
                }
              },
          ],
          'visitorLog_guest_children' => [
              'label' => Yii::t('app', 'Visitor with children'),
              'value' => 1,
              'rules' => [
                  ['required'],
              ],
              'inputOptions' => [
                  'type' => 'checkbox',
              ],
              'fetchData' => function ($value) {
                if ($value == '1') {
                  $this->data["visits"][0]['guest_chi'] = 3;
                }
              },
          ],
          'visitorLog_certificate' => [
              'label' => Yii::t('app', 'Certificate applied'),
              'value' => 1,
              'rules' => [
                  ['required'],
              ],
              'inputOptions' => [
                  'type' => 'checkbox',
              ],
              'fetchData' => function ($value) {
                if ($value == '1') {
                  $label = Certificate::getTypeLabels(Certificate::TYPE_FREE_TIME);
                  $this->data["visits"][0]['certificate'] = $label . ' - ' . '10' . Yii::t('app', ' minute(s)');
                }
              },
          ],
      ]);
    }

    if (in_array($this->_template->type_id, [Template::TYPE_TIMETABLE_MAIL])) {
      $this->data['event'] = [
          'start' => '2018-12-22 07:00:00',
          'end' => '2018-12-22 17:00:00',
      ];
    }

    $this->data['cafe'] = $cafe->getAttributes(['id', 'name', 'max_person', 'address', 'currency', 'vat_code']);
    $this->data['cafe']['logo'] = $cafe->getLogo();
    $this->data['user'] = Yii::$app->user->identity->getAttributes(['email', 'name']);

    if (!$this->_template->params['is_print']) {
      $options = array_merge($options, [
          'email' => [
              'label' => Yii::t('app', 'Send test to Email'),
              'value' => Yii::$app->user->identity->email,
              'rules' => [
                  ['required'],
              ],
          ],
      ]);
    }

    return $options;
  }

  public function configureOptions($options)
  {
    $this->options = $options;

    foreach ($options as $fieldName => $fieldOptions) {
      // Attribute
      $this->_attributes[$fieldName] = $fieldOptions['value'];

      // Label
      if (isset($fieldOptions['label'])) {
        $this->_attributes_labels[$fieldName] = $fieldOptions['label'];
      }

      // Hint
      if (isset($fieldOptions['hint'])) {
        $this->_attributes_hints[$fieldName] = $fieldOptions['hint'];
      }

      // Rules
      $rules = $fieldOptions['rules'];
      array_unshift($rules, ['safe']);

      foreach ($rules as $rule) {
        array_unshift($rule, [$fieldName]);
        $this->_rules[] = $rule;
      }
    }
  }

  /**
   * @inheritdoc
   */
  public function canGetProperty($name, $checkVars = true, $checkBehaviors = true)
  {
    if (isset($this->_attributes[$name])) {
      return true;
    }

    return parent::canGetProperty($name, $checkVars, $checkBehaviors);
  }

  /**
   * @inheritdoc
   */
  public function canSetProperty($name, $checkVars = true, $checkBehaviors = true)
  {
    if (isset($this->_attributes[$name])) {
      return true;
    }

    return parent::canSetProperty($name, $checkVars, $checkBehaviors);
  }

  /**
   * @inheritdoc
   */
  public function __get($name)
  {
    if (isset($this->_attributes[$name])) {
      return $this->_attributes[$name];
    }

    return parent::__get($name);
  }

  /**
   * @inheritdoc
   */
  public function __set($name, $value)
  {
    if (isset($this->_attributes[$name])) {
      $this->_attributes[$name] = $value;
    } else {
      parent::__set($name, $value);
    }
  }
}